### ISSUE TITLE
Crash:exception in server tick loop

### ISSUE THREAD

**Issue by viceroy369** [Snownee/SnowRealMagic#10]
I get this crash in my modpack from Snow Real Magic! when I try to update to version 0.3.3

  https://paste.dimdev.org/iquporiyoc.mccrash

Crash occurs on world generation.

**Comment by Snownee** [comment]
Use the latest Forge------------------ 原始邮件 ------------------
发件人: "viceroy369"<notifications@github.com>
发送时间: 2019年9月19日(星期四) 上午7:30
收件人: "Snownee/SnowRealMagic"<SnowRealMagic@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Snownee/SnowRealMagic] Crash:exception in server tick loop (#10)



I get this crash in my modpack from Snow Real Magic! when I try to update to version 0.3.3
 
https://paste.dimdev.org/iquporiyoc.mccrash
 
Crash occurs on world generation.
 
&mdash;

**Comment by Snownee** [comment]
Remove `1.12` folder in `mods` folder
