### ISSUE TITLE
Client crash - ticking entity - Cannot get property IntegerProperty(...)

### ISSUE THREAD

**Issue by madmax3004** [Snownee/SnowRealMagic#106]
* Forge Version: forge-35.1.37
 * Mod Version: 1.16.4-2.3.0

Was walking around on a freshly created world on a server. Got attacked by a dragon and died, respawned and after being attacked again I crashed. The log seems to imply an issue with snow blocks and explicitly mentions this mod.

https://pastebin.com/Xaynwew8

**Comment by Snownee** [comment]
looks like Performant
