### ISSUE TITLE
Slab textures are enlarged when snow falls on them

### ISSUE THREAD

**Issue by Hukenon** [Snownee/SnowRealMagic#108]
* Forge Version: 1.16.4 - 35.1.28
 * Mod Version: 2.3.0
 * Slab textures zoom in when snow falls on them. This seems to accumulate somehow until the slab texture is a solid color. Does not seem to be affected by amount of snow piled on, but maybe amount of times it snows.

**Comment by Snownee** [comment]
Use Kiwi 3.5.1 to fix this
