### ISSUE TITLE
All stairs, walls, etc. are showing same texture for acacia planks. (1.14.4)

### ISSUE THREAD

**Issue by Rj248** [Snownee/SnowRealMagic#11]
![image](https://user-images.githubusercontent.com/39466898/65520253-4899da00-deb5-11e9-95c3-09d29d479f4f.png)
![image](https://user-images.githubusercontent.com/39466898/65520327-66673f00-deb5-11e9-9ada-d14a645df5d5.png)
![image](https://user-images.githubusercontent.com/39466898/65520349-6d8e4d00-deb5-11e9-9d38-f0af5872cd5a.png)
I have no idea what is going on but this bug exists

**Comment by Snownee** [comment]
Optifine?

**Comment by Snownee** [comment]
It might be this issue:

https://github.com/sp614x/optifine/issues/2876

**Comment by Rj248** [comment]
Yeah it was optifine...
