### ISSUE TITLE
[Bug] Side textures of snow are glitched and allow you to see through the world.

### ISSUE THREAD

**Issue by Corvus20** [Snownee/SnowRealMagic#113]
* Forge Version: 1.16.5-36.0.43
 * Mod Version: 1.16.4-2.3.2

Screenshots:

![2021-02-25_09 29 38](https://user-images.githubusercontent.com/75586106/109171302-a5a35a80-774f-11eb-9bf7-ca196434f8d1.png)
![2021-02-25_09 29 43](https://user-images.githubusercontent.com/75586106/109171304-a5a35a80-774f-11eb-95c1-ecba68f95434.png)
![2021-02-25_09 32 55](https://user-images.githubusercontent.com/75586106/109171306-a5a35a80-774f-11eb-877d-a28920e33753.png)

This issue can be reproduced without optifine, too, so it isn't an optifine issue.

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue

**Comment by QuerrixTU** [comment]
Hello, this bug is from an old version of ferrite core mod. Installe the latest version to corret that glitch.

**Comment by Corvus20** [comment]
Hey, sorry for not responding to this promptly. It has fixed with the latest version of the ferrite core mod. I'll close this now.
