### ISSUE TITLE
Grass tile entity lag

### ISSUE THREAD

**Issue by ghost** [Snownee/SnowRealMagic#115]
When snow accumulates in areas, especially with tons of grass, the tile entities creates a huge amount of lag. You can see the amount of memory blockentities takes up in the bottom right hand corner. (This example has 2500 grass/snow tile entities in a 50x50 area)

![2021-03-14_04 18 31](https://user-images.githubusercontent.com/60119200/111066760-eef8e700-847d-11eb-85fe-6ab878f495f4.png)

And here's what it looks like without the tile entities in view

![2021-03-14_04 32 57](https://user-images.githubusercontent.com/60119200/111066862-6c245c00-847e-11eb-893f-38a72b7532f9.png)

 * Forge Version: 36.0.58
 * Mod Version: 2.3.2

**Comment by Snownee** [comment]
First thank you for your time to test these. I did these too and I know it's laggy too. However optimizing this requires many efforts and I am not good at rendering stuff. So the best choice currently is turn off this feature.
