### ISSUE TITLE
Tetra shovels cannot produce snowball when mining snow

### ISSUE THREAD

**Issue by Mooncat25** [Snownee/SnowRealMagic#116]
### **Description**
Using any shovel from Tetra to break snow does not produce snowball while Minecraft shovel does.

### **Steps to reproduce**
1. Start in creative mode. Go to a snowy biome or simply place some snow manually.
2. Get yourself a Tetra workbench, a Tetra hammer (stone or better), a Minecraft iron shovel and an iron ingot.
3. Change to survival mode.
4. Use the Minecraft shovel to break snow. Snowball will be dropped.
5. To make a Tetra shovel: Place the Tetra workbench. Right click it. Put the Minecraft shovel on its slot. Click "Iron shovel", then "Shovel head". Place the iron ingot in the slot near "Head material". Click "Craft". The shovel is now Tetra shovel. Now you can take it out.
6. Use the Tetra shovel to break snow. No snowball will be dropped. But snowball drop is expected.

### **Forge Version**
36.1.0

### **Mod Version**
Kiwi-1.16.5-3.4.2
SnowRealMagic-1.16.4-2.3.3
tetra-1.16.5-3.8.0 ([Link](https://www.curseforge.com/minecraft/mc-mods/tetra))
mgui-1.16.4-3.1.3 (Required by tetra) ([Link](https://www.curseforge.com/minecraft/mc-mods/mgui))

I'm not certain whether this bug belongs to Tetra or this mod, but I was told this mod is using the old method to check for a shovel, so I report this here first.

**Comment by codewolf219** [comment]
I'm also experiencing this same issue.

**Comment by Snownee** [comment]
I think you should report it to Tetra devs. Looks like they hardcoded all mineable blocks, I don't know why

**Comment by codewolf219** [comment]
This is also a problem with unified tools such as a Mattock and Paxel in Silent Gear - basically if it isn't explicitly a shovel your snow cannot be harvested.

**Comment by Mooncat25** [comment]
I have just put this issue on Tetra's discord, but I think it would be better if I notify @mickelus here. Sorry if it is not appropriate.
