### ISSUE TITLE
Extreme lag accompanied by console spam talking about trying to place snow blocks and dummy blocks

### ISSUE THREAD

**Issue by Corvus20** [Snownee/SnowRealMagic#118]
* Forge Version: 1.16.5, forge 36.1.0
 * Mod Version: 1.16.4-2.5.2

[latest.log](https://github.com/Snownee/SnowRealMagic/files/6205474/latest.log)

*I have been unable to get pastebin, or any alternatives, to work properly so far. I will update this issue with the proper link if I get one to work.

**Comment by didis54** [comment]
I'm also facing this issue
 * Forge Version: 36.1.1
 * Mod Version: 2.5.1

Posting part of the logs as the whole file is too big, hope that can help
https://paste.ubuntu.com/p/xR7s2D9CDp/

**Comment by Snownee** [comment]
I have fixed most of the spams. But this issue still exists. Idk how to completely fix it
