### ISSUE TITLE
Saplings won't grow if surrounded by snow

### ISSUE THREAD

**Issue by lebanni** [Snownee/SnowRealMagic#120]
* Forge Version: forge-1.16.5-36.1.0.jar
 * Mod Version: SnowRealMagic-1.16.4-2.5.3.jar

If a sapling is on a snow tile, it won't grow.

**Comment by lebanni** [comment]
I think thre is the same issue for 2x2 saplings like dark oak.

**Comment by Snownee** [comment]
> I think thre is the same issue for 2x2 saplings like dark oak.

Yeah this is a known issue but it is hard to fix so I gave up
