### ISSUE TITLE
[Minor Bug] Client force to show extended info for tags

### ISSUE THREAD

**Issue by pwigary** [Snownee/SnowRealMagic#122]
* Forge Version: 36.1.2
 * Mod Version: 1.16.4-2.5.4.jar and kiwi is 1.16.5-3.4.2.jar

Client force to show extended info for tags without pressing the control button.

Reference:

https://ibb.co/XXmc0XB
https://ibb.co/sm1cSwT
https://ibb.co/ftPCzrF

**Comment by Snownee** [comment]
this is not a bug. just do not turn on the extended info

**Comment by pwigary** [comment]
But it was off though. That's why I state(forced), putting the mod in the pack it happens.

[jeiintegration-client.txt](https://github.com/Snownee/SnowRealMagic/files/6304343/jeiintegration-client.txt)

**Comment by Snownee** [comment]
you can disable it in kiwi-client.toml
