### ISSUE TITLE
Ticking entity exception when TNT minecart explodes on snow layers

### ISSUE THREAD

**Issue by AndyPie88** [Snownee/SnowRealMagic#126]
* Forge Version: 36.1.4
 * Mod Version: SnowRealMagic-1.16.4-2.5.5.jar & Kiwi-1.16.5-3.4.2.jar 

https://paste.ubuntu.com/p/CjfbR2swcR/

This crash seems to be inconsistent but can be triggered by this interaction.

**Comment by Snownee** [comment]
What is the block under snow layers, or are the snow layers more than one block? It looks like it is a vanilla bug

**Comment by AndyPie88** [comment]
Found a way to trigger the crash. Tested on both vanilla and modded client, only crashed with modded.

Place at least 5 layers of snow then drop a TNT minecraft on top of it. It should crash immediately.

**Comment by Snownee** [comment]
thanks, I will test that. You dont have to test it in vanilla because vanilla doesn't refer to the block so the crash will not be triggered

**Comment by Snownee** [comment]
ok, try make tnt minecart explodes on redstone ore 👀

**Comment by AndyPie88** [comment]
Oh dear...
Fired off a bug report to Mojang. Might wanna hide that going forward:)

**Comment by Snownee** [comment]
I have done that. and a patch version of my mod will be released today
