### ISSUE TITLE
[Feature Request] Allow non-full blocks to be placed in the same space as carpets

### ISSUE THREAD

**Issue by pm065** [Snownee/SnowRealMagic#129]
(This isn't the same as #25)
Would it be possible to make non-full blocks placeable on carpets? To prevent situations like this:
![2021-05-09_07 53 16](https://user-images.githubusercontent.com/81559564/117563129-c23b0780-b09b-11eb-892c-6209ae304d95.png)
where if you just remove the carpet in the spot it looks odd and mismatched:
![2021-05-09_07 54 59](https://user-images.githubusercontent.com/81559564/117563150-e1399980-b09b-11eb-83b9-5952a9050b90.png)
This is probably outside SRM's scope, though...

**Comment by Snownee** [comment]
Use [Kaleido](https://www.curseforge.com/minecraft/mc-mods/kaleido)
