### ISSUE TITLE
Generated Texture does not respect IBlockColor

### ISSUE THREAD

**Issue by pupnewfster** [Snownee/SnowRealMagic#14]
* Minecraft Version: 1.14.4
 * Mod Version: 1.1.1

I was working on setting up a private pack for a few friends so we can mess around with testing what things are still broken/not ported yet for Mekanism. And I noticed that this mod does not properly support coloring textures for blocks that use IBlockColor. https://github.com/mekanism/Mekanism/blob/1.14.x/src/additions/java/mekanism/additions/client/AdditionsClientRegistration.java is the class in which I register the color providers.

I doubt there is an easy fix, for this issue, and it isn't the easiest to test as there is no release version of mekanism available for 1.14, but I figured you should at least be aware of the issue.

**Comment by pupnewfster** [comment]
This issue is *mostly* fixed but it still looks a little odd at the bottom
![image](https://user-images.githubusercontent.com/1203288/66256405-80c5d600-e75b-11e9-90ec-e24aa9222928.png)


I believe this is because of not including the tint index here: https://github.com/Snownee/SnowRealMagic/blob/1.14/src/main/resources/assets/snowrealmagic/models/block/fence_side.json#L25-L29

**Comment by Snownee** [comment]
oops, thanks for pointing that out
