### ISSUE TITLE
issue with dynamic trees and passable leaves, almost certainly the same issue being expressed with both mods

### ISSUE THREAD

**Issue by pibblepower** [Snownee/SnowRealMagic#140]
Okay, here's the issue (I'm using 0.5.3 of the 1.12.2 version and forge 14.23.5.2855). When I have dynamic trees installed, snow that's placed at least one block above and allowed to allowed to fall onto the leaves of a dynamic tree, it seems to sink halfway into the leaf block before disappearing. And if passable leaves are installed, the snow can be placed on any leaf block without needing to be placed above and it sinks right through all the way. I think this is an issue with the leaf blocks being passable (dynamic tree leaves are semi-passable, while leaves are completely passable with passable leaves installed). To reproduce the issue, install the latest version of 1.12.2 SnowRealMagic and/or passable leaves and dynamic trees, using the latest forge version and do what I described to reproduce the issue. Long story short, can this be patched?

**Comment by Desoroxxx** [comment]
Same issues on my side

**Comment by ghost** [comment]
God, this is really killing my modpack. I really hope they can figure out a way to patch this.

Maybe prevent gravity upon initial worldgen?

**Comment by Desoroxxx** [comment]
I just removed SnowRealMagic out of my modpack until this issue get fixed
