### ISSUE TITLE
Crash with something, but I cant figure out what.

### ISSUE THREAD

**Issue by Corvus20** [Snownee/SnowRealMagic#141]
* Forge Version: Forge 36.2.2 for Minecraft 1.16.5
 * Mod Version:  1.16.4-2.6.0
 * Can you reproduce this issue with relevant mods only?: I cant even figure out which mods are relevant beyond Snow! Real Magic! Perhaps you can get more out of the crash logs than I could?

Initial Crash Report from my personal modpack:
https://paste.ubuntu.com/p/WKbmHWdGzn/

**Comment by aedans** [comment]
I'm getting the same error, looks like there was a NPE here https://github.com/Snownee/SnowRealMagic/blob/1ed8bf510be2e04d99c1e0d1b1337bd50d7302a3/src/main/java/snownee/snow/block/ModSnowTileBlock.java#L107
