### ISSUE TITLE
Snowy biomes not registering at all in the overworld

### ISSUE THREAD

**Issue by NighthowlerStudios** [Snownee/SnowRealMagic#142]
* Forge Version: 36.2.4
 * Mod Version: 2.6.0+
 * Can you reproduce this issue with relevant mods only?: yes

nothing in the log says it, but your recent mod update did nothing but make all snowy biomes (including vanilla) fail to register and thusly fail to generate in the overworld

in modded dimensions where snowy biomes *do* manage to spawn, I have experienced the performance lag to be *way worse* than before, resulting in GC spam

whatever "change" was committed needs to be reverted.

**Comment by NighthowlerStudios** [comment]
Note: downgrading to 2.5.x fixes this.

**Comment by Snownee** [comment]
Could you provide more information? I don't remember I imported "optimization" in 2.6+

**Comment by NighthowlerStudios** [comment]
Version 2.6.1: "Reduced lag after world generation"

This bug I encountered might actually be tied to something on Kiwi library side, however the issue still remains if I install this update along with its associated Kiwi version.

When I play my modpack on 2.6.1, all snow biomes (including modded ones) get entirely unregistered.  I think something faltered with your snow block that made it inaccessible from placers and caused forge to reject the biomes.  But I'm not a modder so I only have a guess based on my knowledge of code.

**Comment by NighthowlerStudios** [comment]
Furthermore, whilst the issue is present, a dimension mod Ultra Amplified Dimension sees the snow biomes fine.  This let me generate snow to benchmark with, and lo and behold, performance actually is worse than it was in 2.5.7.

and it's a render and update issue.  I think the falling snow fix you added in 2.6.0 has broken the snow block class.

**Comment by NighthowlerStudios** [comment]
you can test this yourself by manually updating the modpack Kaleidio's Battle Pack 3.6.2 off of CurseForge.  I ship with your mod's 2.5.7 to avoid this reproducible issue.

**Comment by NighthowlerStudios** [comment]
You are able to see that something has happened to the registry by attempting /locatebiome (any snow biome here)

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/137461073-213ca2ce-b5b5-4e0e-8400-a5eca1f6e43b.png)

There is no such changelog. that description is for MC 1.12.2

**Comment by NighthowlerStudios** [comment]
Strange, CurseForge app says differently

nonetheless changes made in 2.6.0 and 2.6.1 has broken biome gen

I can retest and post screenshots and logs if you really need me to.

**Comment by NighthowlerStudios** [comment]
cool now curseforge app is showing some *entirely different* version with "fix bugs"

**Comment by NighthowlerStudios** [comment]
weirdly the issue disappeared.  I guess whatever mod was colliding fixed it ever since I found this issue.  Closing until I find it again somehow...
