### ISSUE TITLE
1.12 楼梯和半砖没有雪，此外和cuisine不兼容

### ISSUE THREAD

**Issue by joe-vettek** [Snownee/SnowRealMagic#145]
我看到1.16.5的模组里会给楼梯和半砖加上雪，请问以后会在1.12.2更新这个功能吗？不然还是有点太奇怪了。
而且很奇怪的是和cuisine的竹子也不兼容，砍伐后放置的竹子以栅栏形式存在，但是不能放置雪。

**Comment by Snownee** [comment]
高版本独有特性
