### ISSUE TITLE
[1.16.5] Snow Tiles act as Full Blocks

### ISSUE THREAD

**Issue by Entralia** [Snownee/SnowRealMagic#146]
Greetings, SnowRealMagic Team. 
Love your mod, and all it does to the world.

Just one small issue though:
- Whenever a block is placed above a Snow Tile, that Snow Tile acts as a solid block 
(to the point that I could even jump on top of the Snow Tile, and it would look like I'm floating)

I'd suspected that it was SnowRealMagic that caused the issue, since I don't think I have any other mods that affect Snow.

Hope it gets resolved sometime soon.
Thanks once again for this amazing mod!
Take care, and stay safe, dear reader!

**Comment by Snownee** [comment]
I don't know what you mean "floating" but I think this is intended

**Comment by Entralia** [comment]
Hello there! 

Sorry! I should have provided an example or two:
- a cobweb directly on a snow tile will cause the snow tile to become solid (meaning you have to jump on the snow tile to walk through the cobweb, instead of walking through it normally)
- basically any block on top of the snow tile will cause the tile to become completely solid (like a barrier block)

Hope this helps! 

Edit: I believe I have discovered the same issue as Closed Issue #134

**Comment by Snownee** [comment]
That issue has been fixed. Please make sure you are using the latest version

**Comment by Entralia** [comment]
thank you very much!
