### ISSUE TITLE
[1.12.2] Compatibility: Remove Snow from Removed Trees

### ISSUE THREAD

**Issue by Ameranth** [Snownee/SnowRealMagic#147]
Hello and thank you for your work!

When chunks are generated with snow on leaf blocks of trees, the snow layers remain floating mid-air if the tree is removed due to postgen features like biomesoplenty lakes, or reccurent complex structures.

I've observed this with dynamictrees, I am unsure if it happens without them.

Thank you for your itme!

**Comment by Snownee** [comment]
Sorry, I don't fix vanilla bugs.

**Comment by Ameranth** [comment]
Thanks for the reply, didn't know it was a vanilla issue.

**Comment by Snownee** [comment]
https://bugs.mojang.com/browse/MC-610
