### ISSUE TITLE
[1.16.5] falling snow physics no longer applies as of 2.7.1

### ISSUE THREAD

**Issue by NighthowlerStudios** [Snownee/SnowRealMagic#149]
* Forge Version: 36.2.4
 * Mod Version: 2.7.1+
 * Can you reproduce this issue with relevant mods only?: haven't checked (possibly not, used Kaleidio's Battle Pack available on curseforge)

no logs report on it.  but the bug is server side

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/140598475-037d674c-7282-48ad-aa3b-6e1b191b6701.png)

I can't reproduce it

**Comment by NighthowlerStudios** [comment]
You don't seem to be using Kaleidio's Battle Pack for testing in that instance, your test is invalid.

The issue might be a mod collision with another mod in said pack

**Comment by NighthowlerStudios** [comment]
Falling snow not falling was caused by a server side lockup of a separate mod, closing.
