### ISSUE TITLE
Connection issue with non wooden fences

### ISSUE THREAD

**Issue by pupnewfster** [Snownee/SnowRealMagic#15]
* Minecraft Version: 1.14.4
 * Mod Version: 1.2.0

While testing my fences I noticed that the snow variant stops connecting with the normal variant. This is reproduceable with vanilla's nether brick fence. I believe the fix is to proxy the material here: https://github.com/Snownee/SnowRealMagic/blob/1.14/src/main/java/snownee/snow/block/SnowFenceBlock.java#L78 to be the material of the "true" block.

**Comment by Snownee** [comment]
Added a horrible hack...

**Comment by pupnewfster** [comment]
I may try to look at it and see if I can think of some way to make it less hacky and then make a PR if I figure out a better method. Given my guess is it still won't quite work properly for my case as in 1.14 Mekanism uses a "custom" material for the plastic blocks: https://github.com/mekanism/Mekanism/blob/1.14.x/src/additions/java/mekanism/additions/common/block/plastic/BlockPlastic.java#L13 But I do see the problem given I hadn't noticed at first glance that the get material method doesn't have any world information so you can't just query the tile.

**Comment by pupnewfster** [comment]
Ya I am looking into this some, as it stands now after the "hack" you added it seems to be even more broken than before, especially when it comes to connecting with itself based on if there is snow or not. It also still doesn't work with nether brick fences IF the snow gets applied to them after they are already placed instead of just placing the snow variant of the fence.

So I am working on fixing this and a few other oddities I have encountered, and will probably submit a PR later today.
