### ISSUE TITLE
[1.16.5] Optifine Render Regions causing snow to OpenGL Error 1281

### ISSUE THREAD

**Issue by NighthowlerStudios** [Snownee/SnowRealMagic#150]
* Forge Version: 36.2.4+
 * Mod Version: 2.7.1+
 * Can you reproduce this issue with relevant mods only?: no (Optifine)
 
 TO REPRODUCE:
 
 install optifine, go it video settings > performance settings > turn everything on but smooth fps
 
 make a new world of Default type
 
 use /locatebiome to find a snowy biome such as minecraft:snowy_taiga
 
 watch the console for log spam (usually immediate after first chunk shows up with snow)

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/140598423-be4cce74-f713-4b81-a9c4-b31e546789e1.png)

I can't reproduce it

**Comment by NighthowlerStudios** [comment]
I also had Fast Render and Dynamic Updates on.  try testing again.  with 2.7.2 as well as that was the last version I tested on.  

edit: Kaleidio's Battle Pack is not needed to find this issue.

**Comment by NighthowlerStudios** [comment]
Issue easily reproduced when using Kaleidio's Battle Pack 3.7.3 as a core and swapping snow real magic for 2.7.2 (and kiwi to latest)

![2021-11-06_08 48 05](https://user-images.githubusercontent.com/82226641/140603830-f859327d-5911-483e-92b4-062cf3e048f8.jpg)

**Comment by Snownee** [comment]
debugging your modpack is not my job. please make sure you have provided a minimal reproducible example when you reporting bugs

**Comment by Kaleidio** [comment]
I know that, and it's taking me a long time as I have other responsibilities.  if you truly wish for me to debug it, it's gonna take me around two days from now if not more.

**Comment by Kaleidio** [comment]
retested in my pack and yes it is specific to render regions being enabled.  gonna start testing with a batch of mods at a time to see if I can find collision

**Comment by NighthowlerStudios** [comment]
welp.  I'm able to reproduce it with your mod, kiwi, and optifine on their own

mods present:

![image](https://user-images.githubusercontent.com/82226641/140618890-4c17e555-a794-426e-b13e-143a041ff194.png)

proof of bug:
![2021-11-06_17 42 35](https://user-images.githubusercontent.com/82226641/140618897-5903476e-59fa-463a-92f1-bd7bbb5672e1.png)

proof of optifine settings:
![2021-11-06_17 43 20](https://user-images.githubusercontent.com/82226641/140618900-02a35e44-a80f-4df4-831b-c69d742586b9.png)

Hardware specification (to help rule out hardware specificity)
Nvidia RTX 3080 GPU running driver 496.49
Ryzen 7 5800X CPU

notes:

I noticed that on the screenshot you sent you were on a super flat world.  try using /locatebiome in a freshly generated world instead :) it might be occuring on blocks you didn't test

**Comment by NighthowlerStudios** [comment]
There ya go, glad that was quick for me.  a reproducible issue has been found for you.  I have included instructions on the main comment.

hope that's more convenient for ya. if you want video proof I could give that too.

**Comment by NighthowlerStudios** [comment]
also make sure you didn't disable "show opengl errors" in your video settings

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/140619580-ce0db86f-1bf4-41ff-b9bd-7dd1c9678648.png)

still can't reproduce. I also reset options before testing

**Comment by NighthowlerStudios** [comment]
if you need me to send you video recorded proof, I will.  this looks like it could be a hardware specific issue.

**Comment by NighthowlerStudios** [comment]
you might want to have somebody else who has similar hardware to mine test for you

**Comment by NighthowlerStudios** [comment]
and you have show opengl errors on?  did you check the latest.log?

**Comment by Snownee** [comment]
yes. what if you disable snow real magic? will the error occur?

**Comment by NighthowlerStudios** [comment]
the error does not occur without the mod.  if it did then snow real magic 2.5.8 wouldn't be working.

proof:
![2021-11-06_18 27 43](https://user-images.githubusercontent.com/82226641/140620076-fb737a30-9324-48c6-a114-436fb31bff6c.png)

![image](https://user-images.githubusercontent.com/82226641/140620084-72cce18e-f1de-45d0-8050-6b42de3c57e9.png)

**Comment by NighthowlerStudios** [comment]
I can do a version specificity check if you'd like, to see how far back I can go before the error stops

**Comment by Snownee** [comment]
Hello. Could you help me check if it is fixed?

[libs.zip](https://github.com/Snownee/SnowRealMagic/files/7667639/libs.zip)

**Comment by NighthowlerStudios** [comment]
hiya, I'll check right now, sorry for the delay

**Comment by NighthowlerStudios** [comment]
yup, all fixed, will await curseforge publication :)

**Comment by NighthowlerStudios** [comment]
amazing job, and thank you for being strong and supporting optifine, I know what hell it can be
