### ISSUE TITLE
Incompatbility With Halogen the Forge port of [Sodium]

### ISSUE THREAD

**Issue by carolinashark** [Snownee/SnowRealMagic#152]
Modpack; when I had Halogen it makes all snow blocks transparent. Apparently its something to with overriding mixins

![2313](https://user-images.githubusercontent.com/94015244/140997853-f91bcb64-d784-4fb1-abfc-35eb86b2af53.png)

**Comment by Snownee** [comment]
So what's your version? Why did you delete issue template?
