### ISSUE TITLE
1.12.2 // Still no compatibility between SRM and PassableLeaves.

### ISSUE THREAD

**Issue by ghost** [Snownee/SnowRealMagic#156]
### Mod loader

Forge

### Minecraft version

1.12.2

### Mod version

SnowRealMagic-1.12.2-0.6.0

### Modloader version

Forge 1.12.2 - 14.23.5.2855

### Modpack info

https://www.youtube.com/watch?v=X8EpwHdR62k&ab_channel=Finecraft%3AEnhancedSurvival

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

![2021-11-28_16 41 29](https://user-images.githubusercontent.com/71896090/143791143-d23472ea-6706-4c6e-aab0-1084f8618b87.png)

As snow generates, it falls through the leaves due to Passable Leaves. But, rather than stacking as layers with the other snow, it (for some odd reason) "lands" and "hovers" above the snow layers beneath it.

**This only occurs upon generation**. If snow layers are suddenly left "floating" through _other_ circumstances, they properly fall into place. This behavior only occurs when the world is generated.

It's been quite some time since this incompatibility was reported, and I would REALLY love to see a fix implemented!

**Comment by Snownee** [comment]
Can you place snow on leaves?

**Comment by ghost** [comment]
### https://streamable.com/1t1w91

I made a video to show what I mean here!

No, you cannot place snow on leaves with Gravity=true. Snow layers will fall through. However, this _would_ still be acceptable behavior, since it would simply allow 1 extra layer of snow to pile underneath trees, **if** the gravity/stacking was working properly on worldgen.
Unfortunately, on Worldgen, these floating snow layers appear despite Gravity being set to True.

So I looked for another alternative. Another possible alternative would be: Disable gravity, so the snow layers don't fall through on worldgen. That DOES work! Except that it introduces another issue, because SRM doesn't imitate Vanilla snowlayer behavior. What do I mean? In vanilla, unsupported snow layers break upon losing the block beneath them. It's both intuitive and certainly expected behavior. However, in SRM, snow layers do NOT break when losing their supporting block (like in Vanilla). Unfortunately, the snow layers awkwardly stay in the air, hovering and never breaking.

I would really happily donate a number of coffees your way if you can help me get this figured out!

I really think that Option #2 would be the easiest way to fix this. Although it would be a bummer losing gravity features, at least it would allow proper worldgen AND PassableLeaves functionality.

All that means is, could you PLEASE consider a patch where there is an option to allow snow to break when unsupported, like in Vanilla Minecraft?

**Comment by Snownee** [comment]
Thank you for making a video

**Comment by ghost** [comment]
Thanks for taking a look!!
