### ISSUE TITLE
How to disable snow accumulation on certain blocks?

### ISSUE THREAD

**Issue by darchitectlp** [Snownee/SnowRealMagic#158]
### Mod loader

Forge

### Minecraft version

1.16

### Mod version

SnowRealMagic-1.16.4-2.7.2.jar

### Modloader version

MultiMC

### Modpack info

https://www.curseforge.com/minecraft/modpacks/permafrost-eots

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Looking for a place in the config file to specify blocks that should not get snow accumulation. I don't see one; can it be added?

**Comment by Snownee** [comment]
I don't really understand what you mean

**Comment by darchitectlp** [comment]
Sorry, under features you list "Snow layer will accumulate during snow storm!"

Is there a way to disable accumulation on certain blocks? Let's say I don't want snow to accumulate on hay bales; is that possible? Thank you!
