### ISSUE TITLE
[Compat] Snow Under Trees

### ISSUE THREAD

**Issue by Matthysse** [Snownee/SnowRealMagic#160]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

3.0.1

### Modloader version

Forge 39.0.5

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Hello!
Would love to see compatibility with the Snow Under Trees mod (https://www.curseforge.com/minecraft/mc-mods/snow-under-trees) because now, all plants are covered in snow except from plants that are under trees, even with the Snow Under Trees mod installed.

**Comment by TheButterbrotMan** [comment]
@Snownee Will there be any progress on this?

**Comment by Snownee** [comment]
I suggest you to contact with author of Snow Under Trees. I remember they have implemented this for 1.16 before
