### ISSUE TITLE
the snowy fences are invisible

### ISSUE THREAD

**Issue by WalterB304** [Snownee/SnowRealMagic#161]
### Mod loader

Fabric

### Minecraft version

1.18

### Mod version

3.0.1

### Modloader version

Loader 0.12.12 + API 0.45.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

as the title, whenever i place a fence, it gets invisible except for the snow on the top
![Captura de pantalla (7)](https://user-images.githubusercontent.com/96707694/147427022-93314f47-407f-44bb-be63-73e96decc413.png)

**Comment by WalterB304** [comment]
it happens too, to stone walls

**Comment by Snownee** [comment]
Can you provide a full log? Because I can't reproduce it

**Comment by WalterB304** [comment]
where do i go to do that? btw i noticed that every block that can be covered in snow gets invisible, such as flowers, grass, etc.

**Comment by Snownee** [comment]
https://minecrafthopper.net/help/guides/getting-minecraft-latest-log/

**Comment by WalterB304** [comment]
[latest.log](https://github.com/Snownee/SnowRealMagic/files/7781463/latest.log)

**Comment by Snownee** [comment]
Please install Indium, just as what the mod description told you
