### ISSUE TITLE
Illegal argument exception crash on 1.18.1 Fabric

### ISSUE THREAD

**Issue by ghost** [Snownee/SnowRealMagic#162]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

3.0.1

### Modloader version

Fabric loader: 0.12.12 | Fabric API: 0.45.0

### Modpack info

N/A

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/m82CDejU

### Issue description

Mods used: 
Snow! Real Magic! v3.0.1
Kiwi v5.2.2
Fabric API 0.45.0

There seems to be a ticking world exception crash related to this argument exception:
java.lang.IllegalArgumentException: Missing required parameters: parameter minecraft:tool, parameter minecraft:origin
at this method: at snownee.snow.loot.NormalLootEntry.method_433(NormalLootEntry.java:41)

I was able to obtain this crash by finding a snowy plains biome and a spruce village while it was snowing. It took a little for the crash to occur and it didn't happen the instant the chunk loaded. Overall, I've replicated it a few times, all in different worlds with the same biome and village type, however it's not a consistent crash that happens every single time. I'm unsure of what fully causes it. Hopefully this helps.

**Comment by Snownee** [comment]
Thank you
