### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by TheButterbrotMan** [Snownee/SnowRealMagic#163]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

3.0.1

### Modloader version

0.12.12

### Modpack info

https://www.curseforge.com/minecraft/modpacks/deathdusk

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/eQZS2zRE

### Issue description

Does randomly crash. Had multiple crashes.

**Comment by TheButterbrotMan** [comment]
Probably linked to #162

**Comment by Snownee** [comment]
Thank you

**Comment by TheButterbrotMan** [comment]
https://pastebin.com/hkqvpzLf 

Another crash, do you maybe have an eta for the fix?

Its sooooo annoying

**Comment by Snownee** [comment]
Hello, please update SnowRealMagic to 3.0.2
