### ISSUE TITLE
Mod

### ISSUE THREAD

**Issue by santacapra** [Snownee/SnowRealMagic#164]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

2.8.3

### Modloader version

36.2.20

### Modpack info

https://www.dropbox.com/s/1pnqppoge1yfjsg/Elver%20Modpack-1.3.zip?dl=0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/santacapra/fc0f522a921ce2b666b9a464141773db

### Issue description

Snow effect makes blocks underneath it invisible
I'm using the CurseForge modloader but it says it isn't eligible for upload so I'm using dropbox to send it

![image](https://user-images.githubusercontent.com/96798098/147609181-6a8a80be-23ba-4937-ac43-8e61c18b0370.png)

I'm fairly certain this is only due to some of the recent mods i added, so here are some possible mods that might be the one conflicting with it:

Additional Bars
Additional Bars BOP Addon
Additional Lights
Artifacts
Small Ships
Macaw's Bridges

Not sure if its any of those but it could be, or maybe a combination of mods, you prolly know better than me tho :p

**Comment by ghost** [comment]
@santacapra Not the dev, but the v2.8.3 version you are using has Magnesium listed as an incompatibility, which results in the unrendered blocks. v2.6.1 of the mod should be compatible with Magnesium as that's what a group I moderate for is using on their modpacks and we do not have any issues.
