### ISSUE TITLE
Snow does not accumulate on stairs, slabs and fences.

### ISSUE THREAD

**Issue by TheButterbrotMan** [Snownee/SnowRealMagic#165]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

3.0.1

### Modloader version

0.12.12

### Modpack info

https://www.curseforge.com/minecraft/modpacks/deathdusk

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Snow does not accumulate on stairs, slabs and fences.

**Comment by TheButterbrotMan** [comment]
Putting snow manually there, does work.

**Comment by TheButterbrotMan** [comment]
https://i.imgur.com/aD3NGPJ.png

**Comment by Snownee** [comment]
PLEASE UPDATE
