### ISSUE TITLE
the mod doesnt work will valleycraft plants

### ISSUE THREAD

**Issue by Chuunkyz** [Snownee/SnowRealMagic#168]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

3.1.0

### Modloader version

fabric 0.12.12 + api 0.44.0

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### Issue description

i can't put snow on plants from the ValleyCraft mod, however it works with botania for example
can you fix this ? or is it up to valleycraft devs ?

**Comment by Snownee** [comment]
I think the ValleyCraft devs should tag their flowers as `minecraft:small_flowers`, or alternatively use the tag `snowrealmagic:containables`. This is the easiest method
