### ISSUE TITLE
other versions support

### ISSUE THREAD

**Issue by JanoYT** [Snownee/SnowRealMagic#17]
* Minecraft Version: 1.11.2
 * Mod Version: i dont know

it would be cool, if the snow real magic mod would be avaiable in other versions of minecraft, for example in 1.11.2

**Comment by Snownee** [comment]
no

**Comment by JanoYT** [comment]
Why?

Snownee <notifications@github.com> schrieb am So., 6. Okt. 2019, 14:48:

**Comment by Snownee** [comment]
1.11.2 is dead version

**Comment by JanoYT** [comment]
If i would pay you would you make a extra version for me?

Snownee <notifications@github.com> schrieb am Mo., 7. Okt. 2019, 03:42:

**Comment by Snownee** [comment]
I suggest you asking someone else. This project is open source
