### ISSUE TITLE
the mod doesnt work will valleycraft plants 2 (lol)

### ISSUE THREAD

**Issue by Chuunkyz** [Snownee/SnowRealMagic#170]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

3.1.0

### Modloader version

fabric 0.12.12 + api 0.45.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

you said :

_I think the ValleyCraft devs should tag their flowers as minecraft:small_flowers, or alternatively use the tag snowrealmagic:containables. This is the easiest method_

however adding these tags isn't fixing anything...

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/147900038-e994facb-0d9b-4769-94e5-20c298ca2e8f.png)

no need to open a new issue. you can just reply in the issue
