### ISSUE TITLE
Mixin game crash

### ISSUE THREAD

**Issue by syntxx-error** [Snownee/SnowRealMagic#171]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

2.9.0

### Modloader version

36.2.22

### Modpack info

Custom modpack orientated at Sky Farm 

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Invalid-Name/2a527966cccc599c3db4536bde069413

### Issue description

Hey There,
I updated my Modpack and at the moment I tried to connect to the Server my game crashes and give me the Mixin Error.

**Comment by Snownee** [comment]
please provide your latest.log file

**Comment by syntxx-error** [comment]
I put the end of my latest log to a new Gist cause my log is over 2.000.000 lines long
https://gist.github.com/Invalid-Name/547a81ee5b3ebda64cf0c70122401798

**Comment by Snownee** [comment]
I think you should update Magnesium

**Comment by syntxx-error** [comment]
I'm not using this mod, I'm using Halogen cause this mod is in the original Modpack of Sky Farm
Halogen: https://www.curseforge.com/minecraft/mc-mods/halogen
Sky Farm: https://www.curseforge.com/minecraft/modpacks/sky-farm-1-16

**Comment by Snownee** [comment]
eh what is the difference? could you use Magnesium?

**Comment by syntxx-error** [comment]
Hey @Snownee,
I tried to join my Server with `Magnesium` and without cause my game still crashes if I use `Magnesium`.
I'm not sure  if the Problem is only with your mod but without `Magnesium` I can easily join my Server.... the point is, that I need `Magnesium` or `Halogen` cause of my FPS, my FPS are around 100-150 with `Halogen` and without only 10.
I would appreciate if you could fix this.
My latest log with `Magnesium``: 
https://gist.github.com/Invalid-Name/756aa3e4fe960b6a13ef1ea2873b41fd

**Comment by Snownee** [comment]
https://www.curseforge.com/minecraft/mc-mods/betterend-re-forked
