### ISSUE TITLE
rendering incompatibility with sodium Fabric 1.18.1

### ISSUE THREAD

**Issue by ghost** [Snownee/SnowRealMagic#172]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

3.1.0

### Modloader version

Fabric 0.12.12

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

When using the latest version of sodium from github
If you put snow on a fence or flower
Then the texture of the fence or flower will become transparent

bug screenshots https://imgur.com/a/jfQcrwm

**Comment by Snownee** [comment]
Please provide your mod list

**Comment by ghost** [comment]
> Please provide your mod list

fabric api 0.45.2
Snow real magic 3.1.0
Sodium 0.4.0 alpha 5
Kiwi  (Fabric)

**Comment by Snownee** [comment]
Please install Indium
