### ISSUE TITLE
Suggestion: Allow snow to melt when temperature changes

### ISSUE THREAD

**Issue by JacobDB** [Snownee/SnowRealMagic#173]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

3.1.0

### Modloader version

0.12.12

### Modpack info

https://www.curseforge.com/minecraft/modpacks/better-minecraft-fabric

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

This modpack includes Fabric Seasons, which as its name would suggest, enables seasons within Minecraft. When winter rolls around, and it starts snowing, it's awesome that everything gets "snowlogged," it really adds to the effect. The issue is that when spring comes, and the vanilla snow melts, everything that has been "snowlogged" remains that way, forever. You can shift-right-click to "shovel" it, but that's quite difficult when you're dealing with large areas and seasons that come and go quickly.

I'm not very familiar with Minecraft modding, but I believe there's a temperature system, right? If so, I think tying in to this so that if the temperature changes the snow melts would solve this problem for Fabric Seasons and likely any other seasons/weather mod.

**Comment by Beleggrodion** [comment]
I think about the same feature request, i play with friends the modpack https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-fabric witch includes also fabric seasons (the code is found under https://github.com/lucaargolo/fabric-seasons)

When the season changes from winter to spring all the snow begins to slow disapear expect all blocks which are altered by this mod here. 

I don't know if its simpler to add the change back to "no snow" in this mod, or it's easier to made a feature request on fabric seasons to support the "change back" if this mod is installed.

**Comment by JacobDB** [comment]
Yeah, I've been  thinking about that too, seems like it could be solved from either direction, but I figured if this mod solved it, it could be solved in other "season" mods too

**Comment by Snownee** [comment]
should have been fixed hopefully
