### ISSUE TITLE
Tinker's Construct Plate Boots Double Jump Incompatibility 

### ISSUE THREAD

**Issue by CautiousAsparagus** [Snownee/SnowRealMagic#175]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

2.9.0

### Modloader version

36.2.23

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

I have a small modded server. One of the players reports an issue with the Tinker's Construct plate boots and the double jump ability. 

Double jumping is not possible when the jump is started on snow more than one layer high. It can be done on bare blocks, and snow that is one layer high.

It was working correctly before I updated the server yesterday, January 16th, and added in the Snow! Real Magic! mod.

I'm new to this sort of troubleshooting, and looking over both my debug.log and latest.log revealed no errors. I'm not sure where else to look to be of any help.

**Comment by Snownee** [comment]
I can't reproduce it
