### ISSUE TITLE
Z-Fighting Slabs on Fabric with Sodium and Indium

### ISSUE THREAD

**Issue by BenjaminPami** [Snownee/SnowRealMagic#176]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

3.1.0

### Modloader version

Fabric: Loader 0.12.12

### Modpack info

https://www.curseforge.com/minecraft/modpacks/vanilla-with-a-side-of-fries

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Was wandering around and noticed some z-fighting on snow logged slabs, using the most current versions of sodium and indium at the time of posting, sodium 0.4.0 alpha6 and indium 1.0.2 alpha2. I also tried downgrading to sodium 0.4.0 alpha5 and indium 1.0.2 alpha2 and the problem persisted.

**Comment by Snownee** [comment]
screenshots?

**Comment by BenjaminPami** [comment]
![2022-01-21_08 04 38](https://user-images.githubusercontent.com/98132510/150531988-000f01d7-341c-41d5-b888-ccc558cc630c.png)
![2022-01-21_08 04 24](https://user-images.githubusercontent.com/98132510/150531997-f9995b2c-ba9a-40de-b9e6-09494d088961.png)
couple of screens, one with the f3 menu on, if theres any more info i can get you let me know

I also isolated just the mods in question in an install just to make sure it wasnt a compatibility issue with anything else and still get the same z-fighting on the slab, i also tested a few other slabs to see if they gave me the same issue
![2022-01-21_08 12 39](https://user-images.githubusercontent.com/98132510/150533145-652c2c0b-57ed-4a28-beb5-537ea79cb06a.png)
![2022-01-21_08 14 39](https://user-images.githubusercontent.com/98132510/150533155-4225a177-b25f-4f4c-ac22-7f698ce39427.png)

And lastly for the sake of trying it I downgraded versions and tested out indium-1.0.2alpha1, snowrealmagic-3.1.0, sodium- 0.4.0 alpha5 and kiwi5.2.2 and had the same result with zfighting on slabs

If theres anymore info i can give or anything else i can do please do let me know and thanks!

**Comment by subatomic-olive** [comment]
I also have this issue. Have there been any updates?

**Comment by Snownee** [comment]
I currently have no idea about how to fix this issue
