### ISSUE TITLE
2x "Potentially Dangerous alternative prefix" entries in my server's console during launch

### ISSUE THREAD

**Issue by PJRamaglia** [Snownee/SnowRealMagic#180]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

SnowRealMagic-1.18-forge-3.2.0

### Modloader version

forge-1.18.1-39.0.63

### Modpack info

N/A

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/PJRamaglia/c6c85c118a8b34bab1615ac98440dee9

### Issue description

So I noticed the following two [main/INFO] entries, specifically at lines 76 - 77, of my server's latest.log file.  Not really sure if it's a bug or not but I figured I should at least report it just to be safe.

**Comment by Snownee** [comment]
Thanks for reporting. This is intentional
