### ISSUE TITLE
Snow does not build up with Serene Seasons installed

### ISSUE THREAD

**Issue by Jamie-o3** [Snownee/SnowRealMagic#181]
### Mod loader

Forge

### Minecraft version

1.18,1

### Mod version

3.2.1

### Modloader version

36.0.59

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

**Comment by Atlantispy** [comment]
Can confirm this, as soon as I added Snow! Real Magic! to my modlist the snow stopped building up on the ground.

**Comment by Flugel3** [comment]
Yeah, I'm having the same issue. I don't know exactly what's causing it but I will add that in certain biomes that have snow already it melts even in MID-WINTER.
