### ISSUE TITLE
Ice accumulates one layer below water.

### ISSUE THREAD

**Issue by xVIPERx98** [Snownee/SnowRealMagic#184]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

SnowRealMagic-1.18-forge-3.2.2

### Modloader version

Forge 39.0.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/Pa18SvKG

### Issue description

Ice accumulates one layer under the water, rather than being at the topmost layer of the water.
![2022-02-05_19 28 10](https://user-images.githubusercontent.com/72999347/152663550-9c79bda8-4444-4657-bd22-d7219ce26107.png)

**Comment by Snownee** [comment]
I can't reproduce this issue. In general it's impossible to freeze water if its neighbors are all water, and SnowRealMagic does not change this. But in your picture, it breaks this rule. If you have more information you can reopen this issue

**Comment by tobi1449** [comment]
Hi Snownee,
I've got the same issue. 
It seems this is caused by the "snowMakingIce" option when it's snowing. 
The code for this doesn't use any vanilla freezing mechanics but simply checks if there's a water block at the position and sets it to an ice block. Therefore none of the usual freezing rules apply.

**Comment by Snownee** [comment]
Please make sure it is reproducible without other mods, and provide detailed steps to reproduce it

**Comment by xVIPERx98** [comment]
You can close this issue back from February.

Have since updated Minecraft and use other mods.

**Comment by xVIPERx98** [comment]
My bad thought this was a direct message not a thread.
