### ISSUE TITLE
Suggestion: Prevent snow on block using Blaze Powder

### ISSUE THREAD

**Issue by BreadBxsket** [Snownee/SnowRealMagic#186]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

3.2.2

### Modloader version

Forge

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

A small QoL change, if you right click with blaze powder on a slab, wall, fence, etc., it'll prevent snow from ever appearing on it. Similar functionality to using honeycomb to prevent copper from oxidizing.

**Comment by Snownee** [comment]
You can use light to prevent snowing. I don't it is a good idea
