### ISSUE TITLE
Snow constantly melts in all biomes with serene seasons installed in versions after 3.2.0

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Snownee/SnowRealMagic#187]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

3.2.2

### Modloader version

Forge 39.0.66

### Modpack info

N/A

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/NJL5390/858e8713910b159be14bb0c888f8d6cb

### Issue description

When testing out the latest version of this mod, I noticed that whenever I went to colder biomes such as snowy taigas or jagged peaks that despite snow generating in these biomes when the chunks are generated, the snow very quickly melts away despite being in a colder biome where snow should be maintained all the time.

After some testing I found that this bug only seems to occur when Serene Seasons is installed (https://www.curseforge.com/minecraft/mc-mods/serene-seasons). This has only started happening after I recently updated the mod and with some testing I found that in versions prior to 3.2.0 that this issue was not occuring. Therefore this issue seems to have arisen as a result of the recent snow accumulation rework that happened in version 3.2.0.

If the description isn't clear enough then I made a short clip demonstrating what is happening with this bug: https://youtu.be/76c_uWu964E

Thanks in advance.

P.S The serene seasons version used when testing was 6.0.0.10 and the Kiwi version was 5.2.5.

**Comment by superninjakiwi** [comment]
I get this issue too, snow always melts, even in the dead of winter, in biomes that should always be snowy.

**Comment by Ashtar084** [comment]
me too

**Comment by Flugel3** [comment]
Yeah I have the same issue, I tested it with Serene Seasons installed and uninstalled, same exact results. No Idea what the source of the bug is though..
