### ISSUE TITLE
ItemSnow cannot be cast to ItemBlockAccessor

### ISSUE THREAD

**Issue by ghost** [Snownee/SnowRealMagic#189]
### Mod loader

Forge

### Minecraft version

1.12.2

### Mod version

0.6.1

### Modloader version

Forge 14.23.5.2860

### Modpack info

RLCraft

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/hYAEsNB5

### Issue description

I should mention I'm also using Impact's 1.12.2 Forge Mod which does not display in the crash report.

`java.lang.ClassCastException: net.minecraft.item.ItemSnow cannot be cast to snownee.snow.mixin.ItemBlockAccessor`

**Comment by Snownee** [comment]
You checked the "Can you reproduce this issue with relevant mods only?" option. So you mean you have this crash even if there is only SnowRealMagic installed?

**Comment by ghost** [comment]
Yes.

I'm not sure if it's my installation directory or etc.

**Comment by Snownee** [comment]
Can you provide a latest.log with only SnowRealMagic installed?
