### ISSUE TITLE
Snow melts in cold biomes when snowMeltsInWarmBiomes is enabled

### ISSUE THREAD

**Issue by ghost** [Snownee/SnowRealMagic#190]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

3.2.5

### Modloader version

39.0.79 and 39.0.85

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Snow melts in all biomes including cold ones when config option `snowMeltsInWarmBiomes` is set to true. It's especially visible if you set gamerule `randomTickSpeed` to a high number.

**Comment by Snownee** [comment]
Do you have Serene Seasons?

**Comment by ghost** [comment]
nope

**Comment by ghost** [comment]
It happened with only this and Kiwi installed.

**Comment by Snownee** [comment]
Do you mean the level of the snow layer is decreasing? this is intentional behavior and the snow won't disappear completely. otherwise mob cannot spawning or pathfinding. if you don't want this you can set "snowNaturalMelt" to false in the config file
