### ISSUE TITLE
incompatible with untamed Wilds

### ISSUE THREAD

**Issue by TacocaTYT** [Snownee/SnowRealMagic#192]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

3.2.2

### Modloader version

39.0.79

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/1hjHj2ti

### Issue description

Game crashed, spat out following log.

**Comment by Snownee** [comment]
It looks like they've fixed the problem: https://github.com/RayTrace082/untamedwilds/issues/147
