### ISSUE TITLE
[Suggestion] allow snowballs to be stacked to 64 instead of 16

### ISSUE THREAD

**Issue by ffuentesm** [Snownee/SnowRealMagic#193]
### Mod loader

Forge

### Minecraft version

1.18

### Mod version

SnowRealMagic-1.18.1-forge-3.2.5.jar

### Modloader version

39.1.2

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

just minor quality of life change to allow snowballs to be stacked to 16 since when breaking snow it causes the inventory to be filled too fast.

**Comment by Snownee** [comment]
I think this feature is kinda irrelevant to this mod's theme
