### ISSUE TITLE
better azalea moss layers problems.

### ISSUE THREAD

**Issue by Jjesper0508** [Snownee/SnowRealMagic#194]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

3.2.2

### Modloader version

Fabric - 0.13.3

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

2 bugs: 

1. Moss carpets (better Azalia) disappear seemingly randomly but seem like they mostly do it if next to more moss layers or a block of some sort. tested them next to torches but that moss carpet lived for a long time so I don't think its melting

2. When moss layers(better Azalia) fall they turn into snow from snow real magic. (should break)

Apologies if these bugs are from the better Azalia side.

**Comment by Snownee** [comment]
not issue from our side. I think they should not inherit behaviors from snow block
