### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by lebanni** [Snownee/SnowRealMagic#195]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.0.0

### Modloader version

forge 40.0.19

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/lebanni/9df16871739c46bf4836a549289d6abe

### Issue description

Kiwi v6.0.1.
Running as a server. Crashes when client is connecting.

Crashlog : 
https://gist.github.com/lebanni/68e3cef0cc39c0395f3ed18cbf261e2c

**Comment by Snownee** [comment]
please update Kiwi
