### ISSUE TITLE
[1.18.2] Crash out of no where

### ISSUE THREAD

**Issue by BugmanBugman** [Snownee/SnowRealMagic#196]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

3.2.2

### Modloader version

Forge 1.18.2-40.0.19

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/BugmanBugman/4991ed4fce8ddb61c554f344eef00e04

### Issue description

Crash out of no where on server while exploring

**Comment by Snownee** [comment]
please update Kiwi
