### ISSUE TITLE
Crash as soon after rain became thunder (1.18.2-Forge)

### ISSUE THREAD

**Issue by zalfrost** [Snownee/SnowRealMagic#197]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.0.0

### Modloader version

Forge 40.0.25

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/QViugVKn

### Issue description

I was playing the game normally and suddenly I see snow and a few seconds later I heard thunder. After that, the game crashed. When I took a look at the Crash-Report that was generated by Minecraft, It says something about Rain and Thunder.

**Here is the Crash Report:** https://pastebin.com/n5xbsAis

**Comment by Snownee** [comment]
please update Kiwi

**Comment by zalfrost** [comment]
Thank you so much for your hard work. Really appreciated it. All the best for you (☞ﾟヮﾟ)☞

Everything works fine now. No more crashes.
