### ISSUE TITLE
Banner Snow

### ISSUE THREAD

**Issue by SafeOfArsenal** [Snownee/SnowRealMagic#199]
### Mod loader

Fabric

### Minecraft version

1.18.1

### Mod version

3.2.2

### Modloader version

Fabric Loader: 0.13.3, Fabric API: 0.46.4

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

Banner Snow

### Issue description

You are not able to place snow under banners
![g](https://user-images.githubusercontent.com/66153781/162123182-e98938be-260b-45b9-980e-3f160cb64272.png)

**Comment by Snownee** [comment]
Currently I have no plan to support this
