### ISSUE TITLE
Game crash when you put snow on foliage

### ISSUE THREAD

**Issue by jolopapina** [Snownee/SnowRealMagic#200]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.0.0

### Modloader version

Forge: 40.1.0

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/ZJSj423c

### Issue description

When you put snow on leaves, there is a chance the game will crash

**Comment by Snownee** [comment]
update Kiwi
