### ISSUE TITLE
Serene seasons support

### ISSUE THREAD

**Issue by jolopapina** [Snownee/SnowRealMagic#201]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.0.0

### Modloader version

Forge: 40.1.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Snow doesn't spawn when snowfall

**Comment by ateuchtmann** [comment]
Same issue here!

**Comment by Answordy** [comment]
Can confirm too.

It also seems to happen with modded cold, snowy biomes with no cerrelation to seasons, so the problem might have different roots, not seasons, but it's quite annoying for sure.

**Comment by jolopapina** [comment]
yes, i have installed biomes o plenty
