### ISSUE TITLE
Snow makes non-full blocks invisible when using Rubidium

### ISSUE THREAD

**Issue by DommyDCoder** [Snownee/SnowRealMagic#202]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.0.0

### Modloader version

40.1.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

When using this mod and rubidium together, snow makes blocks( the ones that change textures when snow is on top of it. Example: stairs and slabs) invisible. But the snow textures still show. So the original block texture disappears but the snow layer texture is still there. It also applies to grass and flowers, where you can "Snow log" it.
![2022-04-28_21 59 11](https://user-images.githubusercontent.com/102012077/165968573-3c0a73bd-b170-439c-88ca-fa3007a65ae6.png)

**Comment by ranenvious** [comment]
I am also having this bug, were you able to find a fix?

**Comment by qznfbnj** [comment]
> I am also having this bug, were you able to find a fix?

do you use latest version 4.1.0?
