### ISSUE TITLE
Fence Snow Not Melting

### ISSUE THREAD

**Issue by SpudlesEsq** [Snownee/SnowRealMagic#203]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

2.9.0

### Modloader version

Forge 36.2.33

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Snowed fences do not melt

**Comment by Snownee** [comment]
I think this issue has been fixed in higher Minecraft versions
