### ISSUE TITLE
launch crash mixin error when snowrealmagic is installed on my modpack

### ISSUE THREAD

**Issue by netcore10** [Snownee/SnowRealMagic#205]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

4.0.0

### Modloader version

fabric loader 14.6 api 0.53.4

### Modpack info

https://easyupload.io/i75l8f

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/Jen0JDWn

### Issue description

mixin, found it very hard to find what conflict is causing it, and i'm running out of ideas.

**Comment by Snownee** [comment]
it's servercore. please report to its devs, thank you. it can be patched with a very simple change in mixin config plugin

**Comment by netcore10** [comment]
Server core won't push an update to 1.18.2, is there any chance this can be patched on your end? Otherwise i think snow real magic is a no go in this case.
