### ISSUE TITLE
种在雪地上的2x2树苗不能长出大树

### ISSUE THREAD

**Issue by Dr-WeiAL** [Snownee/SnowRealMagic#206]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.1.0

### Modloader version

Forge 40.1.25

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

![image](https://user-images.githubusercontent.com/47446553/170692167-f280be34-9678-4b19-8927-e3258b2213a1.png)
![image](https://user-images.githubusercontent.com/47446553/170692193-0f6b4d20-3a0b-436e-b069-1021fcb3c758.png)

**Comment by Snownee** [comment]
it is too expensive to implement this, so I am not going to fix this problem
