### ISSUE TITLE
[4.0.0] NullPointerException causes game to crash

### ISSUE THREAD

**Issue by Chribit** [Snownee/SnowRealMagic#207]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

4.0.0

### Modloader version

Fabric: Loader 0.14.6 + API =.53.4

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Chribit/506cdc2bb4f7be3948414ab465d5e728

### Issue description

The game crashes whenever I explore a snowy taiga biome. The following error is displayed:

Cannot invoke "net.minecraft.class_1657.method_5998(net.minecraft.class_1268)" because the return value of "net.minecraft.class_1750.method_8036()" is null

The only line in the stacktrace related to a mod is:

snownee.snow.entity.FallingSnowEntity.method_5773(FallingSnowEntity.java:142)

Which is why i'm posting the issue here. I'm not sure what is causing the crash specifically and if it has anything to do with other mods i've got installed.

**Comment by Snownee** [comment]
https://www.curseforge.com/minecraft/mc-mods/snow-real-magic-fabric/files/3680621

![image](https://user-images.githubusercontent.com/16059084/170819590-2b9df6ca-63bb-4334-8509-28f13e307676.png)

It is incompatible with The Corners

**Comment by Chribit** [comment]
oh sh*t! I just recently downloaded that mod while using yours for ages... so sorry! Must have forgotten about the incompatibility!
