### ISSUE TITLE
Startup crash incompatibility with Capsules mod

### ISSUE THREAD

**Issue by MaxWasUnavailable** [Snownee/SnowRealMagic#208]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

SnowRealMagic-1.18.2-forge-4.1.0

### Modloader version

40.1.31

### Modpack info

Custom modpack. Can provide a download if necessary.

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/r1ZL62XB

### Issue description

The game crashes during startup if both Capsules & Snow: Real Magic are present in the modpack.

See line 93 in the provided crash log for what seems to be the cause.

```
Exception message: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:loot_pool_entry_type / snowrealmagic:normal])
```

**Comment by Snownee** [comment]
report to them. they should not access to block registry while mod is constructing
