### ISSUE TITLE
snow melts even in cold biomes

### ISSUE THREAD

**Issue by Jonas4505** [Snownee/SnowRealMagic#209]
### Mod loader

Forge

### Minecraft version

1.18.1

### Mod version

3.2.2

### Modloader version

39.1.2

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

All snow melts in cold biomes doesn't matter if it's night, day, or winter. I use serene seasons. For some reason, snow does set if the randomtickspeed is 0. If I up it all snow melts.

**Comment by Snownee** [comment]
Do you mean the level of the snow layer is decreasing? this is intentional behavior and the snow won't disappear completely. otherwise mob cannot spawning or pathfinding. if you don't want this you can set "snowNaturalMelt" to false in the config file
