### ISSUE TITLE
SRM Crash on Startup

### ISSUE THREAD

**Issue by RandomNarrator** [Snownee/SnowRealMagic#214]
### Mod loader

Forge

### Minecraft version

1.12.2

### Mod version

0.6.1

### Modloader version

1.12.2-forge1.12.2-14.23.5.2847

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/B9Ys8WBZ

**Comment by Snownee** [comment]
try install one of them:
https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility
https://www.curseforge.com/minecraft/mc-mods/mixinbootstraplegacy
