### ISSUE TITLE
All air blocks turned to fence gates

### ISSUE THREAD

**Issue by LmasterLong** [Snownee/SnowRealMagic#215]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.1.0

### Modloader version

Forge 40.1.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Upon removing this mod I followed the instructions in the config file that would remove all the custom blocks before uninstalling the mod. Later I found out somehow 90% of all the air blocks were replaced with fence gates. The blocks were invisible so there was no real damage and with work edit I was able to turn them back into air blocks. Crazy glitch, nothing like this has ever happened to me before.

**Comment by Snownee** [comment]
If the fence gates are invisible how do you see them?

**Comment by LmasterLong** [comment]
I was able to tell by using worldedit to to check all the blocks in a certain area

**Comment by Snownee** [comment]
What you said 20 days ago is first you found all the air blocks were replaced by fence gates, then you used WorldEdit to turn them back

**Comment by LmasterLong** [comment]
yes
