### ISSUE TITLE
Full Snow Block does not melt

### ISSUE THREAD

**Issue by TheButterbrotMan** [Snownee/SnowRealMagic#217]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

SnowRealMagic-1.18.2-fabric-4.1.2

### Modloader version

Fabric: Loader 0.14.8 + API 0.58.0+1.18.2

### Modpack info

https://www.curseforge.com/minecraft/modpacks/deathdusk (2.0.4)

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

![image](https://user-images.githubusercontent.com/64548098/183289142-58305ede-884e-4e1f-8862-7166bbb238fb.png)

**Comment by Snownee** [comment]
I think it is Fabric Seasons' bug
