### ISSUE TITLE
Wrong texture without Vanilla Resource Pack

### ISSUE THREAD

**Issue by UncleSam139** [Snownee/SnowRealMagic#22]
* Minecraft Version: 1.14.4
 * Mod Version: SnowRealMagic-1.14.4-1.4.1.jar
 * Resoure Pack: PureBDcraft 64x 1.14.4

Hi, I'm using a resource pack and if the snow layer is on top of the fence or the gate they have the vanilla texture. But without the snow layer, it's the modded texture.

Here some screenshots: 

![2019-10-22_01 01 26](https://user-images.githubusercontent.com/41263727/67250073-443bef00-f46a-11e9-8a68-fda98d851b34.png)
![2019-10-22_01 08 32](https://user-images.githubusercontent.com/41263727/67250076-4a31d000-f46a-11e9-9cad-e2d65a43e0de.png)

**Comment by Snownee** [comment]
It is not vanilla texture. It is an issue of UV, I cannot come up with a good solution...
