### ISSUE TITLE
Could there be a changelog for the mod updates? 

### ISSUE THREAD

**Issue by ffuentesm** [Snownee/SnowRealMagic#220]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

5.0.1

### Modloader version

43.1

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I tried to look on the Forge page and on github, but I could not find a changelog on the mod updates. 
That would be good to know what changed on each mod version.
![image](https://user-images.githubusercontent.com/44974827/188266703-862729e3-bc06-4330-baf8-c921254ac54f.png)

**Comment by Snownee** [comment]
Sorry, I am lazy and I don't like writing changelogs, especially if there are no new features for the update.

**Comment by Snownee** [comment]
Still, you can find something useful in the commit messages
