### ISSUE TITLE
[1.19.2 / FORGE] Crash with Snow Under Trees mod on world loading.

### ISSUE THREAD

**Issue by murao-kun** [Snownee/SnowRealMagic#221]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

5.0.2

### Modloader version

Forge 43.1.15

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/murao-kun/e0ac4cf19330290a646db8eea85f614c

**Comment by Snownee** [comment]
Please report to SnowUnderTrees
