### ISSUE TITLE
(1.19.2) Game crashes in Taiga Biome

### ISSUE THREAD

**Issue by izofar** [Snownee/SnowRealMagic#224]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

5.0.3

### Modloader version

Forge 43.1.25

### Modpack info

Better Minecraft 1.19.2

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/izofar/5672e82c65fc9915fb8869d6eed6d7b7

### Issue description

**NOTE:** Above Gist contains both crash.log and latest.log

Bug not reproducible using only relevant mods

**Comment by Snownee** [comment]
try removing ferritecore

**Comment by Snownee** [comment]
Moved discussion to #228
