### ISSUE TITLE
Set a Range of snowAccumulationMaxLayers 

### ISSUE THREAD

**Issue by ALainxD** [Snownee/SnowRealMagic#226]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

SnowRealMagic-1.18.2-forge-4.2.1.jar

### Modloader version

Forge 40.1.80

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

![2022-09-17_22 58 55](https://user-images.githubusercontent.com/69924381/190876239-692145f8-bb0b-4836-89e2-8c80c1944d1f.png)
A option to make the number of snow layers vary 

Instead of 
snowAccumulationMaxLayers = 8
snowAccumulationMaxLayers = 5-7

Maybe make it coordinates predefined so there won't be a huge additional calculation.

So the surface doesn't look so flat when it's all snowed up.

Also 
Snowlayers that are on grass or flower have a grey color once they reach layer 8

**Comment by Snownee** [comment]
Sorry, it does require a lot of extra codes. And I am not very interested in this idea
