### ISSUE TITLE
Snow melting rapidly even in cold biome when "snow melt in warm biome" option is true

### ISSUE THREAD

**Issue by RedBeast1959** [Snownee/SnowRealMagic#227]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

SnowRealMagic-1.19.2-forge-5.0.3.jar

### Modloader version

43.1.25

### Modpack info

Kiwi-1.19.1-forge-8.1.1.jar
rubidium-0.6.2
oculus-mc1.19.2-1.2.8
Quark-3.3-371

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

![2022-09-18_23 32 55](https://user-images.githubusercontent.com/100399264/190912578-005b47b8-eef0-409f-b870-51846b112112.png)

When snow melt in warm biome option is true, snow layer(not full snow block) rapidly melt to zero state even in cold biome. Above screenshot is taken from snowy plain biome. No, it's not about snow natural melt option which is intentional for mob spawning and pathfinding like #209 case, and I don't installed serene seasons like #217.

**Comment by Jusey1** [comment]
Can confirm, was having this issue and it was indeed the config option. I wanted the rapid melting of snow in warm biomes (assuming it isn't winter via a seasons mod) but it was happening everywhere no matter the biome, weather, or season. (I am on 1.18.2 Forge btw).

**Comment by jaidaken** [comment]
I am also having this problem but it is not because of the config option. Snow is disappearing completely, even when snowing.
