### ISSUE TITLE
Crash with custom Modpack

### ISSUE THREAD

**Issue by FLUXinstinct** [Snownee/SnowRealMagic#228]
### Mod loader

Forge

### Minecraft version

19.2

### Mod version

Snow Real Magic 5.0.3

### Modloader version

Forge 43.1.25

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

<script src="https://gist.github.com/FLUXinstinct/2fef6b3c67dcc46d03531ac40eccd6d6.js"></script>

### Issue description

Hello,
I get this crash when flying around in Minecraft with my Modpack and Snow is around.
I use the latest version of Kiwi and Snow Real Magic.

**Comment by Snownee** [comment]
please send your latest.log

**Comment by FLUXinstinct** [comment]
<script src="https://gist.github.com/FLUXinstinct/5f88aac8a9c034738b4a9a39a35513d8.js"></script>

**Comment by FLUXinstinct** [comment]
[latest.log](https://github.com/Snownee/SnowRealMagic/files/9618753/latest.log)

**Comment by Snownee** [comment]
and your crash report?

**Comment by FLUXinstinct** [comment]
[crash-2022-09-21_13.37.58-client.txt](https://github.com/Snownee/SnowRealMagic/files/9622630/crash-2022-09-21_13.37.58-client.txt)

**Comment by Snownee** [comment]
try removing ferritecore. please tell me if it still crashes or not

**Comment by FLUXinstinct** [comment]
nope keeps crashing. Crashlog: (think its the same though)
[crash-2022-09-22_17.17.04-client.txt](https://github.com/Snownee/SnowRealMagic/files/9627213/crash-2022-09-22_17.17.04-client.txt)

**Comment by Snownee** [comment]
@MehVahdJukaar hello, could you take a look at this issue? I hope here can be changed into `((BlockStateBase) (Object) this).getValue(DoublePlantBlock.HALF) == DoubleBlockHalf.UPPER`, to avoid assuming the block is actually in the world 😄 

https://github.com/MehVahdJukaar/Supplementaries/blob/master/common/src/main/java/net/mehvahdjukaar/supplementaries/mixins/BlockBehaviourPlanterMixin.java#L40

**Comment by Snownee** [comment]
fixed on their side
