### ISSUE TITLE
[Request] Torch never melts option

### ISSUE THREAD

**Issue by 0ctoqus** [Snownee/SnowRealMagic#229]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

5.0.3

### Modloader version

Latest

### Modpack info

No mod pack

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Hello,

First of all, let me say **thank you** for the great mod, it's really nice to play with it and keep the vanilla sensation while adding immersion to the environment.

I was wondering whether it would be possible to add an option so that **the torches do not melt the snow**.
I know we have an option to keep the snow from melting, but it doesn't work in my case.
I'm using the mod fabric seasons alongside it and I'm not able to enjoy the snow during the winter season and keep my torches from interfering with the ambiance. If I activate the never melt option, I'll always have snow, even during summer.

**Thanks a lot !**

**Comment by Snownee** [comment]
Unfortunately we can't know which block is the light source

**Comment by Andy608** [comment]
Sorry to necro an old thread, but does the light source of the block matter? Could the config setting allow snow to land everywhere regardless of light level?
