### ISSUE TITLE
[BUG] Incompatible w. Sodium

### ISSUE THREAD

**Issue by Shazuli** [Snownee/SnowRealMagic#230]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

5.0.3

### Modloader version

Fabric: Loader 0.14.9 + API 0.60.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Blocks that are "snow logged" stops rendering if Sodium is installed. This issue did not exist for Snow! Real Magic! in Fabric 1.18.2.
There was a similar bug happening in the Forge port of Snow! Real Magic! with Sodium's Forge port [Rubidium](https://www.curseforge.com/minecraft/mc-mods/rubidium).

**Comment by Snownee** [comment]
Have you installed Indium?

**Comment by Shazuli** [comment]
No.
Ok, installed it now. Looks like renders them now correctly, but I'm having some Z-fighting on two of the sides now however. Is this on Indium's side? Doesn't seem like it occurs with just Snow! Real Magic! installed.

**Comment by Snownee** [comment]
currently i don't know how to fix it. and this problem is irrelevant, so closing
