### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kasia1403** [Snownee/SnowRealMagic#231]
### Mod loader

Forge

### Minecraft version

1.12.2

### Mod version

0.6.1

### Modloader version

Forge 14.23.5.2860

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://paste.ee/p/2UBbN

**Comment by Snownee** [comment]
please provide a crash report with relevant mods only

**Comment by Kasia1403** [comment]
Eh, sorrym could You try to reproduce my issue ? Because my computer is so very much slow that I don't like testing a single mod.

**Comment by Snownee** [comment]
could you try removing foamfix and test again?

**Comment by Kasia1403** [comment]
I think that one option in Snow Real Magic caused this crash. I turned it off.

**Comment by Kasia1403** [comment]
Yes, it helped, I think.
