### ISSUE TITLE
1.7.10 or 1.12.2?

### ISSUE THREAD

**Issue by iamsoNewBee** [Snownee/SnowRealMagic#233]
### Mod loader

Forge

### Minecraft version

none

### Mod version

none

### Modloader version

forge

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

if  it`s possible XD

**Comment by Snownee** [comment]
https://www.curseforge.com/minecraft/mc-mods/snow-real-magic/files/3541266
