### ISSUE TITLE
Compatibility with Immersive Weathering Mod (Fabric 1.19.2)

### ISSUE THREAD

**Issue by ChristopherJ123** [Snownee/SnowRealMagic#234]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

5.0.4

### Modloader version

Fabric loader 1.14.9, Fabric-api-0.62.0-1.19.2

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Compatibility with Immersive Weather Mod (Fabric 1.19.2)
Link: https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-fabric

Issue:
Some stairs and stone walls are not snowable, this might be caused by custom #immersive_weathering tags (picture), other blocks without this custom tag works fine.
![snow](https://user-images.githubusercontent.com/86960084/193905712-ae828973-a752-4d88-8be2-8b3c0dc55c2d.png)

**Comment by murao-kun** [comment]
You should update that issue to support Forge too. Since both SRM and IW are existing on forge. Tasted and got same result.

**Comment by Snownee** [comment]
Addressed issue to https://github.com/AstralOrdana/Immersive-Weathering/issues/224
