### ISSUE TITLE
Crash on internal Server 1.19.2

### ISSUE THREAD

**Issue by FLUXinstinct** [Snownee/SnowRealMagic#237]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

Snow Real Magic 5.0.3

### Modloader version

Forge 43.1.43

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/FLUXinstinct/76923980b4c6e5b7d7d8afcfbe208b05

### Issue description

Hello i had this Crash with another 150 Mods installed so im not shure wich mod is causing this but i saw something about Snow Real Magic in the crashlog

**Comment by FLUXinstinct** [comment]
https://gist.github.com/FLUXinstinct/f406f04f9219b21605b99635e7c7572a

**Comment by lesleyxyz** [comment]
Getting exact the same error with Better MC. Stacktrace shows this is mod is causing it

**Comment by Snownee** [comment]
https://github.com/team-abnormals/savage-and-ravage/issues/119
