### ISSUE TITLE
[BUG] Double-grass blocks not changing texture w. Sodium installed

### ISSUE THREAD

**Issue by Shazuli** [Snownee/SnowRealMagic#238]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

5.0.4

### Modloader version

Fabric: Loader 0.14.9 + API 0.60.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

***Hi***

With Sodium (+ Indium) installed double grass blocks will not change the texture of the upper part of the blocks if snowlogged. Removing Sodium and Indium will change the upper block's texture to its snowy variant as it should.

![2022-09-26_15 47 44](https://user-images.githubusercontent.com/9884180/197340859-ec68cf43-220c-4989-870a-98a60fa7ffa7.png)

Snowlogging the upper portion will however change its texture with Sodium and Indium installed.
![2022-10-22_15 19 58](https://user-images.githubusercontent.com/9884180/197341291-fb7bb5b5-e245-4dc0-9c5e-a8af2cc61eef.png)

**Comment by Aceplante** [comment]
Does it do that without sodium?
