### ISSUE TITLE
Suggestion: snow variant of normal blocks

### ISSUE THREAD

**Issue by SepSol** [Snownee/SnowRealMagic#24]
* Minecraft Version: 1.14.4 (Forge 28.1.76)
 * Mod Version: SnowRealMagic-1.14.4-1.4.1

It would be great if we had snow variants of full-blocks as well. It is so inconsistent right now:

![2019-11-02_20 45 46](https://user-images.githubusercontent.com/47871887/68074593-04ea9800-fdb2-11e9-8317-bb028ccd8de4.png)

Also why are the edges of snow variant blocks so dark?!

**Comment by Snownee** [comment]
Adding this feature will have to rewrite the entire model loader, which I think is unnecessary.

Optifine will make texture dark if it is out of a normal block. I still have no idea about how to fix this.
