### ISSUE TITLE
Double plant gets the top half cut with snow layer

### ISSUE THREAD

**Issue by Krampus69** [Snownee/SnowRealMagic#240]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

SnowRealMagic-1.16.4-2.9.0

### Modloader version

36.2.34

### Modpack info

Unreleased yet

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.githubusercontent.com/Krampus69/3a6b11861f36994a9154b1eea8767613/raw/1a862214115e4a023f02019329cfb8ec8e0e0445/gistfile1.txt

### Issue description

Hello :wave:
I made a plant who is 2 blocks high and the top part doesn't spawn when it appears on a grass block covered in snow.
![2022-11-12_15 09 03](https://user-images.githubusercontent.com/81943963/201478589-5f99b905-bc46-4818-a1cf-e993ca97f86c.png)

It also appears when there is only the relevant mods installed. Here is an example : 

![2022-11-12_15 22 39](https://user-images.githubusercontent.com/81943963/201478639-18b208e6-c890-4f60-af54-aad0606ff6b4.png)

Mod installed : 
Kiwi-1.16.5-3.6.1
OptiFine_1.16.5_HD_U_G8
SnowRealMagic-1.16.4-2.9.0
Plant mod

Thank you for your help 🙏

**Comment by Snownee** [comment]
Sorry, this mod for Minecraft 1.16 is no longer maintained. And this issue is not likely caused by my side
