### ISSUE TITLE
Crash when loading with Optifabric

### ISSUE THREAD

**Issue by Rhyyn** [Snownee/SnowRealMagic#241]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

5.0.4

### Modloader version

0.14.10

### If bug:

- [] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Rhyyn/0a3358f0ae67313cafc2dce101b40e01

### Issue description

Game crash on loading with optifabric but works fine without it, are they not compatible ?

Crash report  : https://gist.github.com/Rhyyn/fa82f02471560b47cb76062757c8d669

**Comment by Snownee** [comment]
fixed i guess
