### ISSUE TITLE
Blocks become transparent when there is snow layer under them

### ISSUE THREAD

**Issue by Tander** [Snownee/SnowRealMagic#243]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

5.0.3

### Modloader version

Forge 43.1.65; Kiwi-1.19.1-forge-8.1.3

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/xrbyDeHv

### Issue description

Reproduced it on clean install with latest version Forge and mod. Tested with fence and grass, but most likely similar thing happens with other blocks that can be covered with snow.

![изображение](https://user-images.githubusercontent.com/1059805/205968128-80d15eac-859d-4c8e-98c6-c2307cfecb87.png)

**Comment by Tander** [comment]
Worked well on 1.18.2 (on the clean setup as well)
![изображение](https://user-images.githubusercontent.com/1059805/206493205-8b79f22f-220c-4645-a670-4ae99cb374c3.png)

**Comment by Tander** [comment]
Okay, I think I found the source.

Everything works with forge 43.1.57 but breaks in 43.1.58 and later (including 43.2.0). Here is what changed in this version:
43.1.58 Call baked model's \`getModelData\` before \`getRenderTypes\` (#9163)

Hope it will help to fix an issue.

(proofs, just in case)
![изображение](https://user-images.githubusercontent.com/1059805/206554104-93f23bba-dde5-4f5c-ace7-d17a304632db.png)
![изображение](https://user-images.githubusercontent.com/1059805/206554128-77277ee1-afea-4b1f-bcbb-3145f7bdc7fe.png)

**Comment by Snownee** [comment]
Thanks for the information!
