### ISSUE TITLE
Incompatible With Frosted Friends.

### ISSUE THREAD

**Issue by Jackwastakenx2** [Snownee/SnowRealMagic#244]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

5.1.0

### Modloader version

Forge 43.1.7

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

A (presumably from this mod, since it changes the snow layer block), feature, being able to right-click to get a snowball from snow, interferes with a feature in Frosted Friends, where you shift + right-click to create a pile of snow to make snowmen.

**Comment by ssolephant** [comment]
Check the .minecraft (or installed folder)\config\snowrealmagic-common.toml file
sneakSnowball=false
If set to , you can turn off the snowball creation feature of the "Snow! Real Magic!" mod

(I am not the creator of this mod, I simply came to check it out and wanted to give you some advice as I was able to quickly solve the problems in this post)

**Comment by Jackwastakenx2** [comment]
> Check the .minecraft (or installed folder)\config\snowrealmagic-common.toml file sneakSnowball=false If set to , you can turn off the snowball creation feature of the "Snow! Real Magic!" mod
> 
> (I am not the creator of this mod, I simply came to check it out and wanted to give you some advice as I was able to quickly solve the problems in this post)

Thanks!
