### ISSUE TITLE
Incompatible with Rubidium.

### ISSUE THREAD

**Issue by 12345-mcpython** [Snownee/SnowRealMagic#245]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.2.3

### Modloader version

Forge 40.1.86

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/12345-mcpython/1a51a7696b8925e1dbf166ad6b27bbd7

### Issue description

Client crashed When I entered the world.

**Comment by Snownee** [comment]
更新

**Comment by 12345-mcpython** [comment]
什么意思

**Comment by Snownee** [comment]
Rubidium
