### ISSUE TITLE
snowrealmagic:snow being count as entity?

### ISSUE THREAD

**Issue by emibanana** [Snownee/SnowRealMagic#246]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

SnowRealMagic-1.19.2-fabric-5.0.5.jar

### Modloader version

fabric 0.14.11

### Modpack info

https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric/files

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Just a weird thing that snowrealmagic:snow is being count as entity on a server and we have not changed any config for snow real magic mod.

I found this because i run a server performance profiler and it says snowrealmagic:snow is part of the entity count which means it affect server performance. could you look into the reason behind this?

profiler link: https://spark.lucko.me/mQf0u8pYWW

**Comment by Snownee** [comment]
I can't find the entity count part in your profiler link. anything I missed?

**Comment by emibanana** [comment]
> I can't find the entity count part in your profiler link. anything I missed?

here is another profiler summary (pretty much the same with the one above): https://spark.lucko.me/wghh5wf2J4

if you go to "world" tab it will show a summary of all entities in a server, also screenshot below:

![image](https://user-images.githubusercontent.com/120373920/208322499-3d749f72-a076-4eb8-aa99-e27341430e0b.png)

**Comment by Snownee** [comment]
The snow entity is the falling snow block, just like sand.
Have you tried to go to that area and see what is going on?

**Comment by emibanana** [comment]
ok i see.

I haven't checked the area, the reason i reported it is because the numbers seems not dropping even after the snow has fallen on the ground, but i will give update
