### ISSUE TITLE
[suggestion] Tweak to "place snow in block"

### ISSUE THREAD

**Issue by SebSemos** [Snownee/SnowRealMagic#248]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

5.0.5

### Modloader version

Fabric loader 0.14.12/ api0.69.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Hi. I think the place snow in block feature could be affected by the accumulation setting. If "accumulation" is off but "place" is on, you should not have the snow on stairs/slabs... when raining, but still possible to put it by right click

**Comment by Snownee** [comment]
I don't understand. Isn't that how it works now?

**Comment by SebSemos** [comment]
Nope, currently with config:
```
placeSnowInBlock = true
snowAccumulationDuringSnowstorm = false
snowAccumulationDuringSnowfall = false
```
Stairs and others still got snow appearing during bad weathers.

![2022-12-31_20 41 07](https://user-images.githubusercontent.com/89230340/210154247-a64f0808-843a-4206-9ffe-b55a55aaae7a.png)

**Comment by Snownee** [comment]
No, `snowAccumulationDuringSnowstorm = false` and `snowAccumulationDuringSnowfall = false` do not prevent snow from falling. They only prevent snow from becoming more than one layer

**Comment by SebSemos** [comment]
Yes, but an option to prevent this layer to appear when `placeSnowInBlock = true` would be great I think. So you still can make them snowy by hand
