### ISSUE TITLE
Snow accumulation on blocks doesn't occur unless a snow layer was already present or added by player

### ISSUE THREAD

**Issue by lazarusgreen** [Snownee/SnowRealMagic#249]
### Mod loader

Forge

### Minecraft version

1.12.2

### Mod version

0.6.2

### Modloader version

Forge 14.23.5.2860

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Exactly what the title says.
![image](https://user-images.githubusercontent.com/61564109/210117030-1004ddcc-8f7e-4475-804f-bb08aaa3b475.png)

In the above screenshot, multiple fences were placed and left in snow. Over a long period of time, snow layer buildup occured only on the single fence that was already in snow. This seems to occur regardless of whether or not any other mods are present.

**Comment by Aceplante** [comment]
Does this happen in 1.18.2? If so I hope this gets fixed

**Comment by lazarusgreen** [comment]
> Does this happen in 1.18.2? If so I hope this gets fixed

Unknown to me, I don't test newer versions. I can however add that uninstalling Weather 2 seems to make this issue disappear, but only randomly, so I am unsure if it's the main cause. It still tends to come back.

[Apologies for accidental closing and reopening, my finger slipped.]

**Comment by strubium** [comment]
I could definitely see Weather 2 causing issues like this, but if it's randomly coming back I don't know. 

Try making a new mod profile with only this mod and see if it still happens
