### ISSUE TITLE
 Suggestion: the same mod, but for carpets?! (1.14.4 - Forge)

### ISSUE THREAD

**Issue by SepSol** [Snownee/SnowRealMagic#25]
![image](https://user-images.githubusercontent.com/47871887/68074651-a1149f00-fdb2-11e9-9234-1db3698b4eed.png)

**Comment by Snownee** [comment]
Inspirations mod has this feature. If Inspirations has no plan to port to 1.14. I will write a new mod about this feature.

**Comment by SepSol** [comment]
Thank you so much! I'll ask them and will update you if I get anything in response.
