### ISSUE TITLE
XercaMod incompatibility

### ISSUE THREAD

**Issue by Patronelli** [Snownee/SnowRealMagic#250]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

2.1.1

### Modloader version

Forge 43.2.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Snow doesn't cover slabs and stairs of XercaMod and can't be placed on them.

https://www.curseforge.com/minecraft/mc-mods/xercamod

**Comment by Snownee** [comment]
Addressed issue to https://github.com/ercanserteli/xercamods/issues/74
