### ISSUE TITLE
destruction of half-blocks when changing the gamerule

### ISSUE THREAD

**Issue by Steve-the-Skunk** [Snownee/SnowRealMagic#251]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

5.1.0

### Modloader version

Forge: 43.2.3

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

destruction of half-blocks when changing the gamerule blizzardStrength to a value of 2, I did not check the others, but all possible half-blocks are destroyed, such as steps and the rest, which is why the roof built of such steps is damaged on the hard surface of any solid block, the remaining blocks hanging above the ground were not affected

**Comment by Steve-the-Skunk** [comment]
I also discovered that it destroys chests and torches

**Comment by Snownee** [comment]
Sorry for the inconvenience. New version here:
https://www.curseforge.com/minecraft/mc-mods/snow-real-magic/files/4312453

**Comment by Steve-the-Skunk** [comment]
The world does not want to be generated with the new version, it reaches about 55 – 60% and stops if I set the blizzardstrength parameter.
If I do not install it, the world loads, however, when I try to change the value through the command and call the weather, the game crashes.

**Comment by Snownee** [comment]
Could you provide a latest.log? I can't reproduce it

**Comment by Snownee** [comment]
I mean the crashed one

**Comment by Steve-the-Skunk** [comment]
[crash-2023-01-08_15.06.40-server.txt](https://github.com/Snownee/SnowRealMagic/files/10420942/crash-2023-01-08_15.06.40-server.txt)

**Comment by Snownee** [comment]
I think it has been fixed in the latest version
