### ISSUE TITLE
Create shingle stairs and slabs incompatibility

### ISSUE THREAD

**Issue by Patronelli** [Snownee/SnowRealMagic#252]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

6.1.0

### Modloader version

42.2.3

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Snow doesn't cover shingle slabs and stairs of Create mod and can't be placed on them.

**Comment by Snownee** [comment]
You can't cover it if it is not tagged with `minecraft:stairs` or `minecraft:slabs`
