### ISSUE TITLE
Incompatibility with Moonlight Lib

### ISSUE THREAD

**Issue by Typhonidite** [Snownee/SnowRealMagic#258]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

Any (6.2.2)

### Modloader version

Forge 43.2.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Typhonidite/d3caf6f17cc027f0f4739dafbe60132c

### Issue description

The mod is incompatible with Moonlight Library, even with the latest versions of both Snow! Real Magic! and Kiwi.

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue

**Comment by Typhonidite** [comment]
Huh? That's... I'm not sure I understand, then.
Can you tell anything obviously wrong within the logs? Or what could be causing the issue, exactly, if not an incompatibility between the two?

**Comment by Snownee** [comment]
Duplicate of #269
