### ISSUE TITLE
[1.14.4][Bug] Snow on slabs culls block faces

### ISSUE THREAD

**Issue by TheMisteryMan** [Snownee/SnowRealMagic#26]
* Minecraft Version: 1.14.4
 * Forge Version: 28.1.90
 * Mod Version: 1.4.1
Slabs seem to have some sort of culling going on on edges, both with & without Optifine
![2019-11-23_20 03 30](https://user-images.githubusercontent.com/47439660/69489474-37296b80-0e2d-11ea-9d01-f25184edad31.png)

Additionally, snowed on slabs seem to get a stretched side texture if using Optifine (but Optifine isn't exactly known for _not_ messing with rendering so...)
![2019-11-23_20 03 38](https://user-images.githubusercontent.com/47439660/69489475-37296b80-0e2d-11ea-9143-b684578274f9.png)

**Comment by Snownee** [comment]
Thanks for reporting
