### ISSUE TITLE
Mod crashes with optifine

### ISSUE THREAD

**Issue by realGretix** [Snownee/SnowRealMagic#262]
### Mod loader

Forge

### Minecraft version

1.19.3

### Mod version

7.2.0

### Modloader version

Forge 44.1.16

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/LbmTRUPC

### Issue description

Snow Real Magic crashes with optifine HD U I2 pre3

**Comment by Aceplante** [comment]
It crashes without it

**Comment by ahmettcavus** [comment]
same

**Comment by Snownee** [comment]
Sorry, we no longer support Optifine
