### ISSUE TITLE
Twigs Compat

### ISSUE THREAD

**Issue by Matthysse** [Snownee/SnowRealMagic#263]
### Mod loader

Forge

### Minecraft version

1.19.x

### Mod version

6.4.0

### Modloader version

Forge 43.2.4

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Hello!

Simple issue to suggest to add Twigs mod compatibility. In fact, it would be nice to have snow-logged twigs pebbles and sea shells, so that it doesn't create holes in the ground when they are on the terrain and it snows because of the season.

**Comment by Snownee** [comment]
Do you know you can add snow-logging ability yourself using tags? You can send your datapack to me so that it can be supported

**Comment by Matthysse** [comment]
Oh I didn't know! I created the files, I thought putting IDs in the "y_offset" file would make the rendered block go higher when snow cover them but it doesn't work, it just puts snow into the block just like the "containables" file so I don't know what else I have to do to make that work, but here are the files:

[data.zip](https://github.com/Snownee/SnowRealMagic/files/10724537/data.zip)

**Comment by Snownee** [comment]
thank you
