### ISSUE TITLE
Incompatability with the Roamers mod

### ISSUE THREAD

**Issue by marianyp** [Snownee/SnowRealMagic#267]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

6.3.0

### Modloader version

Forge 43.2.3

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://mclo.gs/MZLYFcP

### Issue description

The Roamers mod ([CurseForge](https://www.curseforge.com/minecraft/mc-mods/roamers) and [GitHub](https://github.com/KitKait2001/roamers)) adds player-like entities that mine blocks. I'm experiencing a crash when these entities attempt to mine snow layers.

From looking at the crash report, I'm assuming it's something related to the loot table of the custom snow that SnowRealMagic adds. 

To recreate this issue, install both Roamers and SnowRealMagic, go to a snowy biome and spawn a Roamer, and wait for it to attempt to mine snow or a block with a snow layer on top.

**Comment by Snownee** [comment]
This project has an invisible source and is inactive.
