### ISSUE TITLE
Allow snow layers to drop below water and melt with time - alternative to turning water into ice

### ISSUE THREAD

**Issue by T3sT3ro** [Snownee/SnowRealMagic#268]
### Mod loader

Forge

### Minecraft version

1.19

### Mod version

whatever

### Modloader version

fabric

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

It would be nice if there was another mode for snow layers falling into the water - instead of forming ice on touch, it could fall to the bottom and accumulate on the floor, but melt with time.

--- 

As a meta side note — you are missing the issue template for suggestions, or a setting that allows for creating issues that are not using issue templates.

**Comment by Snownee** [comment]
Thanks for the suggestion. We have no plans for this at this time.
