### ISSUE TITLE
Issue with optifine

### ISSUE THREAD

**Issue by ahmettcavus** [Snownee/SnowRealMagic#269]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

6.4.0

### Modloader version

Forge: 43.2.0

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/L5TKqstk

### Issue description

this mod is incompatible with optifine and crashes when tried to run them together. You can reproduce the issue yourself. Here is the link for crash: https://pastebin.com/rHKN6M19 latest.log file is on the other link.

**Comment by vinnyg0621** [comment]
same with me

**Comment by Aceplante** [comment]
It crashes even without optifine

**Comment by Cobyt3** [comment]
same here, buggy with rubidium + oculus and crashes with Optifine. Great.

**Comment by ahmettcavus** [comment]
@Wimblerrr what kind of bugs you face with rubidium + oculus?

**Comment by Cobyt3** [comment]
> @Wimblerrr what kind of bugs you face with rubidium + oculus?

This one for example. https://github.com/Snownee/SnowRealMagic/issues/278

There is another issue open regarding invisible blocks which also occure for me

**Comment by Cherrychip7** [comment]
same, crashes with optifine

**Comment by Snownee** [comment]
Sorry, we no longer support Optifine
