### ISSUE TITLE
transparents block without small hitblock can't receive snow

### ISSUE THREAD

**Issue by Ichirou-Tomoe** [Snownee/SnowRealMagic#27]
* Mod Version: 1.14.4-1.4.2

some blocks can't get a layer of snow at their feet. Either by hand, snow layer falling from above, or regular snowing. (And it kinda defeat the whole mod purpose of getting fully snowy landscape.)
1- transparents blocks, like vegetation, whose hitbox cover the whole block 
As you can see in the picture enclosed, this is true for vanilla and modded plants. 
![vanilla and BOP plant's response to snow](https://user-images.githubusercontent.com/24699543/69913460-68f78f00-1438-11ea-84c7-cc3449926030.png)

2- some solid block whose model leave ground space like modded fences or vertical slabs.
Now we wouldn't expect those blocks to receive a layer of snow on top of them like stairs and fences do. But snow at their feet would be fantastic. here is an example of a furniture fence.
![2019-12-01_12 37 48](https://user-images.githubusercontent.com/24699543/69913456-5d0bcd00-1438-11ea-99d3-e1397bf668b3.png)

Thank you for making this mod. It greatly improve the appeal of snowy biomes!

**Comment by Snownee** [comment]
That is because the blocks are not inherited from vanilla class. What mod are you using?

**Comment by Ichirou-Tomoe** [comment]
tall plants from vanilla don't have snow either : tall grass, peonies,  rose bush, lilacs. All have a hit box covering the whole block so I guess they may be implemented differently.
Plants from Biomes O'Plenty and XL Food Mod show the exact same behavior as vanilla plants: all small flowers (like the violet and glowflower in the picture), with small hit box, are perfectly snowed-in, while taller or even one block tall plants with box wide hit box can't be snowed-in.

The fence is from MrCrayfish's Furniture Mod.

**Comment by WenXin20** [comment]
Walls and fences from Engineer's Decor will also render incorrectly. Instead of using the 3D model from the mod, snow will change its shape completely to look like a normal wall.

**Comment by Snownee** [comment]
It is intended behavior. Special models will not be supported
