### ISSUE TITLE
Ice in Twilight Forest's Twilight Glacier biome melts constantly as of 6.4.0 when Serene Seasons is installed

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Snownee/SnowRealMagic#270]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

6.4.3

### Modloader version

43.2.6

### Modpack info

Kiwi Version: 8.2.1, Twilight Forest Version: 4.2.1518, Serene Seasons Version: 8.1.0.24

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/NJL5390/e413c4909b134cafecf633202bb66553

### Issue description

I have noticed that whenever I visited the Twilight Forest with the latest updates to Snow Real Magic then the ice found on the surface of the Twilight Glacier would just start melting for no reason, which eventually turns the glacier into a giant lake.
![2023-03-12_22 14 45](https://user-images.githubusercontent.com/64381954/224577795-338a60c4-9be5-4d03-9740-62a22f95934d.png)
If I uninstall Serene Seasons or if I go back to a version prior to 6.4.0/6.3.0 then this issue stops happening so this seems to be a conflict between newer versions of Snow Real Magic and Serene Seasons. 

Although I'm not sure how as Serene Seasons has a dimension whitelist to ensure that only the Overworld has seasons so the Twilight Forest shouldn't be affected at all by anything from Serene Seasons.

Please let me know if you need any more information about this issue or if I can be of any further assistance. 

Thanks for the incredibly immersive mod!

**Comment by Snownee** [comment]
I think you can try to add this biome to the Serene Seasons' biome_info config

**Comment by The-Bernician-Lamb** [comment]
Adding it to the biome blacklist did nothing unfortunately. The issue still occured regardless.
