### ISSUE TITLE
[Suggestion] Return of snow accumulation blacklist feature

### ISSUE THREAD

**Issue by FastBoye127** [Snownee/SnowRealMagic#271]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.1.0

### Modloader version

40.1.54

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Previous versions had the option to add a blacklist for snow accumulation in the config file, like so:

invalidSupportingBlocks = ["ice", "packed_ice", "barrier", "coarse_dirt"]

It would be great to have this feature again. Thank you!

**Comment by Snownee** [comment]
I remember this option was not removed until 1.19. after 1.19 you can use vanilla block tags to control this behavior
