### ISSUE TITLE
Game does not launch past Launcher

### ISSUE THREAD

**Issue by Herobattler** [Snownee/SnowRealMagic#273]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

SnowRealMagic-1.19.2-forge-6.4.4.jar

### Modloader version

Forge: 43.1.52

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Game does not launch past Launcher and therefore no log or crash log available.

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue

**Comment by Snownee** [comment]
Try updating Forge
