### ISSUE TITLE
Incompatibilities with Rubidium

### ISSUE THREAD

**Issue by Jusey1** [Snownee/SnowRealMagic#274]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

6.4.4

### Modloader version

Forge: 43.2.4

### Modpack info

Custom

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

N/A

### Issue description

I really love the mod but it breaks a bit with Rubidium by causing a lot of z-fighting with the snow layers on stairs, slabs, and full blocks while also causing snowed plants to become invisible, which can be used for cheating on servers for example:
![Untitled](https://user-images.githubusercontent.com/61861078/226998283-af79a29f-2c24-44ed-bf27-4dcb8000b04d.png)

The z-fighting and invisible blocks only happens when the mod is with Rubidium so I ain't sure if this is an issue on their end or not so I'll be posting this report on their end as well. Also to note that the z-fighting only happens on two sides of the blocks on average and doesn't happen at all on snowed fences and gates.

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue

**Comment by Jusey1** [comment]
https://user-images.githubusercontent.com/61861078/227259026-ea74519e-517f-4684-a6ab-8566cac92924.mp4

So, I figured out that you can get the bug happening with just any snow pile by right-clicking it until you get the bug... Which makes it even worst. Also, video proof with it happening only with the three mods installed and all. I really really hope this isn't a GPU specific bug with my AMD card because that would be annoying. Already had a bug specific to AMD GPUs before with Create, which is now fixed but still... I wouldn't want that kind of issue for you mateys to fix.

**Comment by Jusey1** [comment]
[Files.zip](https://github.com/Snownee/SnowRealMagic/files/11052906/Files.zip)

Oh, also, sharing my configs for Rubidium.

**Comment by Jusey1** [comment]
As for the weird z-fighting, that still happens too. Just harder to record. It also cause weird 'lines' on top of snowy slabs too if they're right next to each. (Sorry about all of these visual problems, this stuff has been bothering me for a while but I been silence about this for a very long time).

**Comment by Snownee** [comment]
still can't reproduce

**Comment by Jusey1** [comment]
Well, it's very obviously there. I provided visual evidence... So it has to be a bug that happens with specific hardware then is my only guess.

**Comment by Snownee** [comment]
Ok, I'll leave it here waiting for feedback from others.

**Comment by Cobyt3** [comment]
I have the same problem
![grafik](https://user-images.githubusercontent.com/108224706/229370568-7d738f1f-144f-46c0-a380-af35d1694dfb.png)

edit: altough it seems like only under grass plants. 
![grafik](https://user-images.githubusercontent.com/108224706/229370655-965099f5-38d9-4fd7-bc71-1cb826173ee4.png)
![grafik](https://user-images.githubusercontent.com/108224706/229370659-70463362-8e80-4bc2-b61f-74113d2ae34e.png)

**Comment by Jusey1** [comment]
It happening with grass is how I first found the bug myself. Wimblerr, do you by chance have an AMD GPU? As I said before, this could be a hardware related bug for all I know but if not, then I have no idea what is going on.

**Comment by Cobyt3** [comment]
> It happening with grass is how I first found the bug myself. Wimblerr, do you by chance have an AMD GPU? As I said before, this could be a hardware related bug for all I know but if not, then I have no idea what is going on.

Hi, no I'm using an Nvidia GTX 1660ti

**Comment by Jusey1** [comment]
Okay, damn. Interesting.

**Comment by Jusey1** [comment]
I decided to come back to this mod recently after removing Rubidium from my 1.20.1 modpack, and yeah. Almost all my issues was gone instantly, however there was z-fighting with snow on slab blocks. Figured out it was from the overlay model. The overlay model should have it's y size set to normal (0 / 16) instead of (-0.009 / 16.009 ) as it causes the overlay to stick out slightly above the snow on top of the slab, causing an unique form of z-fighting when multiple slabs are snowed right next to each. Luckily, that's an easy fix to do in a resource pack, so yeah.

Still no idea why everything else messes up so much with Rubidium though.

**Comment by Doming3000** [comment]
I've been experiencing this same problem since 1.16, I initially reported it on rubidium's github, and they told me "It's not my mod", I mean, he's right, but if your shit doesn't work I could finally look into it to see what happens and if it happens with other mods

**Comment by AntonyCilleros** [comment]
similar issue with embeddium on 1.20.1.
(there is also small grass in front of tall grass but they are invisible)
![image](https://github.com/Snownee/SnowRealMagic/assets/77164002/0c23d6e4-722a-43f5-bb7c-ca63f05b9f2e)

**Comment by Reshy** [comment]
![image](https://github.com/Snownee/SnowRealMagic/assets/2096384/5bfc6538-c870-437e-8e58-e17e65013a21)
Embeddium embeddium-0.2.16+mc1.20.1.jar

**Comment by chair-man-f** [comment]
i have this problem with embeddium and rubidium (1.16.5) 
<img width="1728" alt="Screenshot 2024-01-27 at 07 40 32" src="https://github.com/Snownee/SnowRealMagic/assets/117324349/b5bbbf8e-d012-42e0-a40d-4a8913037979">

**Comment by Snownee** [comment]
@Reshy @AntonyCilleros could you provide your mod lists?

**Comment by StarNavy25** [comment]
I had this issue as well on Embeddium Forge, but managed to get it to work by removing Lazurite (Indium). Don't know if this applies to everyone, but just thought I'd share

**Comment by Snownee** [comment]
older versions are no longer maintained
