### ISSUE TITLE
Not compatible with Serene Seasons

### ISSUE THREAD

**Issue by TocaDev** [Snownee/SnowRealMagic#276]
### Mod loader

Forge

### Minecraft version

1.19.3

### Mod version

SnowRealMagic-1.19.3-forge-7.3.0

### Modloader version

forge-1.19.3-44.1.23

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/raw/xVDGu20Y

### Issue description

The mod is not compattible with **Serene Seasons**.

**Comment by TocaDev** [comment]
How would I go about installing https://github.com/Snownee/SnowRealMagic/commit/c6b8d1a45c4c6225efe7cd2a153609fc44a0ab3e into the mod.

**Comment by Snownee** [comment]
https://www.curseforge.com/minecraft/mc-mods/snow-real-magic/files/4454830
