### ISSUE TITLE
Slabs can be broken at constant speed

### ISSUE THREAD

**Issue by Aceplante** [Snownee/SnowRealMagic#279]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

1.18.2

### Modloader version

1.18.2

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Regardless of whether you use your hand, pickaxe, or a shovel, slabs with snow on them can be broken quickly

**Comment by LessThanBenji** [comment]
+1 -- issue affecting v10.3.1 on 1.20.1, using Fabric 0.15.6
