### ISSUE TITLE
Snow melts in winter [Serene Seasons] [1.18.2]

### ISSUE THREAD

**Issue by GrandmaPork** [Snownee/SnowRealMagic#280]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.2.4

### Modloader version

Forge 40.2.1

### Modpack info

N/A

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

When snowMeltsInWarmBiomes = true, snow melts during winter
Didn't know if this was intentional or not so thought I'd post it here

**Comment by Snownee** [comment]
Fixed in 10.1.0

**Comment by Mystic-Ervo** [comment]
> Fixed in 10.1.0

But the lastest 1.18.2 version is the 4.2.4
