### ISSUE TITLE
Wierd things going on with snow layers near cryosol block from Immersive weathering

### ISSUE THREAD

**Issue by slovinsqui** [Snownee/SnowRealMagic#281]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

SnowRealMagic-1.19.2-fabric-5.1.0.jar

### Modloader version

fabric 0.14.19

### Modpack info

Custom modpack

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### Issue description

weird texture glitch occurs when there is snow layers accumulating in some cryosol blocks from immersive weathering https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-fabric

when placing more snow layers, the side of the cryosol became transparent
![2023-04-19_15 32 18](https://user-images.githubusercontent.com/96891858/233220142-f6c6878f-e1be-4bb4-bf8b-28ea94950128.png)

I can't really categorize what is going on but here is a screenshot of some texture clipping(?):
![2023-04-19_15 02 55](https://user-images.githubusercontent.com/96891858/233221107-9500a9f8-3448-4338-95d1-4981096e11ec.png)

and for some reason, I could place snow layers inside cryosol

there are some mods that i'm suspicious about:
immersive weathering (similar snow layer configuration + already having problems with cryosol)
Charm (also has snow layering config)
lambdaBettergrass

**Comment by Snownee** [comment]
Please make sure you can reproduce this issue with Immersive Weathering only

**Comment by slovinsqui** [comment]
ok, so i did that, and turns out snow layers go through cryosol blocks

![2023-04-20_13 35 05](https://user-images.githubusercontent.com/96891858/233481993-2a36ff6b-a7ca-4224-b9d7-432590aeabcc.png)

![2023-04-20_13 35 07](https://user-images.githubusercontent.com/96891858/233482002-dcd9795a-b8c3-481c-a52c-05ea69535c62.png)

it seems that this only happens when the cryosol is on top of a permafrost block, both from immersive weathering

![2023-04-20_13 36 55](https://user-images.githubusercontent.com/96891858/233482513-07ae27bc-240c-475e-87cd-413410677cb2.png)

Also, it crashed while testing out things
[latest.log](https://github.com/Snownee/SnowRealMagic/files/11290311/latest.log)

**Comment by slovinsqui** [comment]
![Screenshot 2023-04-20 134323](https://user-images.githubusercontent.com/96891858/233483445-1256cd2e-c599-45b0-9700-ea36a10254c6.png)

I dont know if its related to this error, but immersive weathering connects the cryosol texture with the permafrost texture when placed togheter
and the ones with the NON connected texture (blue circle) seems to be the one that has the snow layer clipped inside of it

**Comment by Snownee** [comment]
Okay. Thanks for the information. I have found the cause

**Comment by AstralOrdana** [comment]
lol wtf

**Comment by Dr-WeiAL** [comment]
![image](https://github.com/Snownee/SnowRealMagic/assets/47446553/f8682189-a02c-49cc-9cd7-a017966c9d78)
Indeed
1.19.2Forge still has the problem

**Comment by AlonsoCid** [comment]
It actually happends with any block introduced by Immersive Weathering and doesn't matter what block is underneath. I'm testing with only those two mods installed, I have submit an issue to the other mod author in case he can help.

**Comment by Snownee** [comment]
> It actually happends with any block introduced by Immersive Weathering and doesn't matter what block is underneath. I'm testing with only those two mods installed, I have submit an issue to the other mod author in case he can help.

I'm grateful for that

**Comment by Reshy** [comment]
This also happens with Leaf Piles.

![image](https://github.com/Snownee/SnowRealMagic/assets/2096384/dbcd41df-c3be-4394-a77f-2bc0e06e20bd)
