### ISSUE TITLE
Mod seems incompatible with Fabric Seasons Mod

### ISSUE THREAD

**Issue by Cape-City** [Snownee/SnowRealMagic#282]
### Mod loader

Fabric

### Minecraft version

1.19.3

### Mod version

SnowRealMagic-1.19.3-fabric-7.4.0.jar

### Modloader version

Fabric: Loader 0.14.19 - fabric-api-0.76.1+1.19.3.jar

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/Lj9xhgUN

### Issue description

To test the Fabric Seasons mod i jumped forward many time 30 days (/time add 30d).
If i do this for a couple of time and then start the rain (/weather rain) and jumped again 30d further,
the game crashed. If i do exakt the same without one of this mods (Seasons or Snow Magic), the game did not crash.
There seems an incompability with the Snow! Real Magic! and the Fabric Seasons Mod

Fabric API
modmuss50
fabric-api-0.76.1+1.19.3.jar

Fabric Seasons
D4rkness_King
fabric-seasons-2.0+1.19.3.jar

Fabric Seasons: Extras
D4rkness_King
fabric-seasons-extras-1.1-BETA+1.19.3.jar

Kiwi 🥝 (Fabric)
Snownee_
Kiwi-1.19.3-fabric-9.1.1.jar

Snow! Real Magic! ⛄ (Fabric)
Snownee_
SnowRealMagic-1.19.3-fabric-7.4.0.jar

[crash-2023-04-22_17.42.06-server.txt](https://github.com/Snownee/SnowRealMagic/files/11301710/crash-2023-04-22_17.42.06-server.txt)

**Comment by Squidney64** [comment]
I have the same issue. Turning it from winter into spring corrupts the world.

**Comment by Snownee** [comment]
Fixed in 1.19.2 and 1.19.4. 1.19.3 is no longer maintained

**Comment by Cape-City** [comment]
:( poor me

**Comment by Snownee** [comment]
> :( poor me

The simplest solution is to downgrade Fabric Seasons to 1.x

**Comment by Cape-City** [comment]
Isn't a solution, with the latest 1.x version of Fabric Season available on CF the 1.19.3 MC crashes during startup.

**Comment by Snownee** [comment]
Is there an option related to "replace meltable states"? You can turn it off

**Comment by Cape-City** [comment]
Nope, the Seasons mod hasn't much settings to change.
