### ISSUE TITLE
Incompatibilities with Fabric Seasons differently in pre-2.0 and in 2.0

### ISSUE THREAD

**Issue by sisby-folk** [Snownee/SnowRealMagic#285]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

5.1.1

### Modloader version

Quilt 0.18.10

### Modpack info

https://modrinth.com/modpack/tinkerers-quilt

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Just a simple oversight if I understand it correctly - the compatibility mode will replace block entities with their appropriate blocks via random tick, but without updating the grass below, it stays grey, as it would be with snow on top.

![image](https://user-images.githubusercontent.com/55819817/235954551-623f803a-0024-4f93-8e79-54bfffb85aa9.png)

**Comment by sisby-folk** [comment]
Okay yeah this is actually an incompatibility with fabric seasons before fabric seasons 2.0 - updating to seasons 2.0 fixes it.

That's not generally advisable due to [current incompat](https://github.com/lucaargolo/fabric-seasons/issues/108), so, might as well retitle this one.

**Comment by Snownee** [comment]
Is this problem solved? Totally forgot about it. Feel free to leave a comment if not.
