### ISSUE TITLE
Fences invisble in latest update

### ISSUE THREAD

**Issue by Aceplante** [Snownee/SnowRealMagic#287]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

SnowRealMagic-1.18.2-forge-4.2.4

### Modloader version

latest one?

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

![2023-05-05_11 11 25](https://user-images.githubusercontent.com/101857505/236497715-6a776bea-333b-4b32-95dc-82409152bb27.png)
![2023-05-05_11 09 35](https://user-images.githubusercontent.com/101857505/236497723-90b6cb39-2005-43c5-b02e-50abc69876aa.png)

**Comment by ghost** [comment]
having this exact issue as well. happens to slabs as well

**Comment by awnc** [comment]
see issue #335

**Comment by Reshy** [comment]
Really need which mods cause this issue to be listed, what ones are in your modpack?

**Comment by Aceplante** [comment]
I dont remember. It may have even been a texture pack issue

**Comment by Snownee** [comment]
older versions are no longer maintained
