### ISSUE TITLE
[Suggestion] Make world gen snow apply to the bottom block only

### ISSUE THREAD

**Issue by xJon** [Snownee/SnowRealMagic#289]
(MC `1.12.2`, Forge `14.23.5.2860`, SnowRealMagic `0.7.1`)

![image](https://github.com/Snownee/SnowRealMagic/assets/8945347/6aee1170-6e11-41e4-ad30-d49888ff4be1)

**Comment by Snownee** [comment]
They just should not make this block snow-loggable

**Comment by xJon** [comment]
I'm the pack author, and it would be very nice to have bushes snow-loggable, but I understand.
