### ISSUE TITLE
Slabs with transparency will no longer be transparent

### ISSUE THREAD

**Issue by WenXin20** [Snownee/SnowRealMagic#29]
* `Minecraft Version: v1.14.4`
 * `Mod Version: v1.4.3`
* `Styled Blocks v5.0b4`

Slabs that have transparency will lose that trait if snow is placed on top. In this case, the glass slab is from the [Styled Blocks](https://www.curseforge.com/minecraft/mc-mods/styled-blocks-mod) mod.
I also noticed that the breaking sound changes.

![2019-12-10_15 55 50](https://user-images.githubusercontent.com/12000593/70572716-f9834d00-1b65-11ea-850d-3ddf2ce275bb.png)

**Comment by WenXin20** [comment]
Was it intended to prevent snow placement on transparent slabs and stairs?

And slabs are now missing the side snow texture.

**Comment by Snownee** [comment]
yes
