### ISSUE TITLE
Snow under dynamic trees

### ISSUE THREAD

**Issue by GrandmaPork** [Snownee/SnowRealMagic#292]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.2.4

### Modloader version

Forge 40.2.9

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Could you add compatibility with dynamic trees? There is a small gap between the base of the tree and the snow if the tree is more or less than a block 
![2023-06-07_10 42 18](https://github.com/Snownee/SnowRealMagic/assets/109642282/42edd777-e6d7-4b12-ad90-d02aa705ec8a)

**Comment by GrandmaPork** [comment]
saplings too

**Comment by Snownee** [comment]
Thanks for the suggestion. We have no plans for this at this time.
