### ISSUE TITLE
Crash "exit code: -1"

### ISSUE THREAD

**Issue by matzar24** [Snownee/SnowRealMagic#293]
### Mod loader
Forge

### Minecraft version
1.19.2

### Mod version
6.5.0

### Modloader version
43.2.0 recomended 1.19.2

### Modpack info
170 mods

log file
[crash-2023-06-15_14.59.13-client.txt](https://github.com/Snownee/SnowRealMagic/files/11757757/crash-2023-06-15_14.59.13-client.txt)

### Issue description

Crash is happening during world loading.
What mods Snow Real Magic doesnt like?

**Comment by Snownee** [comment]
update Rubidium and Snow Real Magic

**Comment by matzar24** [comment]
Now it made it worse, game completely doesnt start up

I had this issue before recent update of SRM and Rubidium.

More specificly game crashes a few seconds after appear of "joining world" message, so world loading is completed 100%.
It doesnt apply only to my world, all worlds I would create All of them crashes moment before "joining world" is finished.

**Comment by matzar24** [comment]
You made my day, finally after month Snow Magic works.
After updating versions, there was another crash, but it was caused by mod Rubidium Extra, which doesnt have updated relese.
So recent update of S.R.M and Rubidium solved incompatibility beetwen them.
Snow acumulates? Confirmed. EVerything works fine.
