### ISSUE TITLE
Snow melting light level different than vanilla

### ISSUE THREAD

**Issue by Miszelka** [Snownee/SnowRealMagic#295]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.2.2

### Modloader version

forge-40.2.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Snow should melt at light level 12 or more in vanilla while it melts at 10.
Is this intended? If so can it be a variable in the config files?

**Comment by Snownee** [comment]
It is not intended. But 1.18.2 is no longer maintained. I just checked the code and if it works properly, the condition is still 12.

**Comment by Miszelka** [comment]
So are you saying my version should work correctly or the new versions or
all of them?

niedz., 18 cze 2023, 21:30 użytkownik Snownee ***@***.***>
napisał:

**Comment by Snownee** [comment]
Please make sure that you can reproduce the problem with relevant mods only first

**Comment by Miszelka** [comment]
Having only Snow Real Magic and kiwi loaded the light level descrepency is
still present on version 4.2.2, version 4.2.4 does not have this problem,
so i guess my question was outdated from the start

pon., 19 cze 2023, 20:17 użytkownik Snownee ***@***.***>
napisał:
