### ISSUE TITLE
Snow on grass and other blocks doesn't melt in spring summer or fall (with Serene Seasons)

### ISSUE THREAD

**Issue by LazrProductions** [Snownee/SnowRealMagic#296]
### Mod loader

Forge

### Minecraft version

1.20

### Mod version

9.0.0

### Modloader version

46.0.12

### Modpack info

https://www.curseforge.com/minecraft/modpacks/zyesmp

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Snow that is occupying the same block as grass, ferns, fences, etc... only melts during summer. all vanilla type snow layers melt while leaving Snow Real Magic type snow behind.

**Comment by mosharky** [comment]
same here

**Comment by Snownee** [comment]
are you guys on a dedicated server?

**Comment by mosharky** [comment]
Yup

**Comment by mosharky** [comment]
Was this not fixed in 9.0.1? Snow-logged grass still isn't melting
