### ISSUE TITLE
Dynamic/Dramatic Tree Integration

### ISSUE THREAD

**Issue by Desoroxxx** [Snownee/SnowRealMagic#299]
### Mod loader

Forge

### Minecraft version

1.12.2

### Mod version

0.7.1

### Modloader version

14.23.5.2860

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

It would be awesome if the trees, from Dynamic/Dramatic Trees would be compatible with Snow Real Magic.

[Dramatic Trees](https://www.curseforge.com/minecraft/mc-mods/dramatictrees)
[Dynamic Trees](https://www.curseforge.com/minecraft/mc-mods/dynamictrees)

![image](https://github.com/Snownee/SnowRealMagic/assets/82710983/80c72a57-0272-494c-ae49-e03e5a7ddcd6)
![image](https://github.com/Snownee/SnowRealMagic/assets/82710983/aa454d0c-130a-48ec-aae5-18cb0cf7a53c)

**Comment by Snownee** [comment]
Thanks for the suggestion. We have no plans for this at this time.
