### ISSUE TITLE
Double tall grass can't have snow in the same block space

### ISSUE THREAD

**Issue by WenXin20** [Snownee/SnowRealMagic#3]
Forge v14.23.5.2796
Snow, Real Magic v0.1.1

Double tall grass, double tall ferns, and modded plants can't have snow placed in the same block space.
Perhaps a whitelist to choose which blocks can have snow?

**Comment by Snownee** [comment]
It does have a whitelist. If a allow them, it will be like this:

![image](https://user-images.githubusercontent.com/16059084/50380121-4d1c3280-0698-11e9-8c34-e0f3058c8380.png)

**Comment by WenXin20** [comment]
Do modded plants work? -----------------------Sincerely, David NewvilleOn Dec 22, 2018 7:51 PM, Snownee <notifications@github.com> wrote:Closed #3.

**Comment by Snownee** [comment]
It depends on if the block inherits vanilla's class

**Comment by WenXin20** [comment]
Ok, makes sense, although the ones I have tried don't work. For example, from the plants2 mod.
