### ISSUE TITLE
Snow Covered Fences & Slabs can't be Waterlogged

### ISSUE THREAD

**Issue by WenXin20** [Snownee/SnowRealMagic#30]
* `Minecraft Version: v1.14.4`
 * `Mod Version: v1.4.3`

If snow-covered slabs or fences are placed underwater, it will not be waterlogged. Walls and stairs waterlogging works fine.

**Comment by Snownee** [comment]
Snow covered blocks should not be water-loggable

**Comment by WenXin20** [comment]
That makes sense. I found out the bug after pinking up a fence with snow on it and then placing it in water. It should probably clear the snow off it instead then.
