### ISSUE TITLE
SnowRealMagic-1.19.2-forge-6.4.4+ and Rubidium-0.6.2-0.6.3ish-2 backport: Crash upon joining world

### ISSUE THREAD

**Issue by sdarkwell** [Snownee/SnowRealMagic#300]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

6.4.4+

### Modloader version

43.2.0

### Modpack info

N/A

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/RsQ1MnMX

### Issue description

**Good evening!**

Minecraft crashes to the desktop shortly after attempting to join a world when both Snow! Real Magic! v6.4.4 or later and the Rubidium v0.6.2-0.6.3ish (Rubidium for Minecraft v1.19.2 backport of a couple of fixes otherwise only available in Rubidium for Minecraft v1.19.3+).

**The link to the Rubidium for Minecraft 1.19.2 backport is:**
[https://github.com/Dunkmania101/Rubidium-1.19.2-fix](https://github.com/Dunkmania101/Rubidium-1.19.2-fix)

The crash does not occur with Snow! Real Magic! v6.4.3, but does occur with all versions thereafter up to and including v4.5.1.

Error occurs whether starting a new world or joining an existing one.

Please let me know if there is any additional information I can provide. :)

**Thank you and be well!**
\- S.

**Comment by Snownee** [comment]
That's why I updated it to 6.4.4. Fixing it will make it incompatible with the official one

**Comment by sdarkwell** [comment]
**Hello @Snownee,**

Thank you for the response!

I was worried that might be the case. I'd much prefer to update to Minecraft v1.19.3 or v1.19.4 so I can use later versions of Rubidium, but too many mods in my modpack were never updated.

Thought I would at least submit an issue to confirm, and hopefully save some time for future seeker.

Thank you again for your time, and your fantastic mod. :)

**Be well!**
\- S.
