### ISSUE TITLE
All vegetation disappears when snow melts with fabric seasons

### ISSUE THREAD

**Issue by axd1x8a** [Snownee/SnowRealMagic#304]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

5.1.2

### Modloader version

Fabric API 0.76.0+1.19.2

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

When fabric seasons are installed and spring starts all vegetation disappears, but this did not happen when the snow melts with torches.
![image](https://github.com/lucaargolo/fabric-seasons/assets/26704473/ec671343-8698-4e2e-ba45-4121bac05afe)

https://github.com/Snownee/SnowRealMagic/assets/26704473/734f245d-85d7-404f-9681-5ec9812b36c4

fabric seasons issue: lucaargolo/fabric-seasons#141

**Comment by grantslone** [comment]
This is also occurring in 1.20.1

**Comment by Snownee** [comment]
Ideally they can disable the "replaced melted state" feature if SRM is present

**Comment by TatleCat** [comment]
So... Has this been fixed?

**Comment by SAPH3RE** [comment]
As of my 1.19.2 gameplay, no it has not.
It's been mentioned on their (Fabric Seasons) Github for almost a year now, and no comment/effort has been seen towards it.
