### ISSUE TITLE
Add the ability to snowlog defined blocks when generating the world.

### ISSUE THREAD

**Issue by jaimarl** [Snownee/SnowRealMagic#306]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

5.1.2

### Modloader version

Fabric Loader 0.14.22 + API 0.76.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

I would like to add the ability to force snowlog blocks when generating the world. For example, rocks from Early Stage mod should be covered with snow so that you can't see the grass underneath them.

**Comment by Snownee** [comment]
You can already do that using datapack
