### ISSUE TITLE
the snow accumulates, the non-full block texture turned into acacia wood 

### ISSUE THREAD

**Issue by SakiEroAice** [Snownee/SnowRealMagic#31]
* Minecraft Version: v1.14.4
 * Mod Version: v1.4.5

The snow accumulates non-full block, like slabs, stairs, fences and walls, their texture turn into acacia woods. This make me so frustrated. Is there any solution?
![1577376659805-1952308643](https://user-images.githubusercontent.com/59259596/71482418-6ae91e00-283d-11ea-8770-f6a9cbb12786.jpg)

**Comment by SakiEroAice** [comment]
i forgot to mention that, it's run with optifine, so i wonder if there are any compatibility between optifine and the mod

**Comment by Snownee** [comment]
Try updating Optifine or choosing another shader

**Comment by SakiEroAice** [comment]
thx! problem solved.
![Uploading 15773779535981757915956.jpg…]()
