### ISSUE TITLE
SnowBlockCoveredEntity causes lag when saving state/NBT during chunk unloading

### ISSUE THREAD

**Issue by MichailiK** [Snownee/SnowRealMagic#310]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

9.0.1

### Modloader version

Fabric Loader 0.14.22 + Fabric API 0.87.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

N/A

### Issue description

We have experienced major TPS lags while flying through the world with elytras. Investigating the issue with spark, we have noticed that the lag is caused by Minecraft unloading chunks & trying to save them. It turns out that, when *Snow! Real Magic!* is saving state/NBT data, it seems to call  `getBlockState`. Calling `getBlockState` on an unloaded chunk causes will load the chunk from disk. This is blocking the server thread, causing large MSPT spikes as chunks get unloaded when flying fast.

![image](https://github.com/Snownee/SnowRealMagic/assets/39029839/57e21aea-4026-4d6e-9f24-ab9dc75c8618)

![image](https://github.com/Snownee/SnowRealMagic/assets/39029839/71aa8213-2a68-44eb-966d-925ce52eeebf)

## Technical analysis

When chunks unload, Minecraft tries to save them to disk. SnowCoveredBlockEntity contains a call to `WatcherSnowVariant#updateOptions` when saving its state/NBT:

https://github.com/Snownee/SnowRealMagic/blob/e3e957877d3e926d913c5537c11b21b142e49729/src/main/java/snownee/snow/block/entity/SnowCoveredBlockEntity.java#L60-L61

`WatcherSnowVariant#updateOptions` is calling `BlockGetter#getBlockState` to check the block above:

https://github.com/Snownee/SnowRealMagic/blob/e3e957877d3e926d913c5537c11b21b142e49729/src/main/java/snownee/snow/block/WatcherSnowVariant.java#L17

As the `BlockGetter` cannot get the block state, since the chunk has been unloaded, it will load the chunk from disk again & need to block the server thread while doing so. This results in reduced TPS.

(Side note: the `Hooks#canSnowSurvive` call right below the previous snippet also contains a `getBlockState` call to check the block below)

https://github.com/Snownee/SnowRealMagic/blob/e3e957877d3e926d913c5537c11b21b142e49729/src/main/java/snownee/snow/Hooks.java#L118

<hr>

My 2 cents on how this could get fixed, even though I'm not familiar with the mod:

1. The data that's being saved in this case seems to only (?) relate to what properties the adjacent blocks have. Hypothetically, you would not need to store that data in the `SnowCoveredBlockEntity`'s NBT. Instead, you can retrieve the adjacent blocks when the chunk has been loaded.
2. If the above is incorrect, is there any chance to "cache" this data, so the mod doesn't need to load the chunk again when saving NBT?

cc @luigistyle

**Comment by the-tuxedo-cat** [comment]
somewhat similar issue causes the game to crash in single-player. when loading chunks,
> Calling getBlockState on an unloaded chunk

will cause the game to crash. also causes serious frame lag.

**Comment by Snownee** [comment]
thank you for the detailed analysis. hopefully fixed now. feel free to reopen it if the problem still occurs
