### ISSUE TITLE
Incompatibility with Regions Unexplored

### ISSUE THREAD

**Issue by KostromDan** [Snownee/SnowRealMagic#312]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

6.5.3

### Modloader version

43.2.23

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

![image](https://github.com/Snownee/SnowRealMagic/assets/90044015/c573a6f5-09cc-4cfd-af61-de6c5ff08e6a)
![image](https://github.com/Snownee/SnowRealMagic/assets/90044015/7be1bf79-fa88-44e1-be79-4a550a8c37bd)

**Comment by mosharky** [comment]
you just had to put that block in this mod's block tag

**Comment by KostromDan** [comment]
> you just had to put that block in this mod's block tag
What tag? I can't find any tag from snowrealmagic in vanilla grass for example.

**Comment by KostromDan** [comment]
```js
ServerEvents.tags('block', event => {
    event.add("snowrealmagic:containables", 'regions_unexplored:medium_grass')
})
```

**Comment by mosharky** [comment]
yep, exactly

**Comment by SettingDust** [comment]
You can resolve it with a PR target https://github.com/Snownee/SnowRealMagic/blob/1.20-fabric/src/main/resources/data/snowrealmagic/tags/blocks/containables.json
