### ISSUE TITLE
Crash on world load with Rubidium & Oculus

### ISSUE THREAD

**Issue by 3lkram** [Snownee/SnowRealMagic#315]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

6.5.3

### Modloader version

Forge 43.3.0

### If bug:

- [x] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/BAsXKGjR

### Issue description

Whenever loading a world with SnowRealMagic-1.19.2-forge-6.5.3.jar, Kiwi-1.19.1-forge-8.3.4.jar, oculus-mc1.19.2-1.6.9.jar, and rubidium-mc1.19.2-0.6.2c.jar, the game will load the chunks then save the world and crash the game and not let the player see the world.

This issue is not present if SnowRealMagic-1.19.2-forge-6.5.3.jar is removed

**Comment by VOLKOUL** [comment]
Bro, I had to check 300 mods to find the cause bruh...
