### ISSUE TITLE
Supplementaries rope fence issues

### ISSUE THREAD

**Issue by Ladocterus** [Snownee/SnowRealMagic#316]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

9.0.1

### Modloader version

Forge 47.2.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

The fences with rope tied around it bug out when it becomes the snow covered fence; the rope remains while the fence disappears and creates floating snow and rope.

Supplementaries 2.6.4

**Comment by peow** [comment]
im using fabric 1.20.1 and this issue happened to me too
![image](https://github.com/Snownee/SnowRealMagic/assets/105888751/88b2e4ee-54dd-422c-bbb5-422528cd74e7)

**Comment by Snownee** [comment]
I think you should report to Supplementaries devs to not convert blocks that have block entity
