### ISSUE TITLE
[Bug] Incompatibility with ModernFix Dynamic Resources on Fabric, and More than Likely Forge Too

### ISSUE THREAD

**Issue by GamingWithDudeAlt** [Snownee/SnowRealMagic#321]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

9.0.1 (This Mod) 5.8.1 (ModernFix)

### Modloader version

Fabric Loader: 0.14.22, Fabric API: 0.90.0

### Modpack info

Custom Made Modpack

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://mclo.gs/bXKL1GF

### Issue description

This is just copy and pasted from the Discord server so it may not make much sense here:

Anytime you place snow under a fence or wall, including modded variants, underneath the fence/wall the world will be completely transparent like in the screenshot I've attached. I'm assuming this mod uses baked models for that as dynamic trees had this same issue in chunks that had dynamic trees before it was fixed, and it was because the mod used baked models for them. Dynamic resources doesn't like baked models as you can tell. I would like to enabled dynamic resources in the modernfix config because it heavily reduces ram usage.

**Comment by SpiritOTHawk** [comment]
i have the same problem

**Comment by Reshy** [comment]
![2023-11-23_15 32 53](https://github.com/Snownee/SnowRealMagic/assets/2096384/51f6dacb-f60a-420b-b571-8618d234a4b0)
Can Confirm.

**Comment by SettingDust** [comment]
@embeddedt is there some hint for this?

**Comment by embeddedt** [comment]
This is most likely caused by the mod using model bakery mixins ([source](https://github.com/Snownee/SnowRealMagic/tree/1.20-fabric/src/main/java/snownee/snow/mixin)). For proper compatibility with dynamic resources, mods should stick to the platform-provided APIs (Model Loading API on Fabric, `ModelEvent.ModifyBakingResult` on Forge).
