### ISSUE TITLE
unknown crash, error found with snownee/jade.Jade

### ISSUE THREAD

**Issue by HentaiHamster** [Snownee/SnowRealMagic#322]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

9.0.2

### Modloader version

47.1.3

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/6Wrxjama

### Issue description

game crashed and gave this error log attached.

reading through the crash it looks like some sort of error with this mod, if not then sorry.

**Comment by HentaiHamster** [comment]
i removed the snow mod and my game loads without crash. with your mod enabled it crashes and gives same error upon loading the world i crashed on, idk

**Comment by Snownee** [comment]
please use this instead and send the crash report again: 
[libs.zip](https://github.com/Snownee/SnowRealMagic/files/13162223/libs.zip)
