### ISSUE TITLE
[Suggestion] 1.20.2 Support

### ISSUE THREAD

**Issue by nco2k** [Snownee/SnowRealMagic#323]
### Mod loader

Fabric

### Minecraft version

1.20.2

### Mod version

9.0.4

### Modloader version

Fabric: Loader 0.14.24 + API 0.90.7

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

would be nice if you could add 1.20.2 support :)

**Comment by Snownee** [comment]
Thanks for the suggestion. We have no plans for this at this time.
