### ISSUE TITLE
Mobs spawn on blocks they should'nt

### ISSUE THREAD

**Issue by SebSemos** [Snownee/SnowRealMagic#324]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

9.0.4

### Modloader version

fabric-api-0.90.4+1.20.1

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Blocks like leaves where mobs don't spawn in vanilla became spawnable if a single snow layer is on them. 2 layers will block the spawn as expected on another block.
(Haven't tested on all the non spawnable blocks, but tested without any other mods)

Using minihud to see light level:
Vanilla:
![huge_2023-11-17_03 47 21](https://github.com/Snownee/SnowRealMagic/assets/89230340/e7d19bb8-849a-480f-bc50-270de56f7f32)
With SRM
![huge_2023-11-17_03 43 51](https://github.com/Snownee/SnowRealMagic/assets/89230340/581da9b7-9eb8-459e-845e-69de1a2644a5)

PS you owe me a dozen of villagers 😂

**Comment by SettingDust** [comment]
Try to add the block to https://github.com/misode/mcmeta/blob/data-json/data/minecraft/tags/blocks/prevent_mob_spawning_inside.json with datapack

**Comment by Snownee** [comment]
I don't get your description. What is the expected behavior?

**Comment by SebSemos** [comment]
Mobs shouldn't spawn on transparent blocks when a snow layer is present

**Comment by ghost** [comment]
same, mob spawns on trees around my house
