### ISSUE TITLE
[CTD] | Snow! Real Magic! & Enhanced Weather

### ISSUE THREAD

**Issue by SylisMC** [Snownee/SnowRealMagic#327]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

9.0.4

### Modloader version

0.86.1+1.20.1

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/Ejgd9Gwu

### Issue description

Game crashes on boot. before main menu

Cloth Config API 11.1.106+fabric
Enhanced Weather 1.0-Beta5.4
Fabric API 0.86.1+1.20.1
Kiwi 🥝11.1.1
Snow! Real Magic! ⛄9.0.4

**Comment by Snownee** [comment]
nothing we can do from our side. they should use a more specific injection point
