### ISSUE TITLE
"Snowlogged grass" turns into "snowlogged tall grass" when sprinting near it.

### ISSUE THREAD

**Issue by DevilPlayz667** [Snownee/SnowRealMagic#328]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

6.5.4

### Modloader version

43.2.10

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

*Whenever I'm sprinting in a snowy biome "Snowlogged grass" turns into "snowlogged tall grass" when sprinting near it.
*I don't know which mods are causing this glich, or if the results are reproducible.
*the modpack was made by me, so I can't give a link to it.
*I don't have any ideas or suggestions as to how to fix this glich.
*sorry for not having much information. I have a lot of mods, so it's hard to figure out which mods are causing this glich.

**Comment by Snownee** [comment]
Hello, I can't reproduce this issue
