### ISSUE TITLE
Stairs and slabs not snow logged

### ISSUE THREAD

**Issue by KDFireHero** [Snownee/SnowRealMagic#329]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

9.0.4

### Modloader version

Fabric Loader 0.14.24  API 0.91.7+1.20.1

### Modpack info

Spelunkery, Wunderreich, Bakery, Naturalist. Meadow, Better Archeology

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Snow does not appear on the stairs and slabs from the mods: Spelunkery, Wunderreich, Let's do: Bakery, Naturalist. Let's do: Meadow

snow does not appear on stairs from: Better Archeology

**Comment by KDFireHero** [comment]
I apologize but I have no clue how to apply this fix could you help?

**Comment by Snownee** [comment]
update should fix
