### ISSUE TITLE
Glitchy Snow Layer Render

### ISSUE THREAD

**Issue by WenXin20** [Snownee/SnowRealMagic#33]
* Minecraft v1.14.4
 * Snow Real Magic v1.4.5

If Optifine's Better Snow Option is turned to on, and there is a grass with snow on it next to a solid block, the snow layer will look glitchy. The snow will be flashing from darker to light as the player moves around.

![2019-12-26_20 50 54](https://user-images.githubusercontent.com/12000593/71498344-9e1db400-2821-11ea-88d4-17857deb91bf.png)

**Comment by Snownee** [comment]
Sorry, I do not provide compatibility support to Optifine
