### ISSUE TITLE
Issues and enhancement propositions with snow layers

### ISSUE THREAD

**Issue by kerryghan-relot** [Snownee/SnowRealMagic#330]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

9.0.2

### Modloader version

Forge: 47.2.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/Wq9DEYHD

### Issue description

Hello, I really appreciate your mod, However while using it I encountered a few issues and had a few enhancement ideas, so I'm posting it here. I hope this will help. Have a good day.

### **Enhancement propositions :** 

- [ ] Possibility to shovel the snow on stairs/slabs. We can shovel the snow on other full block, but not stairs/slabs. Even tough we can right-click it to get it back, it would feel more natural to make it work like other blocks.
- [ ] Toggle overflowing snow on stairs. When right-clicking with empty hand on slabs or full block we can kinda toggle overflowing snow (ie. make snow appear on the sides of the block). Maybe add the same functionnality with stairs.
- [ ] Add snow layer on other types of blocks such as : glass panes (including McCaw's diagonal ones), pots, rails, etc...
- [ ] Possibility to add more than one layer of snow on fences

### **Issues found :** 

- [ ] Incompatibility with **McCaw's mods**, especially "_Diagonal Fences_" and "_Diagonal Windows_": When putting snow layer on diagonally connected fences, they disconnect. Same when putting snow layers (2+) around diagonally connected glass panes.
- [ ] Incompatibility with **bl4ckscor3's mod** named "_Sit_". We can sit on snowy stairs and slabs with no problem, but not on cornered snowy stair. (however, I'm not sure if I should report this or on their side, so I'll do both just in case).

_Screenshot showing the described issues:_
![image](https://github.com/Snownee/SnowRealMagic/assets/122842444/4963d7e1-4d1f-4f2d-9260-ef75fecb06ad)

**Comment by Snownee** [comment]
![image](https://github.com/Snownee/SnowRealMagic/assets/16059084/652a15d7-c0a1-4e12-8ac9-28dbf6b49d69)
![image](https://github.com/Snownee/SnowRealMagic/assets/16059084/e81f23a0-19bf-490e-90a1-e40eb06bbbf1)
![image](https://github.com/Snownee/SnowRealMagic/assets/16059084/763da9f2-9b7f-4cfb-ba99-183af346a970)
🤔

**Comment by kerryghan-relot** [comment]
It appears that you're right, I do can sit on cornered stairs (both snowy and not). After further tests, I edit a few things I said above:

- **Regarding the compatibility with the mod "sit":** it appears that I do can sit on stairs (wether cornered or not, snowy or not) but not on snowy slabs.
- **Regarding the shoveling of snow layers:** I can indeed right click to get the snow back (with a shovel or not, and in both creative or survival). But I can not shovel it with a left click (the 'destroy' button by default) like I can do when the snow is on other full blocks or on the ground.

The following short video shows both of these. Hope this will help.


https://github.com/Snownee/SnowRealMagic/assets/122842444/6cc2128a-2309-49e7-ab71-4afc4e566593
