### ISSUE TITLE
1.16 forge serene seasons snow doesn't fall on stairs or slabs and melts when I manually place snow down

### ISSUE THREAD

**Issue by Jacksong256** [Snownee/SnowRealMagic#331]
### Mod loader

Forge

### Minecraft version

1.16.5

### Mod version

2.9.0

### Modloader version

Forge-36.2.39

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Whenever it is winter it snows because I have serene seasons installed but it still doesn't snow on slabs and stairs despite having snow real magic installed. Even when I place snow down manually on these blocks they just melt even away from a source of heat or light.

**Comment by Snownee** [comment]
Sorry, I no longer maintain Forge 1.16

**Comment by Jacksong256** [comment]
> Sorry, I no longer maintain Forge 1.16

What versions do you support?

**Comment by Snownee** [comment]
For versions below 1.20, I'll only fix severe problems

**Comment by Jacksong256** [comment]
> For versions below 1.20, I'll only fix severe problems

Ok thanks for telling me
