### ISSUE TITLE
When removing the mod, all certain blocks covered with snow simply disappear from the world and cannot be restored

### ISSUE THREAD

**Issue by ovchvi** [Snownee/SnowRealMagic#334]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

9.1.2

### Modloader version

Forge 47.0.35

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

When removing the mod, all blocks covered with snow (steps, fences, gates) simply disappear from the world and cannot be restored. I think this is because the mod replaces blocks with its own models to display snow. I also attach screenshots before and after removing the mod.
![2023-12-13_23 28 42](https://github.com/Snownee/SnowRealMagic/assets/95563718/132d71c7-aea6-46fe-a857-d078e0b20dff)
![2023-12-13_23 29 29](https://github.com/Snownee/SnowRealMagic/assets/95563718/56fd1215-2e41-40ee-ae72-b1e8f93e146c)
I don't think this is a bug, since this is what should happen when deleting the necessary models, but the moment is definitely unpleasant. I really want to save the blocks somehow when deleting the mod. Is there any way to save all such blocks when deleting a mod?

**Comment by Snownee** [comment]
Yeah, sure. Please check the configuration and set "Retain Original Blocks" to true before removing the mod, and then enter the world and speed up the random ticking

**Comment by ovchvi** [comment]
Oh, thank you so much! It's a pity that Forge doesn't have a magic «delete» button to automate this process :) Thanks again!!
