### ISSUE TITLE
[1.20.1] Snow layered on non-solid blocks turn invisible.

### ISSUE THREAD

**Issue by Reshy** [Snownee/SnowRealMagic#335]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

SnowRealMagic-1.20.1-forge-9.1.2.jar

### Modloader version

47.2.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

![2023-12-13_04 58 34](https://github.com/Snownee/SnowRealMagic/assets/2096384/80515ee6-5d8a-4117-8c01-3fa28e664228)

**Comment by Snownee** [comment]
do you have ModernFix?

**Comment by SaltSouls** [comment]
> do you have ModernFix?

I do, is there a solution to this?

**Comment by mimi-min** [comment]
Are you also using Sinytra Connector with Continuity by chance?

After some extensive testing in the Discord server, I found this to be the likely culprit (Continuity on Forge),

**Comment by SaltSouls** [comment]
I am indeed.

**Comment by mimi-min** [comment]
Try the new update Snownee published on CurseForge, it says it's in beta and will try to revert if you click "update" but it fixes the issue with Continuity at least (there's a slight bug where ice under snowed blocks doesn't render for a moment, but it fixes itself after a few seconds). 

Unfortunately there is some other mod in my pack that is still causing an issue, I will post an update here if I find it, but for now try the beta version of Snow.

**Comment by Snownee** [comment]
Closed due to no feedback
