### ISSUE TITLE
[Bug] snow destroys cherry leaves

### ISSUE THREAD

**Issue by MimzyFang** [Snownee/SnowRealMagic#339]
### Mod loader

Quilt

### Minecraft version

1.20.1

### Mod version

9.1.2

### Modloader version

Quilt Loader 0.22.1-beta.4 qfapi 7.4.0+0.90.0-1.20.1

### Modpack info

private modpack https://gitlab.com/Fauli1221/unicmodpack4meme5/

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

not tested

### Issue description

the leaves fill with snow and once there full the snow diapers
![2023-12-21_18 52 17](https://github.com/Snownee/SnowRealMagic/assets/43648117/a1060e76-4d41-4062-9fd5-b27c350fadb2)

I will test this independent from the modpack later once I have more time

**Comment by Snownee** [comment]
fixed in dev now. for Fabric it will be a few more days

**Comment by Snownee** [comment]
but you can modify the block tag by yourself before that
