### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by Pyxial** [Snownee/SnowRealMagic#341]
### Mod loader

Quilt

### Minecraft version

1.19.2

### Mod version

5.1.2

### Modloader version

0.23.0-beta.1

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://mclo.gs/AZHo0kF

### Issue description

Technically the mod is only supported on fabric not quilt in this version, but it was fine for a while so idk.

I mined a snow covered spruce fence, walked for around 3 seconds, and game crashed (crashed so hard NEC couldn't save it, took like 5 seconds to go from black screen to dead). I checked logs and using my very very little knowledge, found something about waterlogging :/

**Comment by Pyxial** [comment]
P.S. I have no clue why simple voice chat is having an stroke

**Comment by Snownee** [comment]
please report to EssentialGUI
