### ISSUE TITLE
Snow generates inside houses with mutiple layers, problem and possible incompability with Choice Theorem's Overhauled village

### ISSUE THREAD

**Issue by TheKatzenlord** [Snownee/SnowRealMagic#345]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

v10.2.3

### Modloader version

Fabric API 0.91.0+1.20.1

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/TheKatzenlord/3d67788aa0ac08b2bb745345b3102401

### Issue description

Snow Spawns inside villager houses and other structures, located in snowy biomes. All structures are mod structures, which is possibly the problem. Tried multiple changes in the config, really would appreciate a solution or compat addon.
![2024-01-07_18 20 55](https://github.com/Snownee/SnowRealMagic/assets/155781723/81fb7863-8eb1-42e4-b046-a0abdbfd7fe6)

**Comment by Snownee** [comment]
My mod does not generate snow with multiple layers

**Comment by TheKatzenlord** [comment]
Okay, thanks, I’m trying to solve the issue otherwise, have a nice day 👍
