### ISSUE TITLE
Not compatible with the Panda'sExtraDetails mod

### ISSUE THREAD

**Issue by TatleCat** [Snownee/SnowRealMagic#346]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

10.2.3

### Modloader version

0.15.3 + 0.91.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

The bottom material of the trapdoor is transparent,
Hopefully the two awesome mods will be compatible.
Because this mod plus animations and seasonal changes are quite perfect🙏

**Comment by Snownee** [comment]
what are you talking about?

**Comment by TatleCat** [comment]
> what are you talking about?

uhm... Sorry(＞＜), I'm a native Chinese speaker, I mean this mod along with the door animation will make the trapdoor resource pack transparent

**Comment by Snownee** [comment]
video please

**Comment by TatleCat** [comment]
> 请视频


Uploading 24-01-11 14-57_x264.mp4…

**Comment by TatleCat** [comment]
> video please

https://github.com/Snownee/SnowRealMagic/assets/128877938/98bc4b0f-73eb-4834-8747-a8cc43ac8842

**Comment by Snownee** [comment]
This issue should be fixed by the other side. But I don't think it's technically worth it.
