### ISSUE TITLE
Suggestion - blacklist blocks from snow accumulation

### ISSUE THREAD

**Issue by katubug** [Snownee/SnowRealMagic#35]
* Minecraft Version: 1.12.2
 * Mod Version: 0.3.3

Hi! I'm doing some testing for a modpack I'm working on, which includes this mod. However, there are some blocks/tile entities which accumulate snow which either look strange, or don't make sense.

This is one of the former - a Pyrotech Bloomery, with a floating snow tile on top. And as for the latter, I didn't get a screenshot, but noted that Magma Blocks can *also* accumulate snow.

![2019-12-28_23 26 11](https://user-images.githubusercontent.com/20935286/71552826-79fcd700-29c9-11ea-8db8-61aed0a8014f.png)

I am not sure how much work it would be to add a config option to let pack makers blacklist certain tile entities from having snow spawn on them, or if you are even supporting the 1.12 version any longer - but if this were a possible option, it would be fantastic.

In any case, thank you very much for this great mod. I hope you have a very happy new year's!

**Comment by Snownee** [comment]
Have you tested without Snow! Real Magic! ? Does snow accumulate on the block?

**Comment by katubug** [comment]
Just tested! Yes, it generates on those blocks even without Snow! Real Magic. If there's a way of preventing vanilla snow from appearing on specified blocks, I suppose I could just use that! I'll look into it.

**Comment by Snownee** [comment]
I think this is a bug of Pyrotech, you should report to Pyrotech directly. Just like [this](https://github.com/codetaylor/pyrotech/issues/76) and [this](https://github.com/codetaylor/pyrotech/issues/172)

**Comment by katubug** [comment]
That's fair, I will do so. However, I do think this would be a nice feature to have, so that "hot" blocks such as magma etc do not accumulate snow. However, I'm guessing this would be a bigger project than I'd initially thought, since you'd be altering vanilla behavior instead of simply adding on to it. In any case, thank you very much for your help! :)

**Comment by Snownee** [comment]
I will consider that, thank you!
