### ISSUE TITLE
[Suggestion] Improve Snowy Tall Grass

### ISSUE THREAD

**Issue by ChloeDawn** [Snownee/SnowRealMagic#356]
### Mod loader

NeoForge

### Minecraft version

1.20.1

### Mod version

10.2.7

### Modloader version

47.1.100

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Currently the upper half of tall grass does not change its texture when the lower half is snowy, and it looks rather strange.
I think a good way to texture it would be to have both halves yellowed, but only the upper half snowy (like snow has fallen on it).

![In-game screenshot of tall grass](https://github.com/Snownee/SnowRealMagic/assets/9869940/8d79a6a6-a8f9-4feb-bfb4-0d54acd4f25d)

**Comment by ChloeDawn** [comment]
After looking at the mod assets I see you have textures for this so this may be a world gen bug in my modpack.
Although, it seems that if I build snow layers into the upper half it then displays the correct texture, so I'm unsure.

![Screenshot of snow in upper half of tall grass](https://github.com/Snownee/SnowRealMagic/assets/9869940/5b8bca54-93b6-4a6b-8cb2-b8302bd3d6b4)

**Comment by etherealgears** [comment]
I'm having this exact issue as well on Forge 47.2.20, MC version 1.20.1. I've tried it with only this mod installed, and the issue still persists.
