### ISSUE TITLE
Right clicking vanilla snow layer changes it to snowrealmagic:snow, repeating the action reverts it back

### ISSUE THREAD

**Issue by TeslaP09** [Snownee/SnowRealMagic#361]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

10.4.2

### Modloader version

Fabric: Loader 0.15.7 + API 0.92.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

This doesn't seem like a bug to me, just a debug feature that wasn't disabled... When right clicking a snow layer, it changes to the snow real magic variant. Clicking again reverts this. In vanilla this is barely noticeable (only in the f3 screen), but in my modpack, the snow real magic variant has other textures and shading than vanilla snow (probably because of some shader / resourcepack whitelisting only the vanilla variant or something like that...). This is reproducible in creative and survival mode and only with an empty hand. Logs don't show anything.

**Comment by Snownee** [comment]
This is a feature that allows the snow layer to show an overlay on the block at the bottom, just like snowy grass does.
