### ISSUE TITLE
Continuity enabled textures break render

### ISSUE THREAD

**Issue by WyrmTitan99** [Snownee/SnowRealMagic#363]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

10.4.3

### Modloader version

1.20.1

### Modpack info

Custom mod pack embedium embedium plus lazuite ive tried fusion and continuity with forgify fabric api

### If bug:

- [yes ] Can you reproduce this issue with relevant mods only?

The blocks beneath turn invisable with snow render floating on top. You had a simillar post from before as well

_No response_

**Comment by vinnyg0621** [comment]
it's embeddium not embedium.
