### ISSUE TITLE
Sandstorm mod suggestion

### ISSUE THREAD

**Issue by matzar24** [Snownee/SnowRealMagic#369]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

0

### Modloader version

0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Sand layers accumulating on desert during sandstorm. (Like snow in this mod)
Visibility limited to 1-2 chunks. Sandstorm blows from certain direction, so sand layers only acumulate before block steps.
And some (10%) of sand layers acumulate after downward block step.

It would be kinda good to assign to every desert most common direction of wind.
Sand slopes created by sand layers would be more consistent.

**Comment by matzar24** [comment]
It would be probably good to accumulate more sand layers the closer to player.
The further away from player, the less sand layers accumulate. Proportionally.

**Comment by Snownee** [comment]
Sorry, I am not interested in this idea
