### ISSUE TITLE
Fence with snow becomes invisible while part of create contraption.

### ISSUE THREAD

**Issue by KostromDan** [Snownee/SnowRealMagic#370]
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

6.5.4

### Modloader version

43.3.13

### Modpack info

https://legacy.curseforge.com/minecraft/modpacks/m-tech-1-19-2

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

https://youtu.be/pxiiFLAXrcE
Fence with snow becomes invisible while part of create contraption. Only snow is rendering.

**Comment by Snownee** [comment]
I have no plans to fix this problem on Forge 1.19/1.20. If this really annoys you, you can play the Fabric edition.
