### ISSUE TITLE
Serene Seasons ice doesn't melt

### ISSUE THREAD

**Issue by decathegr8** [Snownee/SnowRealMagic#371]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

10.2.7

### Modloader version

Forge: 47.2.0

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

Me and my friends are playing on a dedicated server with Serene Seasons and Snow real magic installed and in the winter all the water freezes. However, when winter ends suddenly the ice can't melt and we're stuck with frozen rivers.

**Comment by drewsterp13** [comment]
I have the same issue, I have Serene Seasons as well as Snow Real Magic installed.

**Comment by Pangiaa** [comment]
I had the same problem in connection with serene seasons at better minecraft forge.
Had to switch off the mod because the ice no longer melted.

**Comment by Snownee** [comment]
I can't reproduce it on the latest version

**Comment by xbxbxb123** [comment]
I have this same issue with the latest version and everything

**Comment by Vespidmagna** [comment]
> I have this same issue with the latest version and everything

Having the same issue as well. Quite a bummer that this is still happening. The ice completely removes the pirating aspect of my modpack, so I am hoping this can get fixed.
