### ISSUE TITLE
[Suggestion] Make the snow layer on the side of blocks is active by default

### ISSUE THREAD

**Issue by Yoni664** [Snownee/SnowRealMagic#372]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

10.4.3

### Modloader version

Fabric 0.15.11

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

I really like how the snow layer looks on other blocks and not only on the grass blocks, but I find it very sad that this has to be activated block by block with right click or placing the snow on the stairs. Is there any chance to get this to be active by default?

Let me explain with some images:
For example, these are the snow layers that im trying to get on by default:
![2024-06-05_23 03 33](https://github.com/Snownee/SnowRealMagic/assets/143241985/55d62b8e-46c1-45d2-97f0-2d68a64ab168)

In this case, i really want this option on by default to get the stairs with the snow layer on every new world, just like the stairs on the left that actually I put the snow layer manually
![2024-06-05_23 05 06](https://github.com/Snownee/SnowRealMagic/assets/143241985/07e1a64b-d215-444d-8bce-6ee8aa6899dc)

Same with the tree of the left
![2024-06-05_23 07 17](https://github.com/Snownee/SnowRealMagic/assets/143241985/e25e743c-576b-43fa-ad90-faeb5bbde327)

I really want to know if this is possible, it's mostly an immersion issue.

**Comment by Snownee** [comment]
use this instead: https://modrinth.com/resourcepack/snowiest-snow
