### ISSUE TITLE
Snowy grass erroneosly generates where it shouldn't during winter-spring with Serene Seasons

### ISSUE THREAD

**Issue by Roadhog360** [Snownee/SnowRealMagic#376]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

10.4.3

### Modloader version

47.3.1

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://gist.github.com/Roadhog360/bc32360f2ec2002403e148064a4dda33

### Issue description

So I noticed that snowy grass/flowers generates where snow doesn't, in some areas with ONLY:
- Serene Seasons
- Snow! Real Magic!
- Kiwi. 

Here is a normal, **NON-SNOWY** Taiga, during mid-spring. The same thing happens in any winter season too.
![2024-06-21_02 00 11](https://github.com/Snownee/SnowRealMagic/assets/11903511/2944b442-cf3d-4968-a54e-179938db2ae9)
And here's the same biome when generated during mid-summer
![2024-06-21_02 02 38](https://github.com/Snownee/SnowRealMagic/assets/11903511/64a5d5ec-f1bf-48c3-a3c6-63b9c44ce5a3)

I'd really like to have snowy grass enabled, so please let me know if there is any information I missed. Thanks. It looks really off when some grassy biomes are spotted with snow specifically on the grass when they shouldn't get any snow at all.

**Comment by Pockett-Dev** [comment]
I have been having this exact same issue. :(

**Comment by cobaltlol2** [comment]
Can confirm happens to me too

**Comment by Roadhog360** [comment]
I semi-solved this by using Fabric Seasons. It works with Sinytra Connector and does not have this issue in my setup, albeit Fabric Seasons does auto-snow new chunks during the winter. Then again this issue happened where it wasn't supposed to be snowy. Maybe Serene Seasons does something weird.

Either way I recommend you to try Fabric Season; imo it is actually way better.

**Comment by valchiara** [comment]
Unfortunately Sinytra Connector is not an option for MC 1.19.2, and I personally prefer Serene Seasons :P

**Comment by cobaltlol2** [comment]
What's even the difference between serene and fabric seasons?
