### ISSUE TITLE
Incompatibility between "Snow on Ice" option and "Thin Ice" from Ecologics

### ISSUE THREAD

**Issue by kkempfer** [Snownee/SnowRealMagic#377]
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

5.1.2

### Modloader version

Fabric: Loader 0.15.11 + API 0.76.1

### Modpack info

https://github.com/kkempfer/Create-Survive-Explore

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

I am making modpack that is not officially published on CurseForge/Modrinth yet, but available on GitHub. I am adding tons of realistic-like features.

To add some spice while exploring the world, I wanted to combine the "Snow on Ice" option from [Snow! Real Magic!](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic) with the "Thin Ice" block from [Ecologics](https://www.curseforge.com/minecraft/mc-mods/ecologics). In principle, the "Thin Ice" generates in icy biomes and partially replaces the normal Minecraft Ice. However, with the "Snow on Ice" option turned on, no "Thin Ice" is generated.

I confirm that the issue is reproducible on a minimal setup with only [Snow! Real Magic!](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic) and [Ecologics](https://www.curseforge.com/minecraft/mc-mods/ecologics) installed (+ their dependencies [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api) and [Kiwi](https://www.curseforge.com/minecraft/mc-mods/kiwi-fabric)).

Below, I shared some screenshots of a Frozen river. I generated the world twice using the same seed with the "Snow on Ice" option set to True and False, respectively.

### Steps to Reproduce
* Step 1: Install both [Snow! Real Magic!](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic) and [Ecologics](https://www.curseforge.com/minecraft/mc-mods/ecologics) mods.
* Step 2: Enable the "Snow on Ice" option in the "Snow! Real Magic!" mod settings.
* Step 3: Generate a new world with an icy biome using a fixed seed.
* Step 4: Observe the presence or absence of "Thin Ice".

### Expected Behavior
"Thin Ice" should generate in icy biomes and be covered with snow when the "Snow on Ice" option is enabled.

### Actual Behavior
With "Snow on Ice" set to True, "Thin Ice" does not generate at all. With "Snow on Ice" set to False, "Thin Ice" generates as expected and snow accumulates on it if it snows.

### Screenshots

Snow on Ice = True: The ice is covered with snow, but no "Thin Ice" is present beneath the snow.

![snow_on_ice_true](https://github.com/Snownee/SnowRealMagic/assets/43574603/01bc5a7b-f520-4c78-871e-1e52508976bf)

Snow on Ice = False: The ice is not covered with snow and "Thin Ice" is present. If it is snowing, a snow layer will appear on top of the "Thin Ice" layers, but not on top of the Minecraft Ice.

![snow_on_ice_false_clear](https://github.com/Snownee/SnowRealMagic/assets/43574603/c0dc53bf-1af1-4395-9922-14894822e620)

![snow_on_ice_false_rain](https://github.com/Snownee/SnowRealMagic/assets/43574603/aeaceea3-cd16-4e15-8ea0-7d7f7e11cde6)

**Comment by Snownee** [comment]
I think this should be fixed on their end. Their worldgen feature is executed too late
