### ISSUE TITLE
Client crash when leaving server

### ISSUE THREAD

**Issue by Wash113** [Snownee/SnowRealMagic#380]
### Mod loader

Fabric

### Minecraft version

1.21

### Mod version

11.0.1

### Modloader version

Fabric 0.15.11 / 0.100.4

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://mclo.gs/6WbHNVb

### Issue description

This one took a while to track down. My server population have been experiencing a client crash immediately after clicking disconnect. After a lot of chasing, Ive narrowed it down to this mod. Ive included a log from my fabric instance, but this crash persists in Quilt also. Ive included an image with the other mods we are using. The crash log indicates its a null exception on the mouse click handler. Happy hunting!

![image](https://github.com/Snownee/SnowRealMagic/assets/31891715/d9c38985-20c3-4171-9f46-5906d323766f)

**Comment by Snownee** [comment]
Why do you think the crash is caused by my mod?

**Comment by Wash113** [comment]
Process of elimination. I tried disabling every other mod in that list, this was the only one that resolved the crash when removed

**Comment by Snownee** [comment]
![222](https://github.com/Snownee/SnowRealMagic/assets/16059084/f8beb0fd-96e6-4b07-86ba-6e7292344946)

I can't reproduce it
