### ISSUE TITLE
Incompatibility with Physics Mod snow

### ISSUE THREAD

**Issue by OrangeSniper** [Snownee/SnowRealMagic#383]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

10.4.4

### Modloader version

Forge: 1.20.1 - 47.3.0

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

The mod’s snow does not work with Physics mod snow

**Comment by Snownee** [comment]
Thanks for the suggestion. We have no plans for this at this time.
