### ISSUE TITLE
Incompatible with Indium mod

### ISSUE THREAD

**Issue by Shark10199** [Snownee/SnowRealMagic#385]
### Mod loader

Fabric

### Minecraft version

1.21

### Mod version

11.0.2

### Modloader version

0.16.0

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://mclo.gs/9wfPBTG

### Issue description

When loading up a world, the game crashes.

**Comment by Shark10199** [comment]
I found out it was because of Fabric API but now things seem to work.

**Comment by Snownee** [comment]
Indium's bug. not related to SRM

**Comment by alexia8225** [comment]
What can I do to fix it since I can't play the mod without Indium and Sodium? Thank you

**Comment by Snownee** [comment]
you can try to downgrade Indium

**Comment by alexia8225** [comment]
I downgraded to Sodium version 0.5.9 and Indium version 1.0.33 both for verson 1.21 of Minecraft and still crashing
