### ISSUE TITLE
Natural melting doesn't work on cold biomes when Serene Seasons mod is installed

### ISSUE THREAD

**Issue by VindSole** [Snownee/SnowRealMagic#388]
### Mod loader

Fabric

### Minecraft version

1.21

### Mod version

11.0.2

### Modloader version

Fabric Loader 0.16.2, Fabric API 0.102.0

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://gist.github.com/VindSole/23240b15c4bb60a0f628fd666245c4e8

### Issue description

When using the Serene Seasons mod, the option natural melting, which allows snow layers higher than 1 to melt back to 1 after an snowstorm doesn't work, issue seems to only affect cold biomes.

**Comment by Bit-Newt** [comment]
I have also experienced this bug in Forge 47.1.3 for Minecraft 1.20.1. In the short term, I think I'll just disable the mod outside of winter.

**Comment by TheVillain-Inc** [comment]
I appreciate this issue is closed - but its also happening on 1.20.1. I did not wish to duplicate. 

Same outcome, snow in cold biomes doesn't melt back down to 1 layer at any season, any weather. 
I also run Serene Seaons Fix, but have testing without that. 

MC: 1.20.1
Forge: 47.3.12 
Serene Seasons: 9.1.0.0
Snow Real Magic: 10.5.2
Serene Seasons Fix: 1.1.0.1

**Comment by PvtFudgepants** [comment]
I'm having this issue even though this is closed. Snow accumulates, but doesn't ever melt, so you end up with massive snow piles everywhere.

1.21.1 
Neoforge 21.1.216
Serene Seasons 10.1.0.3
Snow real magic 12.1.2

**Comment by Pecl-ffdd** [comment]
If you want to melt snow that is more than 1 layer you can add this to [util/CommonProxy](https://github.com/Snownee/SnowRealMagic/blob/1.21-fabric/src/main/java/snownee/snow/util/CommonProxy.java) or delete this section completely if you want to melt completely:
```
if (sereneseasons) {
			if (layers > 1) {
				return SnowCommonConfig.snowNaturalMelt && skyLightEnoughToMelt(level, pos, layers);
			}
			return SereneSeasonsCompat.shouldMelt(level, pos, biome);
		}
```
