### ISSUE TITLE
World generation bug

### ISSUE THREAD

**Issue by chimericdream** [Snownee/SnowRealMagic#39]
* Forge Version: 28.1.92 (1.14.4)
 * Mod Version: 1.5.0 beta
 * Have OptiFine installed? No.

I came across a pretty severe world generation bug in the latest beta version of the mod. I was able to reproduce with a minimal setup of Forge, Kiwi, and SRM. It doesn't affect all biomes, but does affect a pretty large number of them. Here is a screenshot of the issue:

![2020-01-01_16 01 00](https://user-images.githubusercontent.com/198075/71646564-5b8c2980-2cb0-11ea-8fd4-bfacf5f79f92.png)

**Comment by chimericdream** [comment]
And here is a screenshot of the mod versions for the minimal "pack" I tested this in:

![snow-bug-repro](https://user-images.githubusercontent.com/198075/71646660-af970e00-2cb0-11ea-8937-c7936620e7a6.png)

**Comment by chimericdream** [comment]
And one more. This is the same world freshly generated with 1.4.5 (from roughly the same position)

![2020-01-01_16 10 12](https://user-images.githubusercontent.com/198075/71646750-54b1e680-2cb1-11ea-8310-850ff1c29e5c.png)

**Comment by WenXin20** [comment]
I also came across this bug recently, and had spent quite some time trying to figure out which mod caused it.

I'm using v1.5.0 with Forge v28.1.109

**Comment by Snownee** [comment]
I think there is something wrong when Forge replaces block registry. The safest way for me is giving up the relevant feature.

**Comment by Yamza** [comment]
This issue is still present in the 1.15.1 version of the mod. SnowRealMagic-1.15.1-1.5.0 https://i.imgur.com/Yihdzpq.png

**Comment by Snownee** [comment]
MinecraftForge/MinecraftForge#6410
