### ISSUE TITLE
Incompatability with Radium on NeoForge 1.20.1

### ISSUE THREAD

**Issue by danaYatsuta** [Snownee/SnowRealMagic#394]
### Mod loader

NeoForge

### Minecraft version

1.20.1

### Mod version

10.5.1

### Modloader version

NeoForge: 47.1.106

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://mclo.gs/YF86CVc

### Issue description

Crash very early on in loading process with Radium 0.12.3+git.50c5c33. Log generated by instance that only has Snow! Real Magic, Kiwi and Radium.

**Comment by Snownee** [comment]
please report it to Radium
