### ISSUE TITLE
Option to break snow layer independent of master block

### ISSUE THREAD

**Issue by IronPiston** [Snownee/SnowRealMagic#40]
* Forge Version: 28.1.109
 * Mod Version: 1.14-1.5.1

Currently, breaking a snow covered slab/stair/etc. returns a snow covered block. Could a config be added that instead makes the snow layer break independent of the block? That way you could remove snow from the top of a block without destroying the base block.

**Comment by Snownee** [comment]
If you want to remove snow from a block, just right click with shovel
