### ISSUE TITLE
crashes without a crashlog on recent version

### ISSUE THREAD

**Issue by itsdeadfrosty** [Snownee/SnowRealMagic#401]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

10.5.2

### Modloader version

Forge 47.3.7

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://pastebin.com/btBJkNvZ

### Issue description

![image](https://github.com/user-attachments/assets/f174d714-8610-4297-bbe6-f26da2c6aacf)

both 10.4 and 10.5 not working with serene seasons and gang.

i can try to mimic in new profile. or whatever you reccomend.

**Comment by serioos** [comment]
I have this problem too. The latest Snow is magic crashes on start up. This is all I have:

https://pastebin.com/Wb03kqez

Minecraft 1.20.1
Forge 47.3.10
SnowRealMagic-1.20.1-Forge-10.5.2.jar

**Comment by Snownee** [comment]
> I have this problem too. The latest Snow is magic crashes on start up. This is all I have:
> 
> https://pastebin.com/Wb03kqez
> 
> Minecraft 1.20.1 Forge 47.3.10 SnowRealMagic-1.20.1-Forge-10.5.2.jar

https://github.com/dima-dencep/rubidium-extra/issues/92

**Comment by Snownee** [comment]
update

**Comment by itsdeadfrosty** [comment]
nope, modern versions cause the crash. im using a 2023 version.

**Comment by Snownee** [comment]
please make sure this bug is reproducible on a minimal setup, not a modpack with many other mods.

**Comment by itsdeadfrosty** [comment]
yeah i dont care enough.

if thats not helpful, hope u feel the same about "Update" as a response
