### ISSUE TITLE
Error with Fancier Block Particles

### ISSUE THREAD

**Issue by reddvilzz** [Snownee/SnowRealMagic#404]
### Mod loader

Forge

### Minecraft version

1.12.2

### Mod version

0.7.1

### Modloader version

Cleanroom 3.3.4-27

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://mclo.gs/1OpHav4

### Issue description

There seems to be an error on the log at the beginning of world creation / world load when using with [Fancier Block Particles mod](www.curseforge.com/minecraft/mc-mods/fbp), it was mentioned at the [github ](https://github.com/Red-Studio-Ragnarok/Fancier-Block-Particles/issues/15) of the mod before but me it hasn't been fixed. Let me know if you needed anything to help.

`[07:08:44] [Server thread/ERROR] [snowrealmagic]: Catching
java.lang.ClassNotFoundException: com.TominoCZ.FBP.FBP`

**Comment by Desoroxxx** [comment]
Oh, this makes sense since I changed my package name.

Anyway, the original fix was janky; I PR'd a new, better fix #405

**Comment by reddvilzz** [comment]
Thank you for the quick PR Fix, how can I build the mod with the fix? Seeing as the 1.12.2 was last contributed from a year ago.. Might have small chance for the fix to be compiled for 1.12.2

**Comment by reddvilzz** [comment]
Thank you for the quick fix.
