### ISSUE TITLE
Cross mod compatibility with Terrafirmacraft

### ISSUE THREAD

**Issue by Zenostriker** [Snownee/SnowRealMagic#407]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

4.2.4

### Modloader version

Forge 40.2.0

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://pastebin.com/embed_js/yKxxbSEi

### Issue description

Currently when I try and load Minecraft with both TFC and SRM the game crashes. It looks like both mods are trying to overwrite the vanilla snow generation. Is there a simple way to fix this or possible support for TFC in the future?

**Comment by Snownee** [comment]
Sorry, I no longer provide support for 1.18.2. But I may be able to put you in touch with someone who can help you with this for a fee. If you are interested, please contact me on Discord!
