### ISSUE TITLE
Transparent textures with sodium-neoforge-0.6.0+mc1.21.1

### ISSUE THREAD

**Issue by kontrola111** [Snownee/SnowRealMagic#409]
### Mod loader

NeoForge

### Minecraft version

1.21.1

### Mod version

11.0.13

### Modloader version

21.1.83

### Modpack info

-

### [IMPORTANT] If bug:

- I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

File attached below

### Issue description

Hi, I created a mod pack and noticed that when snow falls on the roof or short grass it becomes invisible/transparent.

I checked which mod causes this and it turned out that the problem occurs with
sodium-neoforge-0.6.0+mc1.21.1

**Comment by kontrola111** [comment]
[latest.log](https://github.com/user-attachments/files/18044039/latest.log)

**Comment by DarthCaesium** [comment]
Wait, so is the bug fixed?

**Comment by kontrola111** [comment]
> Wait, so is the bug fixed?

Unfortunately not : (
You can try using the embeddium with a monocle and iris
but for my setup i discovered that it haves bugs, I reported them to the creator
