### ISSUE TITLE
Support for double height plants

### ISSUE THREAD

**Issue by IronPiston** [Snownee/SnowRealMagic#42]
* Forge Version: 28.1.109
 * Mod Version: 1.14-1.5.1

Plants like ferns currently don't support snow underneath them. In [this issue](https://github.com/Snownee/SnowRealMagic/issues/3), you mention a whitelist for block support. At least on 1.14 versions, this isn't available. Could the whitelist be added, or at least support for double height plants? Ferns specifically generate in snowy areas, so it looks a bit off.

**Comment by Snownee** [comment]
Supporting double plants requires a lot of extra codes. Whitelist does not solve anything
