### ISSUE TITLE
Suggestion: Snow accumulation greater than 1 block or 8 layers

### ISSUE THREAD

**Issue by phyne** [Snownee/SnowRealMagic#45]
* Forge Version: 1.14.4 - 28.1.113
 * Mod Version: SnowRealMagic-1.14.4-1.5.2

After turning off snow melt, I was hoping for infinite accumulation of snow. It seems that snow only accumulates up to 8 layers, and then stops. My plan was for players building in snow having to continuously clear paths/buildings of snow otherwise face being buried by snowpack.

Is it possible for 8 layers of snow to turn into a snow block so accumulation can continue, or through some black magic have layers accumulate beyond 8 layers?

**Comment by Archer-Dante** [comment]
Same wish for 1.12.2 !
