### ISSUE TITLE
Crash w/ Cube+ & Explorercraft

### ISSUE THREAD

**Issue by WenXin20** [Snownee/SnowRealMagic#47]
* `Forge v28.1.115`
 * `Snow Real Magic v1.5.2`
 * `Kiwi v2.6.1`
 * [`Hwyla v1.10.6-B67`](https://www.curseforge.com/minecraft/mc-mods/hwyla)
 * [`Explorercraft v3.2.4`](https://www.curseforge.com/minecraft/mc-mods/explorercraft-worldexpansion)
 * [`Cube+ v1.1.2`](https://www.curseforge.com/minecraft/mc-mods/cubeplus)
 * Have OptiFine installed? No

This crash is a bit complicated. It took me a while to figure out what was going on.
- The mod Cube+ seems to override stair block placement to place it's own equivalent of stairs, so with this mod, snow layers cannot be placed on those stairs. 
- But if `/setblock` is used or if a stair from a structure is found, then its a normal Minecraft stair block. If a snow layer is placed on this stair block, then I get a crash with Hwyla when looking at the snowy stair block.
- And for some reason, Explorercraft has to be installed or there isn't a crash. And removing either Hwyla or Cube+ will also not give a crash.
[Crash Report](https://gist.github.com/WenXin20/ced02f8d54c6554f72008b2150feb196) 
[Hwyla Error Output](https://gist.github.com/WenXin20/f1d6989d9cbb657d4a1c9549225b4df1)

**Comment by Snownee** [comment]
I have no idea what is going on and I do not touch rendering things. Maybe you should report it to Explorercraft. Thx
