### ISSUE TITLE
Snow not pile up

### ISSUE THREAD

**Issue by ImHePaul** [Snownee/SnowRealMagic#49]
Snow not pile up on bloc, i have only have 1 layer of snow, i'm on 1.12.2

**Comment by Yamza** [comment]
Can confirm this is an issue in 1.15.1 as well, only Snow and Kiwi installed. Forge 30.0.42 https://i.imgur.com/Kko0oxf.png

**Comment by Snownee** [comment]
@Yamza I cannot reproduce this in 1.15.1

**Comment by Yamza** [comment]
The default setting for snow during "rain" is disabled. Snow will only accumulate by "thunder" storm with the default setting. Check your config and try testing it again.

```
snowAccumulationDuringSnowstorm = true
snowAccumulationDuringSnowfall = false
```

**Comment by shtfaced** [comment]
I am using Serenes Season mod with SRM and during winter snow is not accumulating. I already checked config. Am I doing something wrong or is Serenes Seasons just not working with SRM?

mods (
Forge 30.0.38 , 
Kiwi-1.15.1-2.6.3 , 
SereneSeasons-1.15.1-3.0.0.43-universal , 
SnowRealMagic-1.15.1-1.7.1
)

Thank You
Much love

**Comment by Purplo262** [comment]
> I am using Serenes Season mod with SRM and during winter snow is not accumulating. I already checked config. Am I doing something wrong or is Serenes Seasons just not working with SRM?
> 
> mods (
> Forge 30.0.38 ,
> Kiwi-1.15.1-2.6.3 ,
> SereneSeasons-1.15.1-3.0.0.43-universal ,
> SnowRealMagic-1.15.1-1.7.1
> )
> 
> Thank You
> Much love

There seems to be a compatibility issue with mixinbootstrap (the core mod needed by this one to have full features) and Serene Seasons. I noticed this when I had the immersive portals mod installed (uses the same core mod) it was making seasons change whenever I slept and prevented snow from building up or turning fences/slabs/stairs into the snowy versions. 

Hopefully they fix this issue soon!

**Comment by EternalOne11** [comment]
I also have this issue not sure which mod is causing it but it is very annoying since it is a main feature of this mod.

**Comment by Snownee** [comment]
Seems to be similar issue to #68
