### ISSUE TITLE
2 fence on snowy-non snowy block doesn't link

### ISSUE THREAD

**Issue by MilkissWhite** [Snownee/SnowRealMagic#50]
* Forge Version: 30.0.41
 * Mod Version: 1.5.2
 * Have OptiFine installed? See previous issues first
= not installed.

Paste your crash report to somewhere like https://paste.ubuntu.com/, instead of directly here.
= no crash.

---
when I placing fence on snowy block, that snowy-fence doesn't link with already adjust fence on non-snowy block.
it can be fix by just break non-snowy fence and place it again.

here is what screenshot of bug

![snowrealmagic_bug001](https://user-images.githubusercontent.com/60180416/72893468-67718580-3d5c-11ea-8064-3f4b7c29e13b.png)

and here is my mod list

![modlist](https://user-images.githubusercontent.com/60180416/72893549-a1db2280-3d5c-11ea-8871-314bcd892eb5.png)

**Comment by Snownee** [comment]
Cannot reproduce with Snow! Real Magic! only

![image](https://user-images.githubusercontent.com/16059084/72894216-c5e73580-3d55-11ea-82e3-a32c53818c5b.png)

**Comment by MilkissWhite** [comment]
I could reproduce with Snow! Real Magic! only

![snowrealmagic_bug002](https://user-images.githubusercontent.com/60180416/72894687-3e062900-3d5f-11ea-964c-0f1540cad8cc.png)


![snowrealmagic_bug003](https://user-images.githubusercontent.com/60180416/72894692-4199b000-3d5f-11ea-8faa-04c9cde618ac.png)

I did this order
1. create new world 'creative'
2. /locate igloo
3. place dirt, place fence on dirt, place fence on snow
