### ISSUE TITLE
Crash when trying to join my local server? 

### ISSUE THREAD

**Issue by HentaiHamster** [Snownee/SnowRealMagic#52]
My server is running fine but my client is crashing whenever I join 
1.14.4 
forge: 28.2.0 
Kiwi: 2.6.3
SRM: 1.5.2

here is the log https://pastebin.com/CLWc9A8X

Says something about block tessellation and it's the stairs that is doing it.

**Comment by Snownee** [comment]
It is a BetterFoliage bug: https://github.com/octarine-noise/BetterFoliage/issues/276
