### ISSUE TITLE
Snow block has no texture

### ISSUE THREAD

**Issue by Scifantech** [Snownee/SnowRealMagic#56]
I am modding Minecraft 1.12.2 and when I install SnowRealMagic the snow block shows up with the purple and black checkered texture and that shows up also when the snow is accumulating on the ground in game. Can anyone tell me a quick fix for this.

**Comment by Snownee** [comment]
Seems to be incompatible with LiteLoader

**Comment by Scifantech** [comment]
I will remove that and see if it works, thank you.
