### ISSUE TITLE
Crash during new chunk generation

### ISSUE THREAD

**Issue by Yamza** [Snownee/SnowRealMagic#58]
Looks like this may be caused by a snowy dirt block.
https://s.yoosk.pl/cvYEk

SnowRealMagic-1.15.2-1.7.2.jar
Forge: net.minecraftforge:31.1.27

**Comment by Snownee** [comment]
Can it be reproduced?

**Comment by Yamza** [comment]
Wouldn't know how, don't even understand how it's happening.

**Comment by yurisuika** [comment]
https://hastebin.com/debejoyoru.pl
https://hastebin.com/lehifaride.makefile
https://hastebin.com/doyipiruqe.makefile
https://hastebin.com/heyexuvehe.makefile

I am getting a very similar crash. Mine seems to involve tree spawning, or a sheep, or falling snow. I've disabled TerraForged's smooth snow layering in the first two, and the natural snow decorator as well in the next two. Seems to be a slight pattern with the sheep in the first two, and the falling snow layer in the next two.

There is snow right by the spawnpoint with this generation and it doesn't crash, but when I TP to an area I know where snow spawns a few km away, it will crash within a second or so. I can't load up the map again without it crashing right away from there on.

As soon as I remove this mod, all is fine, so I am pretty sure this is the source of the crash.

**Comment by Snownee** [comment]
There is some issues with Mixin that let codes are injected differently between dev environment and actual environment. Now I have used another way to avoid this
