### ISSUE TITLE
Snow is not accumulating on fences, grass, ect.

### ISSUE THREAD

**Issue by Supernova792** [Snownee/SnowRealMagic#61]
![Image](https://i.imgur.com/MDA4nCU.png)
Snow does not appear on/under fences, grass, stairs, flowers when snowing, must be manually placed to take affect (Stairs can't be manually "snowed" in general)

Is this a post 1.12.2 feature only?

MC Version: 1.12.2
Forge: 14.23.5.2852
SnowRealMagic: 0.3.3
MixinBootstrap: 1.0.2

**Comment by Snownee** [comment]
This feature is not available in 1.12. Also 1.12 is no need to install MixinBootstrap
