### ISSUE TITLE
Server Crashes on Startup

### ISSUE THREAD

**Issue by kornfan6589** [Snownee/SnowRealMagic#62]
Running SnowRealMagic 1.15.2 1.7.4
Forge 31.1.46
Mixin bootstrap 1.0.2

Try to start server and it closes rather quickly. Below is the debug log because it doesnt generate a crash report; i dont think it gets that far in startup to do so.

if i remove just snowrealmagic server starts without issue

https://pastebin.com/7QZnTPu7

**Comment by Snownee** [comment]
I can't reproduce this with snowrealmagic only

**Comment by kornfan6589** [comment]
its because im dumb and was missing kiwi, didnt realize it was a dependency

**Comment by kornfan6589** [comment]
its listed as a dependency on curseforge but only if you click individual files and scroll alllll the way down. maybe add a note on the main page description for other idiots like me. or if it is there make it bold because i didnt see it lol
