### ISSUE TITLE
Mod doesn´t work on Bricks (Clay)?

### ISSUE THREAD

**Issue by Artemis2017** [Snownee/SnowRealMagic#63]
Hello,

the Mod doesn´t work on Bricks + Slabs (clay)

![grafik](https://user-images.githubusercontent.com/25553095/79616363-2c85b080-8105-11ea-8fc1-9fcf971c5242.png)

How i can resolved it?

Info: Play MC on 1.15.2 with Forge 31.1.46

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/79717695-f3b82800-830c-11ea-8f53-ecc678552161.png)
Can't reproduce
