### ISSUE TITLE
Lighting bug with stairs

### ISSUE THREAD

**Issue by Aegarain** [Snownee/SnowRealMagic#64]
The lighting for stairs gets messed up when the stairs are in complete darkness and placed over a light source
![2020-04-18_16 09 33](https://user-images.githubusercontent.com/63934486/79673584-eb86ae00-818f-11ea-9491-89ce500f5f97.png)
![2020-04-18_16 09 40](https://user-images.githubusercontent.com/63934486/79673588-ed507180-818f-11ea-9e0f-e6882883543b.png)
![2020-04-18_16 15 08](https://user-images.githubusercontent.com/63934486/79673589-ee819e80-818f-11ea-8993-3bae33722818.png)

Appears in both 1.15.2 and 1.14.4

1.15.2 Modlist:
Forge 31.1.0
SnowRealMagic 1.7.4
Kiwi 2.6.5
Mixinbootstrap 1.0.2

1.14.4 Modlist:
Forge 28.2.0
SnowRealMagiv 1.5.2
Kiwi 2.6.3
Mixinbootstrap 1.0.2

**Comment by Snownee** [comment]
I think it is a vanilla bug. If you look carefully to vanilla stairs, you can see same issue there. My blocks is a little special and make this more obvious

I do not know how to fix this, sorry
