### ISSUE TITLE
Snow doesn`t melt on Slabs/Bricks?

### ISSUE THREAD

**Issue by Artemis2017** [Snownee/SnowRealMagic#65]
Hello,

the snow doesn´t melt on Slabs/Bricks if a torch is in the near.

And is this Mod compatible with Serene Seasons Mod? If not, can you fix it pls? Thank you very much!

MC Version 1.15.2 
Forge 31.1.46

**Comment by Snownee** [comment]
![image](https://user-images.githubusercontent.com/16059084/79717860-5d383680-830d-11ea-89a4-eeeb527e181e.png)
Can't reproduce
