### ISSUE TITLE
No new blocks :D

### ISSUE THREAD

**Issue by Matthysse** [Snownee/SnowRealMagic#67]
Hello ! (again)
Yes I know it's the same as the other one, but you closed my issue and I don't know if you see new messages. I just wanted to say : yes it does, it's possible. I tried removing schifted snow and it only removes the snow and not the stairs. The stairs/slabs/walls aren't changed at all it's just the snow which is on top of it which has a model that is a block under and has a different hitbox. 
It's just a perfect workaround. It would let many new things like being able to place multiple layers on slabs / stairs / walls, more mod compatibility, no thousands of new blocks (just the the snow on the different blocks) and so more leightweight. You can even keep the overlay of the snowy-grass texture.

**Comment by Snownee** [comment]
OK, i get that. I do not think that is a good solution. I have done a new mode to retain original blocks
