### ISSUE TITLE
Incompatible with Serene Seasons?

### ISSUE THREAD

**Issue by Artemis2017** [Snownee/SnowRealMagic#68]
Mod doesn`t work. Any Ideas why?

![2020-04-21_19 46 06](https://user-images.githubusercontent.com/25553095/79896626-e5e7cd00-8408-11ea-90a7-e764c359d640.png)

MC Version: 1.15.2
Forge: 31.1.47

Mods:
![grafik](https://user-images.githubusercontent.com/25553095/79896804-1891c580-8409-11ea-9d69-acb4bf35a943.png)

**Comment by Snownee** [comment]
Please describe your problem in detail

**Comment by Artemis2017** [comment]
It's snowing but the Stairs/Slabs don´t covered with Snow.

**Comment by Snownee** [comment]
Did you install the mod. Is SereneSeasons incompatible?

**Comment by Artemis2017** [comment]
I install all the Mods, which i post. 

Don´t know. I will ask it.

**Comment by Snownee** [comment]
You can try to uninstall that

**Comment by Artemis2017** [comment]
I uninstall SereneSeasons and the Snow is now covered on the Slabs/Stairs. But very slowly. I need to let it 3+Times  snowing that they covered.

**Comment by Artemis2017** [comment]
Here is the answer from the Serene Seasons Mod Creator/Author:

![grafik](https://user-images.githubusercontent.com/25553095/80117391-6d5b4a80-8587-11ea-9bb3-426f5e268488.png)

**Comment by Snownee** [comment]
https://github.com/Glitchfiend/SereneSeasons/issues/247
I assume it will be fixed once this get fixed. If not you can report again then
