### ISSUE TITLE
Block Texture From Snow fall

### ISSUE THREAD

**Issue by cappyy** [Snownee/SnowRealMagic#69]
so ive been testing some things on my modded server i have found out that certain blocks the snow lands on will generate a uneven texture take a look 
![2020-05-04_02 18 23](https://user-images.githubusercontent.com/64769115/80940704-957c5200-8dae-11ea-90e3-c551051ec656.png)

**Comment by Hukenon** [comment]
Using latest version released for 1.16, This seems to happen to all bottom slabs. Stairs seem to work fine aside from odd shadows with shaders. It gets a bit annoying when you wanna shovel your house before a picture.

**Comment by Snownee** [comment]
Use Kiwi 3.5.1 to fix this
