### ISSUE TITLE
[1.14.4] Server crash when snow falls on BoP stairs?

### ISSUE THREAD

**Issue by ProsperCraft** [Snownee/SnowRealMagic#7]
https://gist.github.com/ProsperCraft/87f38b3783bcd22aa977c36763614bec

	SnowRealMagic-1.14.4-1.0.0.jar
Forge .45

**Comment by Snownee** [comment]
Please update Kiwi. I hope I have fixed this issue

https://www.curseforge.com/minecraft/mc-mods/kiwi/files/2760872
