### ISSUE TITLE
Snow Layers Dont Stack Inside Blocks

### ISSUE THREAD

**Issue by Zijuna** [Snownee/SnowRealMagic#73]
I have Kiwi 2.5.6, MixinBootstrap 1.0.3 and SnowRealMagic 1.7.5 with forge 31.2.0 installed on a completely clean 1.15.2 installation and when I try putting more than the base layer of snow on a block (fence, stairs, walls) just does nothing. I've also tried dropping multiple layers on a block, and they just disappear upon impact.

Is this on purpose, am I missing a config or what?

https://imgur.com/a/Gu994EF

**Comment by Snownee** [comment]
It is on purpose. Stackable snow layer will occupy too many block states

**Comment by Zijuna** [comment]
Then please update the gif on the curseforge page, that would be nice.

**Comment by Snownee** [comment]
That is feature for 1.12.2
