### ISSUE TITLE
Weird bug with villages in snowy biomes

### ISSUE THREAD

**Issue by MilkMan1776** [Snownee/SnowRealMagic#74]
![2020-06-10_17 05 58](https://user-images.githubusercontent.com/66752182/84318731-e2d1a900-ab3c-11ea-9d10-0c676f4fff21.png)
![2020-06-10_17 02 34](https://user-images.githubusercontent.com/66752182/84318737-e6653000-ab3c-11ea-9ddb-d7f8d0a76922.png)

There's small patches of grass or path blocks that don't have any snow or any other blocks on top of them. Right clicking on these blocks results in a missing texture block appearing. I've tried running this mod on it's own (With the dependent mods as well) and the issue still occurred. I am also running the latest version of Forge and Snow Real Magic.

**Comment by Snownee** [comment]
I cannot reproduce it
