### ISSUE TITLE
Init Crash if using TerraFirmaCraft

### ISSUE THREAD

**Issue by Inqie** [Snownee/SnowRealMagic#78]
[crash-2020-06-30_19.25.44-client.txt](https://github.com/Snownee/SnowRealMagic/files/4851003/crash-2020-06-30_19.25.44-client.txt)

Crashes while initialising game with error "java.lang.NullPointerException: Initializing game". 
Only mod installed besides TFC. Forge 1.12.2-14.23.5.2854 Windows 10. Crashed also with a full mod order but I isolated it to TFC. More info in the crash log than I can give.

**Comment by nepphhh** [comment]
Similar crash on init. Not using TFC. https://pastebin.com/Rd6dXpwd

**Comment by Snownee** [comment]
> Similar crash on init. Not using TFC. https://pastebin.com/Rd6dXpwd

You didn't install Kiwi

**Comment by seanodell** [comment]
> > Similar crash on init. Not using TFC. https://pastebin.com/Rd6dXpwd
> 
> You didn't install Kiwi

What does this mean? Something else needs to be installed?

**Comment by juraj-hrivnak** [comment]
Related to:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/1642
