### ISSUE TITLE
[1.15 & 1.16] Structurize compatibility crash

### ISSUE THREAD

**Issue by Nightenom** [Snownee/SnowRealMagic#82]
Hello, 
a player reported a crash to our mod (Structurize) which is our fault but it's way easier to solve for you than for us.

Description: the crash [(issue link)](https://github.com/ldtteam/Structurize/issues/185) occurs from your call [(link)](https://github.com/Snownee/SnowRealMagic/blob/1.15/src/main/java/snownee/snow/client/SnowRenderer.java#L46) in Forge code because our current version of the mod doesn't handle fake world rendering in vanilla-like way. It's not feasible for me to use ClientRenderCache along with current rendering code.

Proposed solution: create a marker interface for you to determine whether to use ClientRenderCache or tile entity world directly

This issue will most likely become invalid with a rewrite of our mod (no eta right now)

**Comment by Nightenom** [comment]
If this forge issue [(link)](https://github.com/MinecraftForge/MinecraftForge/issues/7197) will become valid I can make PR which will also solve this issue

**Comment by Snownee** [comment]
Looks like it is a Forge bug. The way for me to manipulate cache is very limited

**Comment by MWG-Logan** [comment]
Also when snow lands on structurize roofing blocks it turns them into blocky stairs, likely because they are coded over stairs. Is there any way to either blacklist the snow falling on them or render the snow with the roof instead of the base stair hitbox?

**Comment by Nightenom** [comment]
@Snownee you should be able to use optional in 1.16 now, 1.15 is still under review (not sure why tho)
something like `MinecraftForgeClient.getRegionRenderCacheOptional(te.getWorld(), pos).orElse(te.getWorld())`

**Comment by Snownee** [comment]
> @Snownee you should be able to use optional in 1.16 now, 1.15 is still under review (not sure why tho)
> something like `MinecraftForgeClient.getRegionRenderCacheOptional(te.getWorld(), pos).orElse(te.getWorld())`

Good to know. Thank you Nightenom!
