### ISSUE TITLE
Acacia Everything

### ISSUE THREAD

**Issue by Irishmun** [Snownee/SnowRealMagic#83]
[1.16.1]Everything that is covered in snow becomes the acacia variant until broken or block picked
![Untitled](https://user-images.githubusercontent.com/43503915/89891085-c1407c80-dbd4-11ea-81a5-57d216a5d5ae.png)

ways to reproduce it:
-install the mod with only it and kiwi (not mixinbootstrap)
-place any snow covered block or have it be snowed on
-wait for a bit
it should at that point become the acacia version,
installing mixinbootstrap seems to only fix it in single player, multiplayer will still have this bug

**Comment by Alexander3847575** [comment]
ive been having the same issue, plus some other weird visual glitches. there appears to be no consistency whatsoever, nor are there any logs. related things seem to be block and lighting updates, as well as dimension changes. appears to be solely visual

**Comment by Entralia** [comment]
just had the same issue, except i'm using sodium reforged for 1.16.5 
:/
