### ISSUE TITLE
Breaking snow within a block or dropping non snow covered variant

### ISSUE THREAD

**Issue by Mnky313** [Snownee/SnowRealMagic#86]
Breaking snow covered blocks without silk touch should drop the normal (non snow covered) variant as currently I can't find a way to remove snow from a snow covered block.

Either that or have the ability to break just the snow on top of a snow covered block.

**Comment by Snownee** [comment]
you can use shovel to break top snow

**Comment by Mnky313** [comment]
thanks, I didn't know about right clicking to harvest the snow off blocks/top layer of fallen snow.

would it be possible to have a config option to have the non snow covered variants drop when they are broken?
