### ISSUE TITLE
According to the Blame mod, Snow Real Magic causes minecraft:freeze_top_layer to be unregistered.

### ISSUE THREAD

**Issue by BugmanBugman** [Snownee/SnowRealMagic#89]
I can confirm it's this mod since I just used it, Kiwi, and Blame together. Also a mention of Error adding element: Unknown registry element net.minecraft.world.gen.feature.IceAndSnowFeature@76098672
https://hatebin.com/amiprshacs

**Comment by Snownee** [comment]
Provide a case the game will not work as usual, otherwise this is a fake warning

**Comment by BugmanBugman** [comment]
Well, from the report “Then go tell that mod owner to register their ConfiguredFeature
 as otherwise, it will break other mods or datapacks that registered their stuff.” so any mods or data packs that do something in the snow biomes could possibly mess up due to freeze top layer not being registered.

Mods that don't register the stuff will cause other mod's stuff to break and not spawn during worldgen. The forge discord just recommends registering worldgen stuff in general.

**Comment by Snownee** [comment]
Thanks for telling me that. I will look into it when I have time
