### ISSUE TITLE
能不能给原版的雪设置一个可穿透方块名单，我发现他跟宝藏2mod的石碑会出现很奇怪的堆叠

### ISSUE THREAD

**Issue by Abo233** [Snownee/SnowRealMagic#9]

**Comment by Abo233** [comment]
就像原版栅栏那样的堆叠方块名单，还有一些很奇葩的生成，比如说原版的蘑菇也奇奇怪怪的，

**Comment by Abo233** [comment]
有一些mod的不规则方块，上面会生成蘑菇，看着就像浮空一样。。。

**Comment by Abo233** [comment]
夸克的钟乳石柱上面居然可以承载砂砾。。。（石柱不是方块。。尖尖的那种。）

**Comment by Abo233** [comment]
思来想去，楼主能不能添加一个就像您mod里面的雪和栅栏那样的穿透堆叠机制的名单，让玩家自定义，这样可以解决很多方块堆叠错误的问题。。

**Comment by Abo233** [comment]
一般情况下不会有这样的现象，但是强迫症看着好不爽。。

**Comment by Snownee** [comment]
我不是楼主……

**Comment by Abo233** [comment]
哦，雪尼。。

**Comment by Abo233** [comment]
说的明白点其实就是让某些方块像雪和栅栏那样可以穿透堆叠，，不然生成上会有大问题

**Comment by Abo233** [comment]
您想想我刚刚我说的那些情况，您就知道，那样有多奇怪了

**Comment by Abo233** [comment]
您可以学学aquatweak 这个mod，他修改了原版的水物理机制。。。好像只跟新了一点1.7.10，比如说什么栅栏可以被水穿透

**Comment by Abo233** [comment]
您有些细节你没发现，原版的水和栅栏有问题。1.13以下貌似都有这样的问题，

**Comment by Abo233** [comment]
您可以做到吗。。

**Comment by Abo233** [comment]
或者设置一个禁止某样方块生成在另一个方块上的黑名单。。。也可以解决许多生成错误的问题。。

**Comment by Abo233** [comment]
但是我说的一些情况可能解决不了。。
