### ISSUE TITLE
The mod require newer javafml:34.1

### ISSUE THREAD

**Issue by FoxieFlakey** [Snownee/SnowRealMagic#90]
The mod is downloaded from https://www.curseforge.com/minecraft/mc-mods/snow-real-magic/files/3082729 and im using forge with optifine 1.16.3 - 34.1.25 and i got in the log

[01:40:58] [Render thread/FATAL] [ne.mi.fm.ModLoader/CORE]: Error during pre-loading phase                                                                            
net.minecraftforge.fml.ModLoadingException: Mod File SnowRealMagic-1.16.3-2.2.1.jar needs language provider                                                            javafml:34.1 or above to load                                                                                                                                        
§7We have found 34.0

**Comment by Snownee** [comment]
What launcher are you using?

**Comment by FoxieFlakey** [comment]
TLauncher and custom script to elimate using launcher ever time to launch minecraft

**Comment by FoxieFlakey** [comment]
i only use TLauncher to generate run command then put my custom JVM flags to increase performace

**Comment by FoxieFlakey** [comment]
i use latest forge from the forge site

**Comment by FoxieFlakey** [comment]
and i regenerate the script with TLauncher a lot and triple check what version i start

**Comment by FoxieFlakey** [comment]
[crash-2020-10-22_16.14.48-fml.txt](https://github.com/Snownee/SnowRealMagic/files/5419634/crash-2020-10-22_16.14.48-fml.txt)
the crash report file if you need one

**Comment by Snownee** [comment]
The crash report shows you are using Forge 34.0.1

**Comment by FoxieFlakey** [comment]
wait, sorry i taking your time into this

**Comment by FoxieFlakey** [comment]
i dont know what wrong with the TLauncher
