### ISSUE TITLE
Crash on loading (shader issue)

### ISSUE THREAD

**Issue by Blugori** [Snownee/SnowRealMagic#93]
Hi, I got an issue that is when Sildur's vibrant shader is used, game will crash on load with snowrealmagic. (even with "old lightning : ON")

Minecraft : 1.16.4
Snow Real Magic : 2.2.1
Forge : 35.0.7
Kiwi : 3.4.0
Optifine : OptiFine_1.16.4_HD_U_G5

only those mods are installed

[crash-2020-11-09_23.48.07-client.txt](https://github.com/Snownee/SnowRealMagic/files/5513686/crash-2020-11-09_23.48.07-client.txt)
[debug.log](https://github.com/Snownee/SnowRealMagic/files/5513691/debug.log)
[latest.log](https://github.com/Snownee/SnowRealMagic/files/5513692/latest.log)

Best regards !

Ps : When I disable the shader, leave the game, start the game with the mod, and then enable the shader, it works fine, but it will crash on next launch if the shader isnt disabled

**Comment by TurboFunder** [comment]
Thanks for the tip!  I can keep playing while a fix is being worked on.
Here's my files for comparison.
All my versions are the same as Blugori, except Im running forge 35.0.15 and Kiwi 3.4.1

[crash-2020-11-14_19.14.29-client.txt](https://github.com/Snownee/SnowRealMagic/files/5541784/crash-2020-11-14_19.14.29-client.txt)
[debug.log](https://github.com/Snownee/SnowRealMagic/files/5541785/debug.log)
[latest.log](https://github.com/Snownee/SnowRealMagic/files/5541786/latest.log)

**Comment by kanauru** [comment]
It appears to crash on specific shaders.
For example BSL, Sildurs, and Vanilla Plus causes the crash.

It works fine on shaders like continuum, lagless , nostalgia, projectluma, seus and some others.

Like Blugori said, the only solution at the moment is to launch the game without shaders on or a working shader first.

**Comment by Snownee** [comment]
please test the new version, thanks

**Comment by kanauru** [comment]
It works now.

Thanks!
