### ISSUE TITLE
Kiwi/Snowmagic registry load error & registry creation error

### ISSUE THREAD

**Issue by aeixilimar** [Snownee/SnowRealMagic#94]
### ** NOTE THIS IS LITERALLY COPY PASTE FROM  KIWI FOR THE SAKE ERROR REPORTING **

So to get things down, I'm running the server from a local machine in my own house, separate from our own every day use machines and just sits in a corner, with a small monitor linked to it, have everything on the open network so a few friends can join and play. This only started happening in the last hour or so, current time 0141AM and began to occur at about 0030AM.

1. First error couldn't load/create registries with Kiwi --->Uninstalled kiwi and downloaded a new version.
2. Second error couldn't load registries with Snowagic ---> Uninstalled ran server, through up the error was with PlentyObiomes, Added SnowMagic again and once again it said it was an issue with SnowMagic.

Assuming SnowMagic bakes itself into the world and is required to run a world that has had SnowMagic on it previously. 
error logs from the server below.

Also will post this again into the Kiwi GitHub found here -> https://github.com/Snownee/Kiwi
 just for the sake of error reporting.

[crash-2020-11-20_01.10.51-fml.txt](https://github.com/Snownee/SnowRealMagic/files/5571889/crash-2020-11-20_01.10.51-fml.txt)
[crash-2020-11-20_01.20.05-fml.txt](https://github.com/Snownee/SnowRealMagic/files/5571890/crash-2020-11-20_01.20.05-fml.txt)
[crash-2020-11-20_01.17.26-fml.txt](https://github.com/Snownee/SnowRealMagic/files/5571891/crash-2020-11-20_01.17.26-fml.txt)
[crash-2020-11-20_00.42.36-fml.txt](https://github.com/Snownee/SnowRealMagic/files/5571894/crash-2020-11-20_00.42.36-fml.txt)
[crash-2020-11-20_00.48.14-fml.txt](https://github.com/Snownee/SnowRealMagic/files/5571895/crash-2020-11-20_00.48.14-fml.txt)
[crash-2020-11-20_01.02.35-fml.txt](https://github.com/Snownee/SnowRealMagic/files/5571896/crash-2020-11-20_01.02.35-fml.txt)

**Comment by Snownee** [comment]
Update BoP and clear config of SnowRealMagic
