### ISSUE TITLE
Bees unable to pollinate flowers with snow

### ISSUE THREAD

**Issue by WenXin20** [Snownee/SnowRealMagic#97]
* Forge Version: v35.1.13
 * Mod Version: v2.2.2

Bees are unable to pollinate flowers that generate with snow layers. This is mostly likely because the flower snow block doesn't inherit the `#minecraft:small_flowers` tag. Is it possible to have it inherit the tags of the parent block?

**Comment by Snownee** [comment]
it is impossible to fix every cases using current implementation. maybe after refactoring
